// packages/ds-vue/src/components/Avatar/Avatar.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import Image from "../Image/Image.vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  src?: string;
  name: string;
  initials?: string;
  priority?: boolean;
  size?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  priority: undefined,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "avatar",
  props.size ? `avatar--${props.size}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" :aria-label="props.name" role="img" :data-testid="props['data-testid']" data-fsds-component="avatar">
    <Image v-if="props.src" :class="'avatar__image'" :src="props.src" alt="" />
    <span v-if="props.initials" :class="'avatar__initials'">
      {{ props.initials }}
    </span>
  </div>
</template>

// packages/ds-svelte/src/components/Avatar/Avatar.svelte
<script lang="ts">
// @generated:start imports
import Image from "../Image/Image.svelte";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  src?: string;
  name: string;
  initials?: string;
  priority?: boolean;
  size?: string;
  class?: string;
}

let { src, name, initials, priority, size, class: className }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "avatar",
    size ? `avatar--${size}` : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} aria-label={name} data-fsds-component="avatar" role="img">
  {#if src}
  <Image class={'avatar__image'} src={src} alt="" />
  {/if}
  {#if initials}
  <span class={'avatar__initials'}>{initials}</span>
  {/if}
</div>
