// packages/ds-angular/src/components/Popover/Popover.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass, NgIf } from "@angular/common";
import { StackComponent } from "../../primitives/index.js";
import { usePopover } from "./usePopover.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type PopoverPlacement = "top" | "bottom" | "left" | "right" | "auto";
export type PopoverTriggerStrategy = "click" | "hover";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-popover",
  standalone: true,
  imports: [NgClass, NgIf],
  template: `<div [ngClass]="classes()">
  <button [ngClass]="'popover__trigger'" type="button" aria-haspopup="true" [attr.aria-expanded]="behavior.open()" aria-controls="popover-content">
    <ng-content />
  </button>
  <ng-container *ngIf="behavior.open()">
    <div [ngClass]="'popover__content'" id="popover-content">
      <ng-content />
    </div>
  </ng-container>
</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PopoverComponent {
  @Input() open?: boolean;
  @Input() defaultOpen?: boolean;
  @Input() placement?: PopoverPlacement = "auto";
  @Input() triggerStrategy?: PopoverTriggerStrategy = "click";
  @Input() offset?: number = 8;
  @Input() closeOnOutsideClick?: boolean;
  @Input() closeOnEscape?: boolean;
  @Input() anchor?: HTMLElement | null;
  @Input() class?: string;
  @Input() onOpenChange?: (value: boolean) => void;

  private destroyRef = inject(DestroyRef);
  protected behavior = usePopover({
    open: () => this.open,
    defaultOpen: this.defaultOpen,
    onOpenChange: (v) => this.onOpenChange?.(v),
    closeOnEscape: this.closeOnEscape,
    closeOnOutsideClick: this.closeOnOutsideClick,
    destroyRef: this.destroyRef,
  });

  classes = computed(() =>
    [
      "popover",
      this.placement ? `popover--${this.placement}` : null,
      this.class,
    ].filter(Boolean).join(" "),
  );

  protected handleOpenChange(event: Event): void {
    this.behavior.setOpen((event.target as HTMLInputElement).checked);
  }
}

@Component({
  selector: "fsds-popover-trigger",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="button" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PopoverTriggerComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["popover__trigger", this.class].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-popover-content",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PopoverContentComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["popover__content", this.class].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-lit/src/components/Popover/Popover.ts
// @generated:start imports
import { LitElement, html, css, nothing } from 'lit';
import { property } from 'lit/decorators.js';
import { PopoverBehavior } from './PopoverBehavior.js';
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type PopoverPlacement = "top" | "bottom" | "left" | "right" | "auto";
export type PopoverTriggerStrategy = "click" | "hover";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
export class PopoverElement extends LitElement {
  static override styles = css`:host { display: contents; }`;

  @property({ type: Boolean }) open?: boolean;
  @property({ type: Boolean }) defaultOpen?: boolean;
  @property() placement?: PopoverPlacement = "auto";
  @property() triggerStrategy?: PopoverTriggerStrategy = "click";
  @property({ type: Number }) offset?: number = 8;
  @property({ type: Boolean }) closeOnOutsideClick?: boolean;
  @property({ type: Boolean }) closeOnEscape?: boolean;
  @property() anchor?: HTMLElement | null;
  @property({ attribute: false }) onOpenChange?: (value: boolean) => void;

  private behavior = new PopoverBehavior(this, {
    open: () => this.open,
    defaultOpen: this.defaultOpen,
    onOpenChange: (v) => this.onOpenChange?.(v),
    closeOnEscape: this.closeOnEscape,
    closeOnOutsideClick: this.closeOnOutsideClick,
  });

  private handleOpenChange(event: Event): void {
    this.behavior.setOpen((event.target as HTMLInputElement).checked);
  }

  private computeClasses(): string {
    return [
      "popover",
      this.placement ? `popover--${this.placement}` : null,
    ].filter(Boolean).join(" ");
  }

  override render() {
    return html`<div class="${this.computeClasses()}">
  <button class=${'popover__trigger'} type="button" aria-haspopup="true" ?aria-expanded=${this.behavior.open} aria-controls="popover-content">
    <slot></slot>
  </button>
  ${this.behavior.open ? html`
  <div class=${'popover__content'} id="popover-content">
    <slot></slot>
  </div>
  ` : nothing}
</div>`;
  }
}

customElements.define('fsds-popover', PopoverElement);

export class PopoverTriggerElement extends LitElement {
  static override styles = css`:host { display: contents; }`;

  override render() {
    return html`<fsds-stack as="button" class="popover__trigger"><slot></slot></fsds-stack>`;
  }
}

customElements.define('fsds-popover-trigger', PopoverTriggerElement);

export class PopoverContentElement extends LitElement {
  static override styles = css`:host { display: contents; }`;

  override render() {
    return html`<fsds-stack class="popover__content"><slot></slot></fsds-stack>`;
  }
}

customElements.define('fsds-popover-content', PopoverContentElement);
// @generated:end

// @custom:start trailing

// @custom:end
