// packages/ds-svelte/src/components/Checkbox/Checkbox.svelte
<script lang="ts">
// @generated:start imports
import { useCheckbox } from "./useCheckbox.svelte.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type CheckboxSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  size?: CheckboxSize;
  checked?: boolean;
  defaultChecked?: boolean;
  onChange?: (checked: boolean) => void;
  indeterminate?: boolean;
  disabled?: boolean;
  name?: string;
  value?: string;
  ariaLabel?: string;
  ariaLabelledby?: string;
  class?: string;
}

let { size = "md", checked, defaultChecked, onChange, indeterminate, disabled, name, value, ariaLabel, ariaLabelledby, class: className }: Props = $props();
// @generated:end

// @generated:start hook
const behavior = useCheckbox({
  checked: () => checked,
  defaultChecked: () => defaultChecked,
  onChange: () => onChange,
});
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "checkbox",
    size ? `checkbox--${size}` : null,
    behavior.checked ? "checkbox--checked" : null,
    disabled ? "checkbox--disabled" : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<label class={classes} data-fsds-component="checkbox">
  <input class={'checkbox__input'} type="checkbox" onchange={(e) => behavior.setChecked((e.currentTarget as HTMLInputElement).checked)} checked={behavior.checked} disabled={disabled} name={name} value={value} aria-label={ariaLabel} aria-labelledby={ariaLabelledby} aria-checked={(indeterminate ? "mixed" : behavior.checked)} indeterminate={indeterminate} />
  <span class={'checkbox__indicator'} aria-hidden="true"></span>
</label>

// packages/ds-angular/src/components/Checkbox/Checkbox.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass } from "@angular/common";
import { useCheckbox } from "./useCheckbox.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type CheckboxSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-checkbox",
  standalone: true,
  imports: [NgClass],
  host: { "data-fsds-component": "checkbox" },
  template: `<label [ngClass]="classes()">
  <input [ngClass]="'checkbox__input'" type="checkbox" (change)="handleCheckedChange($event)" [checked]="behavior.checked()" [disabled]="disabled" [name]="name" [value]="value" [attr.aria-label]="ariaLabel" [attr.aria-labelledby]="ariaLabelledby" [attr.aria-checked]="(indeterminate ? 'mixed' : behavior.checked())" [indeterminate]="indeterminate" />
  <span [ngClass]="'checkbox__indicator'" aria-hidden="true"></span>
</label>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CheckboxComponent {
  @Input() size?: CheckboxSize = "md";
  @Input() checked?: boolean;
  @Input() defaultChecked?: boolean;
  @Input() onChange?: (checked: boolean) => void;
  @Input() indeterminate?: boolean;
  @Input() disabled?: boolean;
  @Input() name?: string;
  @Input() value?: string;
  @Input() ariaLabel?: string;
  @Input() ariaLabelledby?: string;
  @Input() class?: string;

  private destroyRef = inject(DestroyRef);
  protected behavior = useCheckbox({
    checked: () => this.checked,
    defaultChecked: this.defaultChecked,
    onChange: (v) => this.onChange?.(v),
    destroyRef: this.destroyRef,
  });

  classes = computed(() =>
    [
      "checkbox",
      (this.size ?? "md") ? `checkbox--${(this.size ?? "md")}` : null,
      this.behavior.checked() ? "checkbox--checked" : null,
      this.disabled ? "checkbox--disabled" : null,
      this.class,
    ].filter(Boolean).join(" "),
  );

  protected handleCheckedChange(event: Event): void {
    this.behavior.setChecked((event.target as HTMLInputElement).checked);
  }
}
// @generated:end

// @custom:start trailing

// @custom:end
