// packages/ds-vue/src/components/Tabs/Tabs.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useTabs, provideTabsContext } from "./useTabs.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type TabsOrientation = "horizontal" | "vertical";
export type TabsAppearance = "underline" | "pills";
export type TabsActivationMode = "automatic" | "manual";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  value?: string;
  defaultValue?: string;
  onValueChange?: (value: string) => void;
  orientation?: TabsOrientation;
  appearance?: TabsAppearance;
  activationMode?: TabsActivationMode;
  loop?: boolean;
  unmountInactive?: boolean;
  idBase?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  orientation: "horizontal",
  appearance: "underline",
  activationMode: "automatic",
  loop: true,
  unmountInactive: true,
});
// @generated:end

// @generated:start hook
const { activeTab, setActiveTab, registeredTabs, registerTab, unregisterTab, idBase } = useTabs({
  value: () => props.value,
  defaultValue: props.defaultValue,
  onValueChange: props.onValueChange,
  idBase: props.idBase,
});

provideTabsContext({
  activeTab,
  setActiveTab,
  registeredTabs,
  registerTab,
  unregisterTab,
  idBase,
  get orientation() { return props.orientation ?? "horizontal"; },
  get activationMode() { return props.activationMode ?? "automatic"; },
  get loop() { return props.loop ?? true; },
  get unmountInactive() { return props.unmountInactive ?? true; },
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "tabs",
  props.orientation ? `tabs--${props.orientation}` : null,
  props.appearance ? `tabs--${props.appearance}` : null,
  props.activationMode ? `tabs--${props.activationMode}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" :data-testid="props['data-testid']">
    <slot />
  </div>
</template>

// packages/ds-react-native/src/components/Tabs/Tabs.tsx
// @generated:start imports
import type { StyleProp, ViewStyle } from "react-native";
import { Pressable, Text as RNText, View } from "react-native";
import { type ReactNode, useMemo, useState } from "react";
import { useFsdsTheme } from "../../tokens";
import { createTabsStyles } from "./Tabs.styles";
// @generated:end

// @generated:start types
export type TabsOrientation = "horizontal" | "vertical";
export type TabsAppearance = "underline" | "pills";
export type TabsActivationMode = "automatic" | "manual";
// @generated:end

// @generated:start props
export interface TabsProps {
  value?: string;
  defaultValue?: string;
  onValueChange?: (value: string) => void;
  orientation?: TabsOrientation;
  appearance?: TabsAppearance;
  activationMode?: TabsActivationMode;
  loop?: boolean;
  unmountInactive?: boolean;
  idBase?: string;
  children?: ReactNode;
  style?: StyleProp<ViewStyle>;
  testID?: string;
  accessibilityLabel?: string;
  accessibilityLabelledBy?: string | string[];
}
// @generated:end

// @generated:start component
export function Tabs({
  value: controlledActiveTab,
  defaultValue = "",
  children,
  style,
  testID,
  accessibilityLabel,
  accessibilityLabelledBy,
}: TabsProps) {
  const fsdsTheme = useFsdsTheme();
  const styles = useMemo(() => createTabsStyles(fsdsTheme), [fsdsTheme]);
  const [uncontrolledActiveTab] = useState<string>((defaultValue ?? "") as string);
  const activeTab = controlledActiveTab ?? uncontrolledActiveTab;

  return (
    <View
      testID={testID}
      style={[styles.root, style]}
      accessibilityLabel={accessibilityLabel}
      accessibilityLabelledBy={accessibilityLabelledBy}
    >
      <View
        style={styles.list}
      >
        <Pressable
          style={styles.tab}
          accessibilityRole="tab"
          accessibilityState={{ selected: Boolean(activeTab) }}
        />
        <View
          style={styles.indicator}
          accessible={false}
        />
      </View>
      <View
        style={styles.panel}
      >
        {typeof children === "string" ? <RNText>{children}</RNText> : children}
      </View>
    </View>
  );
}
// @generated:end
