// packages/ds-angular/src/components/Truncate/Truncate.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass, NgIf } from "@angular/common";
import { StackComponent } from "../../primitives/index.js";
import { useTruncate } from "./useTruncate.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-truncate",
  standalone: true,
  imports: [NgClass, NgIf],
  template: `<div [ngClass]="classes()">
  <span [ngClass]="'truncate__content'" [style.--fsds-truncate-content-lines]="lines">
    <ng-content />
  </span>
  <ng-container *ngIf="expandable">
    <button [ngClass]="'truncate__toggle'" type="button" [attr.aria-expanded]="behavior.expanded()"></button>
  </ng-container>
</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TruncateComponent {
  @Input() lines?: number;
  @Input() expandable?: boolean;
  @Input() expanded?: boolean;
  @Input() defaultExpanded?: boolean;
  @Input() onExpandedChange?: (expanded: boolean) => void;
  @Input() expandText?: string = "Show more";
  @Input() collapseText?: string = "Show less";
  @Input() class?: string;

  private destroyRef = inject(DestroyRef);
  protected behavior = useTruncate({
    expanded: () => this.expanded,
    defaultExpanded: this.defaultExpanded,
    onExpandedChange: (v) => this.onExpandedChange?.(v),
    destroyRef: this.destroyRef,
  });

  classes = computed(() =>
    [
      "truncate",
      this.behavior.expanded() ? "truncate--expanded" : null,
      this.class,
    ].filter(Boolean).join(" "),
  );
}

@Component({
  selector: "fsds-truncate-content",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TruncateContentComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["truncate__content", this.class].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-svelte/src/components/Truncate/Truncate.svelte
<script lang="ts">
// @generated:start imports
import { useTruncate } from "./useTruncate.svelte.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  lines?: number;
  expandable?: boolean;
  expanded?: boolean;
  defaultExpanded?: boolean;
  onExpandedChange?: (expanded: boolean) => void;
  expandText?: string;
  collapseText?: string;
  class?: string;
  children?: import('svelte').Snippet;
}

let { lines, expandable, expanded, defaultExpanded, onExpandedChange, expandText = "Show more", collapseText = "Show less", class: className, children }: Props = $props();
// @generated:end

// @generated:start hook
const behavior = useTruncate({
  expanded: () => expanded,
  defaultExpanded: () => defaultExpanded,
  onExpandedChange: () => onExpandedChange,
});
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "truncate",
    behavior.expanded ? "truncate--expanded" : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes}>
  <span class={'truncate__content'} style:--fsds-truncate-content-lines={lines}>
    {@render children?.()}
  </span>
  {#if expandable}
  <button class={'truncate__toggle'} type="button" aria-expanded={behavior.expanded}></button>
  {/if}
</div>
