// packages/ds-angular/src/components/Calendar/useCalendar.ts
// @generated:start imports
import { DestroyRef, type Signal } from "@angular/core";
import { createControllableState, createDismissal, createPortal } from "../../primitives/index.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export interface UseCalendarOptions {
  value?: () => Date | Date[] | null | undefined;
  defaultValue?: Date | Date[] | null;
  onChange?: (value: Date | Date[] | null) => void;
  shouldCloseOnSelect?: boolean;
  portalId?: Element | string;
  destroyRef: DestroyRef;
}

export interface UseCalendarResult {
  value: Signal<Date | Date[] | null>;
  setValue: (next: Date | Date[] | null) => void;
  panelRef: { nativeElement: HTMLElement | null };
  portalTarget: Signal<Element | null>;
}
// @generated:end

// @custom:start types

// @custom:end

// @generated:start hook
export function useCalendar(options: UseCalendarOptions): UseCalendarResult {
  const { value: value, set: setValue } = createControllableState<Date | Date[] | null>({
    controlled: options.value,
    defaultValue: options.defaultValue ?? undefined as never,
    onChange: options.onChange,
  });

  const panelRef: { nativeElement: HTMLElement | null } = { nativeElement: null };
  const { target: portalTarget } = createPortal({
    enabled: true,
    target: () => options.portalId,
  });

  createDismissal({
    open: () => true,
    closeOnEscape: () => true,
    onDismiss: () => { void 0; },
    destroyRef: options.destroyRef,
  });

  return {
    value,
    setValue,
    panelRef,
    portalTarget,
  };
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-react/src/components/Calendar/useCalendar.ts
// @generated:start imports
import { type ReactNode, type RefObject, useRef } from "react";
import { useControllableState, useDismissal, usePortal } from "../../primitives/hooks";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export interface UseCalendarOptions {
  /** Controlled "value" value. */
  value?: Date | Date[] | null;
  /** Initial uncontrolled "value" value. */
  defaultValue?: Date | Date[] | null;
  /** Called when "value" changes. */
  onChange?: (value: Date | Date[] | null) => void;
  /** Selecting a date closes the popup (controlled by shouldCloseOnSelect). */
  shouldCloseOnSelect?: boolean;
  /** DOM element or selector for the portal mount point. */
  portalId?: Element | string;
}

export interface UseCalendarResult {
  value: Date | Date[] | null;
  setValue: (next: Date | Date[] | null) => void;
  panelRef: RefObject<HTMLDivElement | null>;
  renderInPortal: (node: ReactNode) => ReactNode;
}
// @generated:end

// @custom:start types

// @custom:end

// @generated:start hook
export function useCalendar(options: UseCalendarOptions = {}): UseCalendarResult {
  const [value, setValue] = useControllableState<Date | Date[] | null>({
    controlled: options.value,
    defaultValue: options.defaultValue ?? undefined as never,
    onChange: options.onChange,
  });

  const panelRef = useRef<HTMLDivElement>(null);
  const portal = usePortal({
    enabled: true,
    target: options.portalId,
  });

  return {
    value,
    setValue,
    panelRef,
    renderInPortal: portal.render,
  };
}
// @generated:end

// @custom:start trailing

// @custom:end
