// packages/ds-angular/src/components/Skeleton/Skeleton.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass } from "@angular/common";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type SkeletonVariant = "block" | "text" | "avatar" | "media" | "dataviz" | "actions";
export type SkeletonAnimate = "shimmer" | "wipe" | "pulse" | "none";
export type SkeletonDensity = "compact" | "regular" | "spacious";
export type SkeletonLines = number | { min: number; max: number };
export type SkeletonRadius = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-skeleton",
  standalone: true,
  imports: [NgClass],
  host: { "data-fsds-component": "skeleton" },
  template: `<div [ngClass]="classes()" [attr.role]="((decorative ?? true) ? 'presentation' : 'status')" [attr.aria-busy]="((decorative ?? true) ? 'false' : 'true')" [attr.aria-hidden]="((decorative ?? true) ? 'true' : 'false')" [attr.aria-label]="ariaLabel"></div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SkeletonComponent {
  @Input() variant?: SkeletonVariant = "block";
  @Input() animate?: SkeletonAnimate = "shimmer";
  @Input() density?: SkeletonDensity = "regular";
  @Input() aspectRatio?: string;
  @Input() lines?: SkeletonLines;
  @Input() radius?: SkeletonRadius;
  @Input() decorative?: boolean = true;
  @Input() ariaLabel?: string;
  @Input() class?: string;

  classes(): string {
    return [
      "skeleton",
      (this.variant ?? "block") ? `skeleton--${(this.variant ?? "block")}` : null,
      (this.animate ?? "shimmer") ? `skeleton--${(this.animate ?? "shimmer")}` : null,
      (this.density ?? "regular") ? `skeleton--${(this.density ?? "regular")}` : null,
      this.class,
    ].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-svelte/src/components/Skeleton/Skeleton.svelte
<script lang="ts">
// @generated:start imports

// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type SkeletonVariant = "block" | "text" | "avatar" | "media" | "dataviz" | "actions";
type SkeletonAnimate = "shimmer" | "wipe" | "pulse" | "none";
type SkeletonDensity = "compact" | "regular" | "spacious";
type SkeletonLines = number | { min: number; max: number };
type SkeletonRadius = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  variant?: SkeletonVariant;
  animate?: SkeletonAnimate;
  density?: SkeletonDensity;
  aspectRatio?: string;
  lines?: SkeletonLines;
  radius?: SkeletonRadius;
  decorative?: boolean;
  ariaLabel?: string;
  class?: string;
}

let { variant = "block", animate = "shimmer", density = "regular", aspectRatio, lines, radius, decorative = true, ariaLabel, class: className }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "skeleton",
    variant ? `skeleton--${variant}` : null,
    animate ? `skeleton--${animate}` : null,
    density ? `skeleton--${density}` : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} role={(decorative ? "presentation" : "status")} aria-busy={(decorative ? "false" : "true")} aria-hidden={(decorative ? "true" : "false")} aria-label={ariaLabel} data-fsds-component="skeleton"></div>
