// packages/ds-vue/src/components/Badge/Badge.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type BadgeVariant = "default" | "status" | "counter" | "tag";
export type BadgeIntent = "info" | "success" | "warning" | "danger";
export type BadgeSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  variant?: BadgeVariant;
  intent?: BadgeIntent;
  size?: BadgeSize;
  icon?: unknown;
  showStatusIcon?: boolean;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "badge",
  props.variant ? `badge--${props.variant}` : null,
  props.intent ? `badge--${props.intent}` : null,
  props.size ? `badge--${props.size}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <span :class="classNames" :data-testid="props['data-testid']">
    <span v-if="props.icon" :class="'badge__icon'" aria-hidden="true"></span>
    <span :class="'badge__content'">
      <slot />
    </span>
  </span>
</template>

// packages/ds-react/src/components/Badge/Badge.tsx
// @generated:start imports
import { type ReactNode } from "react";
import { Stack } from "../../primitives";
import "./Badge.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type BadgeVariant = "default" | "status" | "counter" | "tag";

export type BadgeIntent = "info" | "success" | "warning" | "danger";

export type BadgeSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface BadgeProps {
  variant?: BadgeVariant;
  intent?: BadgeIntent;
  size?: BadgeSize;
  icon?: ReactNode;
  showStatusIcon?: boolean;
  className?: string;
  "data-testid"?: string;
  children?: ReactNode;
}
// @generated:end

// @generated:start subcomponents
export interface BadgeContentProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function BadgeContent({
  children,
  className,
  "data-testid": testId,
}: BadgeContentProps) {
  const classNames = ["badge__content", className].filter(Boolean).join(" ");
  return (
    <Stack className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}
// @generated:end

// @generated:start component
export function Badge({
  variant,
  intent,
  size,
  className,
  "data-testid": testId,
  children,
  icon,
  showStatusIcon,
  ...rest
}: BadgeProps) {
  const classNames = [
    "badge",
    variant && `badge--${variant}`,
    intent && `badge--${intent}`,
    size && `badge--${size}`,
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <span className={`${classNames}`} data-testid={testId} {...rest}>
    {icon && (
      <span className="badge__icon" aria-hidden="true" />
    )}
    <span className="badge__content">
      {children}
    </span>
  </span>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end
