// packages/ds-angular/src/components/BrandSwitcher/BrandSwitcher.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass } from "@angular/common";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-brand-switcher",
  standalone: true,
  imports: [NgClass],
  template: `<div [ngClass]="classes()">
  <ng-content />
</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BrandSwitcherComponent {
  @Input() showAutoCycle?: boolean = false;
  @Input() showDensity?: boolean = false;
  @Input() showFonts?: boolean = false;
  @Input() compact?: boolean = false;
  @Input() sticky?: boolean = false;
  @Input() enableKeyboard?: boolean = true;
  @Input() class?: string;

  classes(): string {
    return [
      "brand-switcher",
      this.class,
    ].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/BrandSwitcher/BrandSwitcher.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  showAutoCycle?: boolean;
  showDensity?: boolean;
  showFonts?: boolean;
  compact?: boolean;
  sticky?: boolean;
  enableKeyboard?: boolean;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  showAutoCycle: false,
  showDensity: false,
  showFonts: false,
  compact: false,
  sticky: false,
  enableKeyboard: true,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "brand-switcher",
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" :data-testid="props['data-testid']">
    <slot />
  </div>
</template>
