// packages/ds-svelte/src/components/Sheet/Sheet.svelte
<script lang="ts">
// @generated:start imports
import { useSheet } from "./useSheet.svelte.js";
import { portal } from "../../primitives/index.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type SheetSide = "top" | "right" | "bottom" | "left";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  side?: SheetSide;
  modal?: boolean;
  class?: string;
  children?: import('svelte').Snippet;
  description?: import('svelte').Snippet;
  title?: import('svelte').Snippet;
}

let { open, defaultOpen, onOpenChange, side = "right", modal = true, class: className, children, description, title }: Props = $props();
// @generated:end

// @generated:start hook
const behavior = useSheet({
  open: () => open,
  defaultOpen: () => defaultOpen,
  onOpenChange: () => onOpenChange,
});
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "sheet",
    side ? `sheet--${side}` : null,
    behavior.openness ? "sheet--open" : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @generated:start fieldAssociation
const instanceId = $props.id();
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} aria-labelledby={title ? `${instanceId}-title` : undefined} data-fsds-component="sheet" use:portal={{ enabled: true }} role="dialog" onclick={(e) => { if (e.target === e.currentTarget) { behavior.setOpenness(false); } }}>
  {#if behavior.openness}
  <div class={'sheet__overlay'} aria-hidden="true"></div>
  {/if}
  {#if behavior.openness}
  <div class={'sheet__content'} role="dialog" aria-modal="true" aria-labelledby="sheet-title-id" aria-describedby="sheet-description-id" data-side={side}>
    <div class={'sheet__header'}>
      <h2 class={'sheet__title'} id={`${instanceId}-title`}>
        {@render title?.()}
      </h2>
      <p class={'sheet__description'}>
        {@render description?.()}
      </p>
      <button class={'sheet__close'} type="button" aria-label="Close sheet" onclick={() => behavior.setOpenness(!behavior.openness)}></button>
    </div>
    <div class={'sheet__body'}>
      {@render children?.()}
    </div>
    <div class={'sheet__footer'}></div>
  </div>
  {/if}
</div>

// packages/ds-angular/src/components/Sheet/Sheet.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass, NgIf } from "@angular/common";
import { StackComponent } from "../../primitives/index.js";
import { useSheet } from "./useSheet.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type SheetSide = "top" | "right" | "bottom" | "left";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-sheet",
  standalone: true,
  imports: [NgClass, NgIf],
  template: `<div [ngClass]="classes()">
  <ng-container *ngIf="behavior.openness()">
    <div [ngClass]="'sheet__overlay'" aria-hidden="true" role="presentation" (click)="behavior.setOpenness(false)"></div>
  </ng-container>
  <ng-container *ngIf="behavior.openness()">
    <div [ngClass]="'sheet__content'" role="dialog" aria-modal="true" aria-labelledby="sheet-title-id" aria-describedby="sheet-description-id" [attr.data-side]="side">
      <div [ngClass]="'sheet__header'">
        <h2 [ngClass]="'sheet__title'">
          <ng-content select="[slot=title]" />
        </h2>
        <p [ngClass]="'sheet__description'">
          <ng-content select="[slot=description]" />
        </p>
        <button [ngClass]="'sheet__close'" type="button" aria-label="Close sheet"></button>
      </div>
      <div [ngClass]="'sheet__body'">
        <ng-content />
      </div>
      <div [ngClass]="'sheet__footer'"></div>
    </div>
  </ng-container>
</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SheetComponent {
  @Input() open?: boolean;
  @Input() defaultOpen?: boolean;
  @Input() onOpenChange?: (open: boolean) => void;
  @Input() side?: SheetSide = "right";
  @Input() modal?: boolean = true;
  @Input() class?: string;

  private destroyRef = inject(DestroyRef);
  protected behavior = useSheet({
    open: () => this.open,
    defaultOpen: this.defaultOpen,
    onOpenChange: (v) => this.onOpenChange?.(v),
    destroyRef: this.destroyRef,
  });

  classes = computed(() =>
    [
      "sheet",
      this.side ? `sheet--${this.side}` : null,
      this.behavior.openness() ? "sheet--open" : null,
      this.class,
    ].filter(Boolean).join(" "),
  );

  protected handleOpennessChange(event: Event): void {
    this.behavior.setOpenness((event.target as HTMLInputElement).checked);
  }
}

@Component({
  selector: "fsds-sheet-content",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SheetContentComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["sheet__content", this.class].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-sheet-header",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="header" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SheetHeaderComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["sheet__header", this.class].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-sheet-title",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="h3" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SheetTitleComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["sheet__title", this.class].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-sheet-description",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="p" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SheetDescriptionComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["sheet__description", this.class].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-sheet-body",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SheetBodyComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["sheet__body", this.class].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-sheet-footer",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="footer" variant="horizontal" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SheetFooterComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["sheet__footer", this.class].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end
