// packages/ds-vue/src/components/Status/Status.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type StatusIntent = "info" | "success" | "warning" | "danger" | "error";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  status: StatusIntent;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "status",
  props.status ? `status--${props.status}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <span :class="classNames" :data-testid="props['data-testid']">
    <span :class="'status__icon'" aria-hidden="true"></span>
    <span :class="'status__label'">
      <slot />
    </span>
  </span>
</template>

// packages/ds-react/src/components/Status/Status.tsx
// @generated:start imports
import { type ReactNode } from "react";
import "./Status.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type StatusIntent = "info" | "success" | "warning" | "danger" | "error";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface StatusProps {
  status: StatusIntent;
  className?: string;
  "data-testid"?: string;
  children?: ReactNode;
}
// @generated:end

// @generated:start subcomponents

// @generated:end

// @generated:start component
export function Status({
  status,
  className,
  "data-testid": testId,
  children,
  ...rest
}: StatusProps) {
  const classNames = [
    "status",
    status && `status--${status}`,
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <span className={`${classNames}`} data-testid={testId} {...rest}>
    <span className="status__icon" aria-hidden="true" />
    <span className="status__label">
      {children}
    </span>
  </span>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end
