// packages/ds-angular/src/components/Calendar/Calendar.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass, NgFor } from "@angular/common";
import { StackComponent } from "../../primitives/index.js";
import { useCalendar } from "./useCalendar.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type CalendarMode = "single" | "range";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-calendar",
  standalone: true,
  imports: [NgClass, NgFor],
  host: { "data-fsds-component": "calendar" },
  template: `<div [ngClass]="classes()" role="application" data-fsds-box="">
  <div [ngClass]="'calendar__header'">
    <button [ngClass]="'calendar__nav'" aria-label="Previous month"></button>
    <span [ngClass]="'calendar__caption'">
      {{ (caption ?? 'Calendar') }}
    </span>
    <button [ngClass]="'calendar__nav'" aria-label="Next month"></button>
  </div>
  <table [ngClass]="'calendar__grid'" role="grid" aria-label="Calendar">
    <tbody>
      <tr>
        <ng-container *ngFor="let item of (days ?? []); let index = index">
          <td [ngClass]="'calendar__cell'" role="gridcell" [attr.data-calendar-index]="index">
            <button [ngClass]="'calendar__day'" (click)="behavior.setValue(item)">
              {{ item.getDate() }}
            </button>
          </td>
        </ng-container>
      </tr>
    </tbody>
  </table>
</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CalendarComponent {
  @Input() caption?: string = "Calendar";
  @Input() value?: Date | Date[] | null;
  @Input() defaultValue?: Date | Date[] | null;
  @Input() onChange?: (value: Date | Date[] | null) => void;
  @Input() mode?: CalendarMode = "single";
  @Input() disabled?: boolean;
  @Input() minDate?: Date;
  @Input() maxDate?: Date;
  @Input() locale?: string = "en-US";
  @Input() shouldCloseOnSelect?: boolean = true;
  @Input() days?: Date[];
  @Input() class?: string;

  private destroyRef = inject(DestroyRef);
  protected behavior = useCalendar({
    value: () => this.value,
    defaultValue: this.defaultValue,
    onChange: (v) => this.onChange?.(v),
    shouldCloseOnSelect: this.shouldCloseOnSelect,
    destroyRef: this.destroyRef,
  });

  classes = computed(() =>
    [
      "calendar",
      (this.mode ?? "single") ? `calendar--${(this.mode ?? "single")}` : null,
      this.disabled ? "calendar--disabled" : null,
      this.class,
    ].filter(Boolean).join(" "),
  );
}

@Component({
  selector: "fsds-calendar-header",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="header" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CalendarHeaderComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["calendar__header", this.class].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-svelte/src/components/Calendar/Calendar.svelte
<script lang="ts">
// @generated:start imports
import { useCalendar } from "./useCalendar.svelte.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type CalendarMode = "single" | "range";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  caption?: string;
  value?: Date | Date[] | null;
  defaultValue?: Date | Date[] | null;
  onChange?: (value: Date | Date[] | null) => void;
  mode?: CalendarMode;
  disabled?: boolean;
  minDate?: Date;
  maxDate?: Date;
  locale?: string;
  shouldCloseOnSelect?: boolean;
  days?: Date[];
  class?: string;
}

let { caption = "Calendar", value, defaultValue, onChange, mode = "single", disabled, minDate, maxDate, locale = "en-US", shouldCloseOnSelect = true, days, class: className }: Props = $props();
// @generated:end

// @generated:start hook
const behavior = useCalendar({
  value: () => value,
  defaultValue: () => defaultValue,
  onChange: () => onChange,
  shouldCloseOnSelect: () => shouldCloseOnSelect,
});
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "calendar",
    mode ? `calendar--${mode}` : null,
    disabled ? "calendar--disabled" : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} role="application" data-fsds-component="calendar" data-fsds-box="">
  <div class={'calendar__header'}>
    <button class={'calendar__nav'} aria-label="Previous month"></button>
    <span class={'calendar__caption'}>{caption}</span>
    <button class={'calendar__nav'} aria-label="Next month"></button>
  </div>
  <table class={'calendar__grid'} role="grid" aria-label="Calendar">
    <tbody>
      <tr>
        {#each (days ?? []) as item, index (index)}
        <td class={'calendar__cell'} role="gridcell" data-calendar-index={index}>
          <button class={'calendar__day'} onclick={() => behavior.setValue(item)}>{item.getDate()}</button>
        </td>
        {/each}
      </tr>
    </tbody>
  </table>
</div>
