// packages/ds-vue/src/primitives/Stack.vue
<script setup lang="ts">
import { computed } from "vue";

export interface StackProps {
  as?: string;
  variant?: "vertical" | "horizontal";
  className?: string;
}

const props = withDefaults(defineProps<StackProps>(), {
  as: "div",
  variant: "vertical",
});

const classNames = computed(() =>
  ["stack", `stack--${props.variant}`, props.className]
    .filter(Boolean)
    .join(" "),
);
</script>

<template>
  <component :is="props.as" :class="classNames">
    <slot />
  </component>
</template>

<style scoped>
.stack {
  display: flex;
}
.stack--vertical {
  flex-direction: column;
}
.stack--horizontal {
  flex-direction: row;
}
</style>

// packages/ds-react-native/src/primitives/stack.tsx
import { View, type StyleProp, type ViewStyle } from "react-native";
import type { ReactNode } from "react";

type StackVariant = "vertical" | "horizontal";

export interface StackProps {
  variant?: StackVariant;
  children?: ReactNode;
  style?: StyleProp<ViewStyle>;
  testID?: string;
}

export function Stack({
  variant = "vertical",
  children,
  style,
  testID,
}: StackProps) {
  const layoutStyle: ViewStyle = {
    display: "flex",
    flexDirection: variant === "horizontal" ? "row" : "column",
  };

  return (
    <View testID={testID} style={[layoutStyle, style]}>
      {children}
    </View>
  );
}
