// packages/ds-vue/src/components/Toast/Toast.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useToast } from "./useToast.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type ToastVariant = "info" | "success" | "warning" | "error";
export type ToastPoliteness = "polite" | "assertive";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  title?: string;
  variant?: ToastVariant;
  politeness?: ToastPoliteness;
  action?: unknown;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  variant: "info",
  politeness: "polite",
});
// @generated:end

// @generated:start hook
const behavior = useToast({
  open: () => props.open,
  onOpenChange: props.onOpenChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "toast",
  props.variant ? `toast--${props.variant}` : null,
  props.politeness ? `toast--${props.politeness}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" aria-live="polite" aria-label="Notifications" role="alert" :data-testid="props['data-testid']">
    <div v-if="behavior.open.value" :class="'toast__item'" role="status">
      <div :class="'toast__row'">
        <div v-if="props.title" :class="'toast__title'"></div>
        <div :class="'toast__description'">
          <slot />
        </div>
        <div v-if="props.action" :class="'toast__action'"></div>
        <button :class="'toast__close'" type="button" aria-label="Dismiss"></button>
      </div>
    </div>
  </div>
</template>

// packages/ds-svelte/src/components/Toast/Toast.svelte
<script lang="ts">
// @generated:start imports
import { useToast } from "./useToast.svelte.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type ToastVariant = "info" | "success" | "warning" | "error";
type ToastPoliteness = "polite" | "assertive";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  title?: string;
  variant?: ToastVariant;
  politeness?: ToastPoliteness;
  action?: unknown;
  class?: string;
  children?: import('svelte').Snippet;
}

let { open, onOpenChange, title, variant = "info", politeness = "polite", action, class: className, children }: Props = $props();
// @generated:end

// @generated:start hook
const behavior = useToast({
  open: () => open,
  onOpenChange: () => onOpenChange,
});
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "toast",
    variant ? `toast--${variant}` : null,
    politeness ? `toast--${politeness}` : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} aria-live="polite" aria-label="Notifications" role="alert">
  {#if behavior.open}
  <div class={'toast__item'} role="status">
    <div class={'toast__row'}>
      {#if title}
      <div class={'toast__title'}></div>
      {/if}
      <div class={'toast__description'}>
        {@render children?.()}
      </div>
      {#if action}
      <div class={'toast__action'}></div>
      {/if}
      <button class={'toast__close'} type="button" aria-label="Dismiss"></button>
    </div>
  </div>
  {/if}
</div>
