// packages/ds-react/src/components/Calendar/Calendar.tsx
// @generated:start imports
import { type HTMLAttributes, type ReactNode } from "react";
import { Stack } from "../../primitives";
import { useCalendar } from "./useCalendar";
import "./Calendar.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type CalendarMode = "single" | "range";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface CalendarProps extends Omit<HTMLAttributes<HTMLDivElement>, "caption" | "children" | "className" | "data-testid" | "days" | "defaultValue" | "disabled" | "locale" | "maxDate" | "minDate" | "mode" | "onChange" | "shouldCloseOnSelect" | "value"> {
  caption?: string;
  value?: Date | Date[] | null;
  defaultValue?: Date | Date[] | null;
  onChange?: (value: Date | Date[] | null) => void;
  mode?: CalendarMode;
  disabled?: boolean;
  minDate?: Date;
  maxDate?: Date;
  locale?: string;
  shouldCloseOnSelect?: boolean;
  days?: Date[];
  className?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start subcomponents
export interface CalendarHeaderProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function CalendarHeader({
  children,
  className,
  "data-testid": testId,
}: CalendarHeaderProps) {
  const classNames = ["calendar__header", className].filter(Boolean).join(" ");
  return (
    <Stack className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}
// @generated:end

// @generated:start component
export function Calendar({
  value: controlledValue,
  defaultValue,
  onChange,
  mode = "single",
  disabled,
  className,
  "data-testid": testId,
  caption = "Calendar",
  minDate,
  maxDate,
  locale = "en-US",
  shouldCloseOnSelect = true,
  days,
  ...rest
}: CalendarProps) {
  const { value, setValue } = useCalendar({
    value: controlledValue,
    defaultValue,
    onChange,
    shouldCloseOnSelect,
  });

  const classNames = [
    "calendar",
    mode && `calendar--${mode}`,
    disabled && "calendar--disabled",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <div className={`${classNames}`} role="application" data-testid={testId} data-fsds-component="calendar" data-fsds-box="" {...rest}>
    <div className="calendar__header">
      <button className="calendar__nav" aria-label="Previous month" />
      <span className="calendar__caption">
        {caption}
      </span>
      <button className="calendar__nav" aria-label="Next month" />
    </div>
    <table className="calendar__grid" role="grid" aria-label="Calendar">
      <tbody>
        <tr>
          {(days ?? []).map((item, index) => (
            <td className="calendar__cell" role="gridcell" data-calendar-index={index} key={index}>
              <button className="calendar__day" onClick={() => setValue(item)} tabIndex={-1}>
                {item.getDate()}
              </button>
            </td>
          ))}
        </tr>
      </tbody>
    </table>
  </div>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/Calendar/Calendar.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useCalendar } from "./useCalendar.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type CalendarMode = "single" | "range";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  caption?: string;
  value?: Date | Date[] | null;
  defaultValue?: Date | Date[] | null;
  onChange?: (value: Date | Date[] | null) => void;
  mode?: CalendarMode;
  disabled?: boolean;
  minDate?: Date;
  maxDate?: Date;
  locale?: string;
  shouldCloseOnSelect?: boolean;
  days?: Date[];
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  caption: "Calendar",
  mode: "single",
  disabled: undefined,
  locale: "en-US",
  shouldCloseOnSelect: true,
});
// @generated:end

// @generated:start hook
const behavior = useCalendar({
  value: () => props.value,
  defaultValue: props.defaultValue,
  onChange: props.onChange,
  shouldCloseOnSelect: props.shouldCloseOnSelect,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "calendar",
  props.mode ? `calendar--${props.mode}` : null,
  props.disabled ? "calendar--disabled" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" role="application" :data-testid="props['data-testid']" data-fsds-component="calendar" data-fsds-box="">
    <div :class="'calendar__header'">
      <button :class="'calendar__nav'" aria-label="Previous month"></button>
      <span :class="'calendar__caption'">
        {{ props.caption }}
      </span>
      <button :class="'calendar__nav'" aria-label="Next month"></button>
    </div>
    <table :class="'calendar__grid'" role="grid" aria-label="Calendar">
      <tbody>
        <tr>
          <td v-for="(item, index) in (props.days ?? [])" :key="index" :class="'calendar__cell'" role="gridcell" :data-calendar-index="index">
            <button :class="'calendar__day'" @click="() => behavior.setValue(item)" tabindex="-1">
              {{ item.getDate() }}
            </button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
