// packages/ds-svelte/src/components/Alert/Alert.svelte
<script lang="ts">
// @generated:start imports
import Button from "../Button/Button.svelte";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type AlertIntent = "info" | "success" | "warning" | "danger";
type AlertLevel = "inline" | "section" | "page";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  intent?: AlertIntent;
  level?: AlertLevel;
  dismissible?: boolean;
  onDismiss?: () => void;
  dismissLabel?: string;
  icon?: unknown;
  class?: string;
  children?: import('svelte').Snippet;
}

let { intent, level, dismissible, onDismiss, dismissLabel = "Dismiss", icon, class: className, children }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "alert",
    intent ? `alert--${intent}` : null,
    level ? `alert--${level}` : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} role="alert" data-fsds-component="alert" data-fsds-box="">
  {#if icon}
  <span class={'alert__icon'} aria-hidden="true">{icon}</span>
  {/if}
  {@render children?.()}
  {#if dismissible}
  <Button class={'alert__dismiss'} type="button" onClick={onDismiss} ariaLabel={dismissLabel} />
  {/if}
</div>

// packages/ds-vue/src/components/Alert/Alert.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import Button from "../Button/Button.vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type AlertIntent = "info" | "success" | "warning" | "danger";
export type AlertLevel = "inline" | "section" | "page";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  intent?: AlertIntent;
  level?: AlertLevel;
  dismissible?: boolean;
  onDismiss?: () => void;
  dismissLabel?: string;
  icon?: unknown;
  class?: string;
  dataTestid?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  dismissible: undefined,
  dismissLabel: "Dismiss",
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "alert",
  props.intent ? `alert--${props.intent}` : null,
  props.level ? `alert--${props.level}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" role="alert" :data-testid="props.dataTestid" data-fsds-component="alert" data-fsds-box="">
    <span v-if="props.icon" :class="'alert__icon'" aria-hidden="true">
      {{ props.icon }}
    </span>
    <slot />
    <Button v-if="props.dismissible" :class="'alert__dismiss'" type="button" @click="props.onDismiss?.()" :ariaLabel="props.dismissLabel" />
  </div>
</template>
