// packages/ds-angular/src/components/Dialog/useDialog.ts
// @generated:start imports
import { DestroyRef, computed, type Signal } from "@angular/core";
import { createControllableState, createDismissal, createFocusTrap, createScrollLock } from "../../primitives/index.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export interface UseDialogOptions {
  open?: () => boolean | undefined;
  defaultOpen?: boolean;
  onOpenChange?: (value: boolean) => void;
  closeOnEscape?: boolean;
  closeOnBackdropClick?: boolean;
  /** When false the surface is non-blocking: no focus trap, no scroll lock. */
  modal?: () => boolean | undefined;
  destroyRef: DestroyRef;
}

export interface UseDialogResult {
  openness: Signal<boolean>;
  setOpenness: (next: boolean) => void;
  panelRef: { nativeElement: HTMLElement | null };
}
// @generated:end

// @custom:start types

// @custom:end

// @generated:start hook
export function useDialog(options: UseDialogOptions): UseDialogResult {
  const { value: openness, set: setOpenness } = createControllableState<boolean>({
    controlled: options.open,
    defaultValue: options.defaultOpen ?? false,
    onChange: options.onOpenChange,
  });

  const panelRef: { nativeElement: HTMLElement | null } = { nativeElement: null };
  const blocking = computed(() => openness() && (options.modal?.() ?? true));
  createFocusTrap(panelRef, { active: blocking, destroyRef: options.destroyRef });

  createScrollLock(blocking, options.destroyRef);

  createDismissal({
    open: () => openness(),
    closeOnEscape: () => options.closeOnEscape,
    onDismiss: () => { setOpenness(false); },
    destroyRef: options.destroyRef,
  });

  return {
    openness,
    setOpenness,
    panelRef,
  };
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-react/src/components/Dialog/useDialog.ts
// @generated:start imports
import { type ReactNode, type RefObject, useRef } from "react";
import { useControllableState, useDismissal, useFocusTrap, usePortal, useScrollLock } from "../../primitives/hooks";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export interface UseDialogOptions {
  /** Controlled "openness" value. */
  open?: boolean;
  /** Initial uncontrolled "openness" value. */
  defaultOpen?: boolean;
  /** Called when "openness" changes. */
  onOpenChange?: (value: boolean) => void;
  /** Whether "escape" dismissal is enabled. */
  closeOnEscape?: boolean;
  /** Whether "overlayClick" dismissal is enabled. */
  closeOnBackdropClick?: boolean;
  /** When false the surface is non-blocking: no focus trap, no scroll lock. */
  modal?: boolean;
  /** Element to focus when the component activates. */
  initialFocus?: RefObject<HTMLElement | null>;
}

export interface UseDialogResult {
  openness: boolean;
  setOpenness: (next: boolean) => void;
  panelRef: RefObject<HTMLDivElement | null>;
  renderInPortal: (node: ReactNode) => ReactNode;
}
// @generated:end

// @custom:start types

// @custom:end

// @generated:start hook
export function useDialog(options: UseDialogOptions = {}): UseDialogResult {
  const [openness, setOpenness] = useControllableState<boolean>({
    controlled: options.open,
    defaultValue: options.defaultOpen ?? false,
    onChange: options.onOpenChange,
  });

  const panelRef = useRef<HTMLDivElement>(null);
  useDismissal({
    open: openness,
    onDismiss: () => setOpenness(false),
    closeOnEscape: options.closeOnEscape !== false,
  });

  useFocusTrap(panelRef, {
    active: openness && (options.modal ?? true),
    initialFocusRef: options.initialFocus,
  });

  useScrollLock(openness && (options.modal ?? true));

  const portal = usePortal({
    enabled: true,
  });

  return {
    openness,
    setOpenness,
    panelRef,
    renderInPortal: portal.render,
  };
}
// @generated:end

// @custom:start trailing

// @custom:end
