// packages/ds-angular/src/components/Tabs/TabsTab.component.ts
// @generated:start imports
import { Component, Input, OnInit, OnDestroy, computed, inject, DestroyRef, ChangeDetectionStrategy } from "@angular/core";
import { NgClass } from "@angular/common";
import { useTabsContext } from "./useTabs.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-tabs-tab",
  standalone: true,
  imports: [NgClass],
  template: `<button
  role="tab"
  type="button"
  [ngClass]="classes()"
  [attr.data-value]="value"
  [attr.id]="ctx.idBase + '-tab-' + value"
  [attr.aria-controls]="ctx.idBase + '-panel-' + value"
  [attr.aria-selected]="isActive()"
  [attr.tabindex]="isActive() ? 0 : -1"
  [disabled]="disabled"
  (click)="ctx.setActiveTab(value)"
><ng-content /></button>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TabsTabComponent implements OnInit, OnDestroy {
  @Input({ required: true }) value!: string;
  @Input() disabled?: boolean;
  @Input() class?: string;
  @Input() dataTestid?: string;

  protected ctx = useTabsContext();

  isActive = computed(() => this.ctx.activeTab() === this.value);

  classes = computed(() =>
    [
      "tabs__tab",
      this.isActive() && "tabs__tab--active",
      this.class,
    ].filter(Boolean).join(" "),
  );

  ngOnInit(): void {
    this.ctx.registerTab(this.value);
  }

  ngOnDestroy(): void {
    this.ctx.unregisterTab(this.value);
  }
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-svelte/src/components/Tabs/TabsTab.svelte
<script lang="ts">
// @generated:start imports
import { onMount, onDestroy } from "svelte";
import { useTabsContext } from "./useTabs.svelte.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  value: string;
  disabled?: boolean;
  class?: string;
  "data-testid"?: string;
  children?: import('svelte').Snippet;
}

let { value, disabled, class: className, "data-testid": dataTestid, children }: Props = $props();
// @generated:end

// @generated:start classes
const ctx = useTabsContext();

const isActive = $derived(ctx.activeTab === value);

const classes = $derived(
  [
    "tabs__tab",
    isActive && "tabs__tab--active",
    className,
  ]
    .filter(Boolean)
    .join(" "),
);
// @generated:end

// @generated:start trailing
onMount(() => {
  ctx.registerTab(value);
});

onDestroy(() => {
  ctx.unregisterTab(value);
});
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<button
  role="tab"
  type="button"
  class={classes}
  data-value={value}
  data-testid={dataTestid}
  id="{ctx.idBase}-tab-{value}"
  aria-controls="{ctx.idBase}-panel-{value}"
  aria-selected={isActive}
  tabindex={isActive ? 0 : -1}
  {disabled}
  onclick={() => ctx.setActiveTab(value)}
>
  {@render children?.()}
</button>
