// packages/ds-svelte/src/components/Accordion/AccordionContent.svelte
<script lang="ts">
// @generated:start imports
import { useAccordionContext } from "./useAccordion.svelte.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  value: string;
  class?: string;
  "data-testid"?: string;
  children?: import('svelte').Snippet;
}

let { value, class: className, "data-testid": dataTestid, children }: Props = $props();
// @generated:end

// @generated:start classes
const ctx = useAccordionContext();

const isOpen = $derived(ctx.isItemOpen(value));

const classes = $derived(["accordion__content", className].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div
  role="region"
  class={classes}
  id="{ctx.idBase}-content-{value}"
  aria-labelledby="{ctx.idBase}-trigger-{value}"
  hidden={!isOpen ? true : undefined}
  data-testid={dataTestid}
>
  <div class="accordion__contentInner">
    {@render children?.()}
  </div>
</div>

// packages/ds-vue/src/components/Accordion/AccordionContent.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useAccordionContext } from "./useAccordion.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  value: string;
  class?: string;
  dataTestid?: string;
}

const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const ctx = useAccordionContext();

const isOpen = computed(() => ctx.isItemOpen(props.value));

const classNames = computed(() =>
  ["accordion__content", props.class].filter(Boolean).join(" "),
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div
    role="region"
    :class="classNames"
    :id="`${ctx.idBase}-content-${props.value}`"
    :aria-labelledby="`${ctx.idBase}-trigger-${props.value}`"
    :hidden="!isOpen ? true : undefined"
    :data-testid="props.dataTestid"
  >
    <div class="accordion__contentInner">
      <slot />
    </div>
  </div>
</template>
