// packages/ds-angular/src/components/Accordion/AccordionContent.component.ts
// @generated:start imports
import { Component, Input, computed, ChangeDetectionStrategy } from "@angular/core";
import { NgClass } from "@angular/common";
import { useAccordionContext } from "./useAccordion.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-accordion-content",
  standalone: true,
  imports: [NgClass],
  template: `<div
  role="region"
  [ngClass]="classes()"
  [attr.id]="ctx.idBase + '-content-' + value"
  [attr.aria-labelledby]="ctx.idBase + '-trigger-' + value"
  [attr.hidden]="!isOpen() ? true : null"
><div class="accordion__contentInner"><ng-content /></div></div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AccordionContentComponent {
  @Input({ required: true }) value!: string;
  @Input() class?: string;
  @Input() dataTestid?: string;

  protected ctx = useAccordionContext();

  isOpen = computed(() => this.ctx.isItemOpen(this.value));

  classes = computed(() =>
    ["accordion__content", this.class].filter(Boolean).join(" "),
  );
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/Accordion/AccordionContent.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useAccordionContext } from "./useAccordion.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  value: string;
  class?: string;
  dataTestid?: string;
}

const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const ctx = useAccordionContext();

const isOpen = computed(() => ctx.isItemOpen(props.value));

const classNames = computed(() =>
  ["accordion__content", props.class].filter(Boolean).join(" "),
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div
    role="region"
    :class="classNames"
    :id="`${ctx.idBase}-content-${props.value}`"
    :aria-labelledby="`${ctx.idBase}-trigger-${props.value}`"
    :hidden="!isOpen ? true : undefined"
    :data-testid="props.dataTestid"
  >
    <div class="accordion__contentInner">
      <slot />
    </div>
  </div>
</template>
