// packages/ds-react/src/components/Accordion/Accordion.tsx
// @generated:start imports
import { type ReactNode } from "react";
import { Stack } from "../../primitives";
import { useAccordion } from "./useAccordion";
import "./Accordion.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type AccordionType = "single" | "multiple";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface AccordionProps {
  type?: AccordionType;
  value?: string | string[];
  defaultValue?: string | string[];
  onValueChange?: (value: string | string[]) => void;
  collapsible?: boolean;
  disabled?: boolean;
  className?: string;
  "data-testid"?: string;
  children?: ReactNode;
}
// @generated:end

// @generated:start subcomponents
export interface AccordionItemProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function AccordionItem({
  children,
  className,
  "data-testid": testId,
}: AccordionItemProps) {
  const classNames = ["accordion__item", className].filter(Boolean).join(" ");
  return (
    <Stack as="li" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface AccordionTriggerProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function AccordionTrigger({
  children,
  className,
  "data-testid": testId,
}: AccordionTriggerProps) {
  const classNames = ["accordion__trigger", className].filter(Boolean).join(" ");
  return (
    <Stack as="button" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface AccordionHeaderProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function AccordionHeader({
  children,
  className,
  "data-testid": testId,
}: AccordionHeaderProps) {
  const classNames = ["accordion__header", className].filter(Boolean).join(" ");
  return (
    <Stack as="header" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface AccordionContentProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function AccordionContent({
  children,
  className,
  "data-testid": testId,
}: AccordionContentProps) {
  const classNames = ["accordion__content", className].filter(Boolean).join(" ");
  return (
    <Stack className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}
// @generated:end

// @generated:start component
export function Accordion({
  value: controlledValue,
  defaultValue,
  onValueChange,
  type = "single",
  disabled,
  className,
  "data-testid": testId,
  children,
  collapsible = false,
  ...rest
}: AccordionProps) {
  const { openness, setOpenness } = useAccordion({
    value: controlledValue,
    defaultValue,
    onValueChange,
  });

  const classNames = [
    "accordion",
    type && `accordion--${type}`,
    disabled && "accordion--disabled",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <div className={`${classNames}`} data-testid={testId} {...rest}>
    <div className="accordion__item">
      <h3 className="accordion__header">
        <button className="accordion__trigger" type="button" aria-expanded={openness !== undefined ? (String(openness) as "true" | "false") : undefined}>
          {children}
          <span className="accordion__chevron" />
        </button>
      </h3>
      <div className="accordion__content">
        <div className="accordion__contentInner">
          {children}
        </div>
      </div>
    </div>
  </div>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/Accordion/Accordion.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useAccordion } from "./useAccordion.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type AccordionType = "single" | "multiple";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  type?: AccordionType;
  value?: string | string[];
  defaultValue?: string | string[];
  onValueChange?: (value: string | string[]) => void;
  collapsible?: boolean;
  disabled?: boolean;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  type: "single",
  collapsible: false,
});
// @generated:end

// @generated:start hook
const behavior = useAccordion({
  value: () => props.value,
  defaultValue: props.defaultValue,
  onValueChange: props.onValueChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "accordion",
  props.type ? `accordion--${props.type}` : null,
  props.disabled ? "accordion--disabled" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" :data-testid="props['data-testid']">
    <div :class="'accordion__item'">
      <h3 :class="'accordion__header'">
        <button :class="'accordion__trigger'" type="button" :aria-expanded="behavior.openness.value === undefined ? undefined : Boolean(behavior.openness.value)">
          <slot />
          <span :class="'accordion__chevron'"></span>
        </button>
      </h3>
      <div :class="'accordion__content'">
        <div :class="'accordion__contentInner'">
          <slot />
        </div>
      </div>
    </div>
  </div>
</template>
