// packages/ds-angular/src/components/Accordion/Accordion.component.ts
// @generated:start imports
import { Component, Input, OnChanges, SimpleChanges, ElementRef, computed, signal, forwardRef, inject, DestroyRef, ChangeDetectionStrategy } from "@angular/core";
import { NgClass } from "@angular/common";
import { useAccordion, AccordionContextToken } from "./useAccordion.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
let _accordionIdCounter = 0;

export type AccordionType = "single" | "multiple";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-accordion",
  standalone: true,
  imports: [NgClass],
  providers: [
    {
      provide: AccordionContextToken,
      useFactory: () => {
        const self = inject(forwardRef(() => AccordionComponent));
        const ctx: import("./useAccordion.js").AccordionContextValue = {
              get openness() { return self.behavior.openness; },
              toggleItem: (v: string) => self.toggleItem(v),
              isItemOpen: (v: string) => self.isItemOpen(v),
              get type() { return self._type; },
              get collapsible() { return self._collapsible; },
              get disabled() { return self._disabled; },
              get idBase() { return self.idBase; },
        };
        return ctx;
      },
      deps: [],
    },
  ],
  host: { "data-fsds-component": "accordion" },
  template: `<div data-fsds-box="" [ngClass]="classes()" (keydown)="handleKeyDown($event)"><ng-content /></div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AccordionComponent implements OnChanges {
  @Input() type?: AccordionType = "single";
  @Input() value?: string | string[];
  @Input() defaultValue?: string | string[];
  @Input() onValueChange?: (value: string | string[]) => void;
  @Input() collapsible?: boolean = false;
  @Input() disabled?: boolean;
  @Input() class?: string;

  _controlledValue = signal<string | string[] | undefined>(undefined);
  _type = signal<"single" | "multiple">("single");
  _collapsible = signal<boolean>(false);
  _disabled = signal<boolean>(false);
  readonly idBase = `accordion-${++_accordionIdCounter}`;

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["value"]) this._controlledValue.set(this.value);
    if (changes["type"]) this._type.set((this.type as "single" | "multiple") ?? "single");
    if (changes["collapsible"]) this._collapsible.set(this.collapsible ?? false);
    if (changes["disabled"]) this._disabled.set(this.disabled ?? false);
  }

  private destroyRef = inject(DestroyRef);
  private elRef = inject(ElementRef<HTMLElement>);
  protected behavior = useAccordion({
    value: () => this._controlledValue(),
    defaultValue: this.defaultValue,
    onValueChange: (v) => this.onValueChange?.(v),
    destroyRef: this.destroyRef,
  });

  isItemOpen(itemValue: string): boolean {
    const v = this.behavior.openness();
    return Array.isArray(v) ? v.includes(itemValue) : v === itemValue;
  }

  toggleItem(itemValue: string): void {
    const v = this.behavior.openness();
    if (this._type() === "multiple") {
      const current = Array.isArray(v) ? v : [];
      this.behavior.setOpenness(
        current.includes(itemValue)
          ? current.filter((x) => x !== itemValue)
          : [...current, itemValue],
      );
    } else {
      const current = typeof v === "string" ? v : "";
      this.behavior.setOpenness(current === itemValue && this._collapsible() ? "" : itemValue);
    }
  }

  handleKeyDown(e: KeyboardEvent): void {
    const key = e.key;
    if (key !== "ArrowDown" && key !== "ArrowUp" && key !== "Home" && key !== "End") {
      return;
    }
    const host = this.elRef.nativeElement as HTMLElement;
    const triggers = Array.from(
      host.querySelectorAll<HTMLButtonElement>("[data-disclosure-trigger]"),
    ).filter((el) => !el.disabled);
    if (triggers.length === 0) return;
    const currentIndex = triggers.indexOf(document.activeElement as HTMLButtonElement);
    let nextIndex = currentIndex;
    if (key === "ArrowDown") {
      nextIndex = currentIndex < 0 ? 0 : (currentIndex + 1) % triggers.length;
    } else if (key === "ArrowUp") {
      nextIndex = currentIndex < 0 ? triggers.length - 1 : (currentIndex - 1 + triggers.length) % triggers.length;
    } else if (key === "Home") {
      nextIndex = 0;
    } else {
      nextIndex = triggers.length - 1;
    }
    e.preventDefault();
    triggers[nextIndex]?.focus();
  }

  classes = computed(() =>
    [
      "accordion",
      (this.type ?? "single") ? `accordion--${(this.type ?? "single")}` : null,
      this.disabled ? "accordion--disabled" : null,
      this.class,
    ].filter(Boolean).join(" "),
  );
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/Accordion/Accordion.vue
<script setup lang="ts">
// @generated:start imports
import { computed, ref } from "vue";
import { useAccordion, provideAccordionContext } from "./useAccordion.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
let _accordionIdCounter = 0;

export type AccordionType = "single" | "multiple";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  type?: AccordionType;
  value?: string | string[];
  defaultValue?: string | string[];
  onValueChange?: (value: string | string[]) => void;
  collapsible?: boolean;
  disabled?: boolean;
  idBase?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  type: "single",
  collapsible: false,
});
// @generated:end

// @generated:start hook
const { openness, setOpenness } = useAccordion({
  value: () => props.value,
  defaultValue: props.defaultValue,
  onValueChange: props.onValueChange,
});

const idBase = props.idBase ?? `accordion-${++_accordionIdCounter}`;
const rootRef = ref<HTMLElement | null>(null);

function isItemOpen(itemValue: string): boolean {
  const v = openness.value;
  return Array.isArray(v) ? v.includes(itemValue) : v === itemValue;
}

function toggleItem(itemValue: string): void {
  const v = openness.value;
  if (props.type === "multiple") {
    const current = Array.isArray(v) ? v : [];
    setOpenness(
      current.includes(itemValue)
        ? current.filter((x) => x !== itemValue)
        : [...current, itemValue],
    );
  } else {
    const current = typeof v === "string" ? v : "";
    setOpenness(current === itemValue && props.collapsible ? "" : itemValue);
  }
}

function handleKeyDown(e: KeyboardEvent): void {
  const key = e.key;
  if (key !== "ArrowDown" && key !== "ArrowUp" && key !== "Home" && key !== "End") {
    return;
  }
  const root = rootRef.value;
  if (!root) return;
  const triggers = Array.from(
    root.querySelectorAll<HTMLButtonElement>("[data-disclosure-trigger]"),
  ).filter((el) => !el.disabled);
  if (triggers.length === 0) return;
  const currentIndex = triggers.indexOf(document.activeElement as HTMLButtonElement);
  let nextIndex = currentIndex;
  if (key === "ArrowDown") {
    nextIndex = currentIndex < 0 ? 0 : (currentIndex + 1) % triggers.length;
  } else if (key === "ArrowUp") {
    nextIndex = currentIndex < 0 ? triggers.length - 1 : (currentIndex - 1 + triggers.length) % triggers.length;
  } else if (key === "Home") {
    nextIndex = 0;
  } else {
    nextIndex = triggers.length - 1;
  }
  e.preventDefault();
  triggers[nextIndex]?.focus();
}

provideAccordionContext({
  openness,
  toggleItem,
  isItemOpen,
  get type() { return props.type ?? "single"; },
  get collapsible() { return props.collapsible ?? false; },
  get disabled() { return props.disabled ?? false; },
  idBase,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "accordion",
  props.type ? `accordion--${props.type}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div
    data-fsds-component="accordion" data-fsds-box=""
    ref="rootRef"
    :class="classNames"
    :data-testid="props['data-testid']"
    @keydown="handleKeyDown"
  >
    <slot />
  </div>
</template>
