// packages/ds-angular/src/components/Details/Details.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass, NgIf } from "@angular/common";
import { StackComponent } from "../../primitives/index.js";
import { useDetails } from "./useDetails.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type DetailsVariant = "default" | "inline" | "compact";
export type DetailsIcon = "left" | "right" | "none";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
let nextInstanceId = 0;

@Component({
  selector: "fsds-details",
  standalone: true,
  imports: [NgClass, NgIf],
  host: { "data-fsds-component": "details" },
  template: `<details [ngClass]="classes()" [open]="behavior.open()">
  <summary [ngClass]="'details__summary'" [attr.aria-controls]="summaryAriaControls">
    <span [ngClass]="'details__summaryContent'">
      <span [ngClass]="'details__icon'"></span>
      <span [ngClass]="'details__summaryText'">
        {{ summary }}
      </span>
    </span>
  </summary>
  <ng-container *ngIf="behavior.open()">
    <div [ngClass]="'details__content'" [attr.id]="instanceId + '-content'">
      <ng-content />
    </div>
  </ng-container>
</details>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DetailsComponent {
  @Input() summary!: string;
  @Input() open?: boolean;
  @Input() defaultOpen?: boolean;
  @Input() onOpenChange?: (open: boolean) => void;
  @Input() disabled?: boolean;
  @Input() variant?: DetailsVariant = "default";
  @Input() icon?: DetailsIcon = "left";
  @Input() class?: string;

  protected readonly instanceId = `fsds-details-${nextInstanceId++}`;

  private destroyRef = inject(DestroyRef);
  protected behavior = useDetails({
    open: () => this.open,
    defaultOpen: this.defaultOpen,
    onOpenChange: (v) => this.onOpenChange?.(v),
    destroyRef: this.destroyRef,
  });

  classes = computed(() =>
    [
      "details",
      (this.variant ?? "default") ? `details--${(this.variant ?? "default")}` : null,
      (this.icon ?? "left") ? `details--${(this.icon ?? "left")}` : null,
      this.behavior.open() ? "details--open" : null,
      this.disabled ? "details--disabled" : null,
      this.class,
    ].filter(Boolean).join(" "),
  );

  get summaryAriaControls(): string | undefined {
    return [this.open ? `${this.instanceId}-content` : null].filter(Boolean).join(" ") || undefined;
  }
}

@Component({
  selector: "fsds-details-content",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DetailsContentComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["details__content", this.class].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-svelte/src/components/Details/Details.svelte
<script lang="ts">
// @generated:start imports
import { useDetails } from "./useDetails.svelte.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type DetailsVariant = "default" | "inline" | "compact";
type DetailsIcon = "left" | "right" | "none";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  summary: string;
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  disabled?: boolean;
  variant?: DetailsVariant;
  icon?: DetailsIcon;
  class?: string;
  children?: import('svelte').Snippet;
}

let { summary, open, defaultOpen, onOpenChange, disabled, variant = "default", icon = "left", class: className, children }: Props = $props();
// @generated:end

// @generated:start hook
const behavior = useDetails({
  open: () => open,
  defaultOpen: () => defaultOpen,
  onOpenChange: () => onOpenChange,
});
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "details",
    variant ? `details--${variant}` : null,
    icon ? `details--${icon}` : null,
    behavior.open ? "details--open" : null,
    disabled ? "details--disabled" : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @generated:start fieldAssociation
const instanceId = $props.id();
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<details class={classes} open={behavior.open} data-fsds-component="details" role="group">
  <summary class={'details__summary'} aria-controls={open ? `${instanceId}-content` : undefined}>
    <span class={'details__summaryContent'}>
      <span class={'details__icon'}></span>
      <span class={'details__summaryText'}>{summary}</span>
    </span>
  </summary>
  {#if behavior.open}
  <div class={'details__content'} id={`${instanceId}-content`}>
    {@render children?.()}
  </div>
  {/if}
</details>
