// packages/ds-angular/src/components/NavTree/NavTree.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass, NgIf, NgFor } from "@angular/common";
import { StackComponent } from "../../primitives/index.js";
import { resolveIcon } from "@full-stack-ds/iconography";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type NavTreeIconSize = "sm" | "md";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
const ICON_GLYPH_SIZE_HINTS: Record<string, number> = { "sm": 16, "md": 20 };

@Component({
  selector: "fsds-nav-tree",
  standalone: true,
  imports: [NgClass, NgIf, NgFor],
  host: { "data-fsds-component": "nav-tree" },
  template: `<li [ngClass]="classes()" data-fsds-box="" role="listitem">
  <div [ngClass]="'nav-tree__heading'">
    <ng-container *ngIf="icon">
      <span [ngClass]="'nav-tree__icon'" aria-hidden="true">
        <ng-container *ngIf="iconGlyph as glyph">
          <svg fill="none" xmlns="http://www.w3.org/2000/svg" [attr.data-fsds-icon]="glyph.name" [attr.viewBox]="glyph.viewBox" [attr.width]="(this.iconGlyphPx ?? glyph.size)" [attr.height]="(this.iconGlyphPx ?? glyph.size)">
            <ng-container *ngFor="let glyphPath of glyph.paths">
              <path [attr.d]="glyphPath.d" [attr.fill]="glyphPath.fill" [attr.stroke]="glyphPath.stroke" [attr.stroke-width]="glyphPath.strokeWidth" [attr.stroke-linecap]="glyphPath.strokeLineCap" [attr.stroke-linejoin]="glyphPath.strokeLineJoin" [attr.stroke-dasharray]="glyphPath.strokeDasharray" [attr.fill-rule]="glyphPath.fillRule" [attr.clip-rule]="glyphPath.clipRule" />
            </ng-container>
          </svg>
        </ng-container>
      </span>
    </ng-container>
    <ng-container *ngIf="href">
      <a [ngClass]="'nav-tree__headingLink'" [href]="href">
        {{ label }}
      </a>
    </ng-container>
    <ng-container *ngIf="!href">
      <span [ngClass]="'nav-tree__headingLabel'">
        {{ label }}
      </span>
    </ng-container>
  </div>
  <ul [ngClass]="'nav-tree__list'">
    <ng-content />
  </ul>
</li>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NavTreeComponent {
  @Input() label!: string;
  @Input() href?: string;
  @Input() icon?: string;
  @Input() iconSize?: NavTreeIconSize = "sm";
  @Input() class?: string;

  classes(): string {
    return [
      "nav-tree",
      (this.iconSize ?? "sm") ? `nav-tree--${(this.iconSize ?? "sm")}` : null,
      this.class,
    ].filter(Boolean).join(" ");
  }

  get iconGlyphPx(): number | undefined {
    return ICON_GLYPH_SIZE_HINTS[(this.iconSize ?? "sm")];
  }

  get iconGlyph() {
    return resolveIcon(this.icon ?? "", this.iconGlyphPx ?? Number.NaN);
  }
}

@Component({
  selector: "fsds-nav-tree-list",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="ul" variant="horizontal" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NavTreeListComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["nav-tree__list", this.class].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-nav-tree-item",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="li" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NavTreeItemComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["nav-tree__item", this.class].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-svelte/src/components/NavTree/NavTree.svelte
<script lang="ts">
// @generated:start imports
import { resolveIcon } from "@full-stack-ds/iconography";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type NavTreeIconSize = "sm" | "md";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  label: string;
  href?: string;
  icon?: string;
  iconSize?: NavTreeIconSize;
  class?: string;
  children?: import('svelte').Snippet;
}

let { label, href, icon, iconSize = "sm", class: className, children }: Props = $props();
// @generated:end

// @generated:start iconGlyph
const ICON_GLYPH_SIZE_HINTS: Record<string, number> = { "sm": 16, "md": 20 };
const iconGlyphPx = $derived(ICON_GLYPH_SIZE_HINTS[iconSize]);
const iconGlyph = $derived(resolveIcon(icon ?? "", iconGlyphPx ?? Number.NaN));
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "nav-tree",
    iconSize ? `nav-tree--${iconSize}` : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<li class={classes} data-fsds-component="nav-tree" data-fsds-box="" role="listitem">
  <div class={'nav-tree__heading'}>
    {#if icon}
    <span class={'nav-tree__icon'} aria-hidden="true">
      {#if iconGlyph}
      <svg fill="none" xmlns="http://www.w3.org/2000/svg" data-fsds-icon={iconGlyph.name} viewBox={iconGlyph.viewBox} width={iconGlyphPx ?? iconGlyph.size} height={iconGlyphPx ?? iconGlyph.size}>
        {#each iconGlyph.paths as glyphPath, glyphIndex (glyphIndex)}
          <path d={glyphPath.d} fill={glyphPath.fill} stroke={glyphPath.stroke} stroke-width={glyphPath.strokeWidth} stroke-linecap={glyphPath.strokeLineCap} stroke-linejoin={glyphPath.strokeLineJoin} stroke-dasharray={glyphPath.strokeDasharray} fill-rule={glyphPath.fillRule} clip-rule={glyphPath.clipRule} />
        {/each}
      </svg>
      {/if}
    </span>
    {/if}
    {#if href}
    <a class={'nav-tree__headingLink'} href={href}>{label}</a>
    {/if}
    {#if !href}
    <span class={'nav-tree__headingLabel'}>{label}</span>
    {/if}
  </div>
  <ul class={'nav-tree__list'}>
    {@render children?.()}
  </ul>
</li>
