// packages/ds-vue/src/components/Truncate/Truncate.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useTruncate } from "./useTruncate.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  lines?: number;
  expandable?: boolean;
  expanded?: boolean;
  defaultExpanded?: boolean;
  onExpandedChange?: (expanded: boolean) => void;
  expandText?: string;
  collapseText?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  expandable: undefined,
  expanded: undefined,
  defaultExpanded: undefined,
  expandText: "Show more",
  collapseText: "Show less",
});
// @generated:end

// @generated:start hook
const behavior = useTruncate({
  expanded: () => props.expanded,
  defaultExpanded: props.defaultExpanded,
  onExpandedChange: props.onExpandedChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "truncate",
  behavior.expanded.value ? "truncate--expanded" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" :data-testid="props['data-testid']">
    <span :class="'truncate__content'" :style="{ '--fsds-truncate-content-lines': props.lines }">
      <slot />
    </span>
    <button v-if="props.expandable" :class="'truncate__toggle'" type="button" @click="() => behavior.setExpanded(!behavior.expanded.value)" :aria-expanded="behavior.expanded.value">
      {{ (behavior.expanded.value ? props.collapseText : props.expandText) }}
    </button>
  </div>
</template>

// packages/ds-react/src/components/Truncate/Truncate.tsx
// @generated:start imports
import { type ReactNode } from "react";
import { Stack } from "../../primitives";
import { useTruncate } from "./useTruncate";
import "./Truncate.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface TruncateProps {
  lines?: number;
  expandable?: boolean;
  expanded?: boolean;
  defaultExpanded?: boolean;
  onExpandedChange?: (expanded: boolean) => void;
  expandText?: string;
  collapseText?: string;
  className?: string;
  "data-testid"?: string;
  children?: ReactNode;
}
// @generated:end

// @generated:start subcomponents
export interface TruncateContentProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function TruncateContent({
  children,
  className,
  "data-testid": testId,
}: TruncateContentProps) {
  const classNames = ["truncate__content", className].filter(Boolean).join(" ");
  return (
    <Stack className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}
// @generated:end

// @generated:start component
export function Truncate({
  expanded: controlledExpanded,
  defaultExpanded,
  onExpandedChange,
  className,
  "data-testid": testId,
  children,
  lines,
  expandable,
  expandText = "Show more",
  collapseText = "Show less",
  ...rest
}: TruncateProps) {
  const { expanded, setExpanded } = useTruncate({
    expanded: controlledExpanded,
    defaultExpanded,
    onExpandedChange,
  });

  const classNames = [
    "truncate",
    expanded && "truncate--expanded",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <div className={`${classNames}`} data-testid={testId} {...rest}>
    <span className="truncate__content">
      {children}
    </span>
    {expandable && (
      <button className="truncate__toggle" type="button" aria-expanded={expanded} />
    )}
  </div>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end
