// packages/ds-vue/src/components/Checkbox/Checkbox.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useCheckbox } from "./useCheckbox.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type CheckboxSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  size?: CheckboxSize;
  checked?: boolean;
  defaultChecked?: boolean;
  onChange?: (checked: boolean) => void;
  indeterminate?: boolean;
  disabled?: boolean;
  name?: string;
  value?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  size: "md",
  checked: undefined,
  defaultChecked: undefined,
  indeterminate: undefined,
  disabled: undefined,
});
// @generated:end

// @generated:start hook
const behavior = useCheckbox({
  checked: () => props.checked,
  defaultChecked: props.defaultChecked,
  onChange: props.onChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "checkbox",
  props.size ? `checkbox--${props.size}` : null,
  behavior.checked.value ? "checkbox--checked" : null,
  props.disabled ? "checkbox--disabled" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <input :class="classNames" type="checkbox" @change="(e) => behavior.setChecked((e.target as HTMLInputElement).checked)" :checked="behavior.checked.value" :disabled="props.disabled" :name="props.name" :value="props.value" role="checkbox" :data-testid="props['data-testid']" />
</template>

// packages/ds-react/src/components/Checkbox/Checkbox.tsx
// @generated:start imports
import { type InputHTMLAttributes, type ReactNode } from "react";
import { useCheckbox } from "./useCheckbox";
import "./Checkbox.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type CheckboxSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface CheckboxProps extends Omit<InputHTMLAttributes<HTMLInputElement>, "checked" | "children" | "className" | "data-testid" | "defaultChecked" | "disabled" | "indeterminate" | "name" | "onChange" | "size" | "value"> {
  size?: CheckboxSize;
  checked?: boolean;
  defaultChecked?: boolean;
  onChange?: (checked: boolean) => void;
  indeterminate?: boolean;
  disabled?: boolean;
  name?: string;
  value?: string;
  className?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start subcomponents

// @generated:end

// @generated:start component
export function Checkbox({
  checked: controlledChecked,
  defaultChecked,
  onChange,
  size = "md",
  disabled,
  className,
  "data-testid": testId,
  indeterminate,
  name,
  value,
  ...rest
}: CheckboxProps) {
  const { checked, setChecked } = useCheckbox({
    checked: controlledChecked,
    defaultChecked,
    onChange,
  });

  const classNames = [
    "checkbox",
    size && `checkbox--${size}`,
    checked && "checkbox--checked",
    disabled && "checkbox--disabled",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <input className={`${classNames}`} type="checkbox" onChange={(e) => setChecked(e.target.checked)} checked={checked} disabled={disabled} role="checkbox" data-testid={testId} {...rest} />
  );
}
// @generated:end

// @custom:start trailing

// @custom:end
