// packages/ds-angular/src/components/Progress/Progress.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass, NgIf } from "@angular/common";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type ProgressVariant = "linear" | "circular";
export type ProgressSize = "sm" | "md" | "lg";
export type ProgressIntent = "info" | "success" | "warning" | "danger";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-progress",
  standalone: true,
  imports: [NgClass, NgIf],
  host: { "data-fsds-component": "progress" },
  template: `<div [ngClass]="classes()" role="progressbar" [attr.aria-valuenow]="value" aria-valuemin="0" aria-valuemax="100" [attr.aria-label]="label" data-fsds-box="">
  <span [ngClass]="'progress__track'" aria-hidden="true">
    <span [ngClass]="'progress__fill'" [style.--fsds-progress-fill-width]="value"></span>
  </span>
  <ng-container *ngIf="showValue">
    <span [ngClass]="'progress__value'">
      <ng-content />
    </span>
  </ng-container>
</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProgressComponent {
  @Input() value?: number;
  @Input() variant?: ProgressVariant;
  @Input() size?: ProgressSize;
  @Input() intent?: ProgressIntent;
  @Input() label?: string;
  @Input() showValue?: boolean;
  @Input() formatValue?: (value: number, max: number) => string;
  @Input() class?: string;

  classes(): string {
    return [
      "progress",
      this.variant ? `progress--${this.variant}` : null,
      this.size ? `progress--${this.size}` : null,
      this.intent ? `progress--${this.intent}` : null,
      this.class,
    ].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-svelte/src/components/Progress/Progress.svelte
<script lang="ts">
// @generated:start imports

// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type ProgressVariant = "linear" | "circular";
type ProgressSize = "sm" | "md" | "lg";
type ProgressIntent = "info" | "success" | "warning" | "danger";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  value?: number;
  variant?: ProgressVariant;
  size?: ProgressSize;
  intent?: ProgressIntent;
  label?: string;
  showValue?: boolean;
  formatValue?: (value: number, max: number) => string;
  class?: string;
  children?: import('svelte').Snippet;
}

let { value, variant, size, intent, label, showValue, formatValue, class: className, children }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "progress",
    variant ? `progress--${variant}` : null,
    size ? `progress--${size}` : null,
    intent ? `progress--${intent}` : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} role="progressbar" aria-valuenow={value} aria-valuemin="0" aria-valuemax="100" aria-label={label} data-fsds-component="progress" data-fsds-box="">
  <span class={'progress__track'} aria-hidden="true">
    <span class={'progress__fill'} style:--fsds-progress-fill-width={value}></span>
  </span>
  {#if showValue}
  <span class={'progress__value'}>
    {@render children?.()}
  </span>
  {/if}
</div>
