// packages/ds-angular/src/components/Walkthrough/useWalkthrough.ts
// @generated:start imports
import { DestroyRef, type Signal } from "@angular/core";
import { createControllableState, createDismissal } from "../../primitives/index.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export interface UseWalkthroughOptions {
  index?: () => number | undefined;
  defaultIndex?: number;
  onStepChange?: (value: number) => void;
  closeOnOutsideClick?: boolean;
  destroyRef: DestroyRef;
}

export interface UseWalkthroughResult {
  step: Signal<number>;
  setStep: (next: number) => void;
  panelRef: { nativeElement: HTMLElement | null };
}
// @generated:end

// @custom:start types

// @custom:end

// @generated:start hook
export function useWalkthrough(options: UseWalkthroughOptions): UseWalkthroughResult {
  const { value: step, set: setStep } = createControllableState<number>({
    controlled: options.index,
    defaultValue: options.defaultIndex ?? 0,
    onChange: options.onStepChange,
  });

  const panelRef: { nativeElement: HTMLElement | null } = { nativeElement: null };
  createDismissal({
    open: () => true,
    closeOnEscape: () => true,
    onDismiss: () => { void 0; },
    destroyRef: options.destroyRef,
  });

  return {
    step,
    setStep,
    panelRef,
  };
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-react/src/components/Walkthrough/useWalkthrough.ts
// @generated:start imports
import { type ReactNode, type RefObject, useRef } from "react";
import { useControllableState, useDismissal, usePortal } from "../../primitives/hooks";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export interface UseWalkthroughOptions {
  /** Controlled "step" value. */
  index?: number;
  /** Initial uncontrolled "step" value. */
  defaultIndex?: number;
  /** Called when "step" changes. */
  onStepChange?: (value: number) => void;
  /** Whether "outsideClick" dismissal is enabled. */
  closeOnOutsideClick?: boolean;
}

export interface UseWalkthroughResult {
  step: number;
  setStep: (next: number) => void;
  panelRef: RefObject<HTMLDivElement | null>;
  renderInPortal: (node: ReactNode) => ReactNode;
}
// @generated:end

// @custom:start types

// @custom:end

// @generated:start hook
export function useWalkthrough(options: UseWalkthroughOptions = {}): UseWalkthroughResult {
  const [step, setStep] = useControllableState<number>({
    controlled: options.index,
    defaultValue: options.defaultIndex ?? 0,
    onChange: options.onStepChange,
  });

  const panelRef = useRef<HTMLDivElement>(null);
  const portal = usePortal({
    enabled: true,
  });

  return {
    step,
    setStep,
    panelRef,
    renderInPortal: portal.render,
  };
}
// @generated:end

// @custom:start trailing

// @custom:end
