// packages/ds-vue/src/components/Label/Label.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  htmlFor?: string;
  form?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "label",
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <label :class="classNames" :for="props.htmlFor" :form="props.form" :data-testid="props['data-testid']" data-fsds-component="label" data-fsds-box="">
    <slot />
  </label>
</template>

// packages/ds-angular/src/components/Label/Label.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass } from "@angular/common";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-label",
  standalone: true,
  imports: [NgClass],
  host: { "data-fsds-component": "label" },
  template: `<label [ngClass]="classes()" [htmlFor]="htmlFor" [attr.form]="form" data-fsds-box="">
  <ng-content />
</label>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LabelComponent {
  @Input() htmlFor?: string;
  @Input() form?: string;
  @Input() class?: string;

  classes(): string {
    return [
      "label",
      this.class,
    ].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end
