// packages/ds-react/src/components/Select/Select.tsx
// @generated:start imports
import { type HTMLAttributes, type ReactNode, useId } from "react";
import { Stack } from "../../primitives";
import { useSelect } from "./useSelect";
import "./Select.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type SelectSize = "sm" | "md" | "lg";

export type SelectOption = { value: string; label: string; disabled?: boolean };
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface SelectProps extends Omit<HTMLAttributes<HTMLDivElement>, "children" | "className" | "data-testid" | "defaultOpen" | "defaultValue" | "disabled" | "empty" | "filterFn" | "multiple" | "onChange" | "onOpenChange" | "open" | "options" | "position" | "searchable" | "size" | "value"> {
  options?: SelectOption[];
  value?: string | string[];
  defaultValue?: string | string[];
  onChange?: (value: string | string[]) => void;
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  multiple?: boolean;
  disabled?: boolean;
  size?: SelectSize;
  filterFn?: ((option: SelectOption, searchTerm: string) => boolean);
  searchable?: boolean;
  empty?: boolean;
  position?: string;
  className?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start subcomponents
export interface SelectTriggerProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function SelectTrigger({
  children,
  className,
  "data-testid": testId,
}: SelectTriggerProps) {
  const classNames = ["select__trigger", className].filter(Boolean).join(" ");
  return (
    <Stack as="button" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface SelectContentProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function SelectContent({
  children,
  className,
  "data-testid": testId,
}: SelectContentProps) {
  const classNames = ["select__content", className].filter(Boolean).join(" ");
  return (
    <Stack className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface SelectOptionProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function SelectOption({
  children,
  className,
  "data-testid": testId,
}: SelectOptionProps) {
  const classNames = ["select__option", className].filter(Boolean).join(" ");
  return (
    <Stack as="li" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}
// @generated:end

// @generated:start component
export function Select({
  value: controlledValue,
  defaultValue = "beta",
  onChange,
  open: controlledOpen,
  defaultOpen = true,
  onOpenChange,
  size = "md",
  position,
  disabled,
  className,
  "data-testid": testId,
  options = [{"value":"alpha","label":"Alpha"},{"value":"beta","label":"Beta"},{"value":"gamma","label":"Gamma"}],
  multiple,
  filterFn,
  searchable,
  empty,
  ...rest
}: SelectProps) {
  const { selection, setSelection, open, setOpen } = useSelect({
    value: controlledValue,
    defaultValue,
    onChange,
    open: controlledOpen,
    defaultOpen,
    onOpenChange,
  });

  const classNames = [
    "select",
    size && `select--${size}`,
    position && `select--${position}`,
    open && "select--open",
    disabled && "select--disabled",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  const instanceId = useId();

  return (
  <Stack layout="native" className={`${classNames}`} role="combobox" aria-haspopup="listbox" aria-controls="fsds-select-listbox" aria-expanded={open} aria-disabled={disabled} data-testid={testId} data-fsds-component="select" {...rest}>
    <button className="select__trigger" type="button" onClick={() => setOpen(!open)} disabled={disabled} aria-controls={`${instanceId}-options`}>
      <span className="select__text" />
    </button>
    {open ? (
      <div className="select__content" role="listbox" id="fsds-select-listbox">
        {searchable ? (
          <div className="select__search">
            <input type="text" />
          </div>
        ) : null}
        <div className="select__options" id={`${instanceId}-options`}>
          {(options ?? []).map((item, index) => (
            <div className="select__option" role="option" onClick={() => setSelection(multiple ? ((Array.isArray(selection) ? selection : selection == null ? [] : [selection]).includes(item.value) ? (Array.isArray(selection) ? selection : selection == null ? [] : [selection]).filter((v) => v !== item.value) : [...(Array.isArray(selection) ? selection : selection == null ? [] : [selection]), item.value]) : item.value)} aria-selected={(Array.isArray(selection) ? selection.includes(item.value) : item.value === selection)} data-value={item.value} key={index}>
              <span>
                {item.label}
              </span>
            </div>
          ))}
        </div>
        {empty ? (
          <div className="select__emptyState" />
        ) : null}
      </div>
    ) : null}
  </Stack>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/Select/Select.vue
<script setup lang="ts">
// @generated:start imports
import { computed, useId } from "vue";
import { useSelect } from "./useSelect.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type SelectOption = { value: string; label: string; disabled?: boolean };
export type SelectSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  options?: SelectOption[];
  value?: string | string[];
  defaultValue?: string | string[];
  onChange?: (value: string | string[]) => void;
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  multiple?: boolean;
  disabled?: boolean;
  size?: SelectSize;
  filterFn?: ((option: SelectOption, searchTerm: string) => boolean);
  searchable?: boolean;
  empty?: boolean;
  position?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  options: () => ([{"value":"alpha","label":"Alpha"},{"value":"beta","label":"Beta"},{"value":"gamma","label":"Gamma"}]),
  defaultValue: () => ("beta"),
  open: undefined,
  defaultOpen: true,
  multiple: undefined,
  disabled: undefined,
  size: "md",
  searchable: undefined,
  empty: undefined,
});
// @generated:end

// @generated:start hook
const behavior = useSelect({
  value: () => props.value,
  defaultValue: props.defaultValue,
  onChange: props.onChange,
  open: () => props.open,
  defaultOpen: props.defaultOpen,
  onOpenChange: props.onOpenChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "select",
  props.size ? `select--${props.size}` : null,
  props.position ? `select--${props.position}` : null,
  behavior.open.value ? "select--open" : null,
  props.disabled ? "select--disabled" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @generated:start fieldAssociation
const instanceId = useId();
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" role="combobox" aria-haspopup="listbox" aria-controls="fsds-select-listbox" :aria-expanded="behavior.open.value" :aria-disabled="props.disabled" :data-testid="props['data-testid']" data-fsds-component="select">
    <button :class="'select__trigger'" type="button" @click="() => behavior.setOpen(!behavior.open.value)" :disabled="props.disabled" :aria-controls="`${instanceId}-options`">
      <span :class="'select__text'"></span>
    </button>
    <div v-if="behavior.open.value" :class="'select__content'" role="listbox" id="fsds-select-listbox">
      <div v-if="props.searchable" :class="'select__search'">
        <input type="text" />
      </div>
      <div :class="'select__options'" :id="`${instanceId}-options`">
        <div v-for="(item, index) in (props.options ?? [])" :key="index" :class="'select__option'" role="option" @click="() => behavior.setSelection(props.multiple ? ((Array.isArray(behavior.selection.value) ? behavior.selection.value : behavior.selection.value == null ? [] : [behavior.selection.value]).includes(item.value) ? (Array.isArray(behavior.selection.value) ? behavior.selection.value : behavior.selection.value == null ? [] : [behavior.selection.value]).filter((v) => v !== item.value) : [...(Array.isArray(behavior.selection.value) ? behavior.selection.value : behavior.selection.value == null ? [] : [behavior.selection.value]), item.value]) : item.value)" :aria-selected="(Array.isArray(behavior.selection.value) ? behavior.selection.value.includes(item.value) : item.value === behavior.selection.value)" :data-value="item.value">
          <span>
            {{ item.label }}
          </span>
        </div>
      </div>
      <div v-if="props.empty" :class="'select__emptyState'"></div>
    </div>
  </div>
</template>
