// packages/ds-svelte/src/components/Skeleton/Skeleton.svelte
<script lang="ts">
// @generated:start imports

// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type SkeletonVariant = "block" | "text" | "avatar" | "media" | "dataviz" | "actions";
type SkeletonAnimate = "shimmer" | "wipe" | "pulse" | "none";
type SkeletonDensity = "compact" | "regular" | "spacious";
type SkeletonLines = number | { min: number; max: number };
type SkeletonRadius = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  variant?: SkeletonVariant;
  animate?: SkeletonAnimate;
  density?: SkeletonDensity;
  aspectRatio?: string;
  lines?: SkeletonLines;
  radius?: SkeletonRadius;
  decorative?: boolean;
  ariaLabel?: string;
  class?: string;
}

let { variant = "block", animate = "shimmer", density = "regular", aspectRatio, lines, radius, decorative = true, ariaLabel, class: className }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "skeleton",
    variant ? `skeleton--${variant}` : null,
    animate ? `skeleton--${animate}` : null,
    density ? `skeleton--${density}` : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} role={(decorative ? "presentation" : "status")} aria-busy={(decorative ? "false" : "true")} aria-hidden={(decorative ? "true" : "false")} aria-label={ariaLabel} data-fsds-component="skeleton"></div>

// packages/ds-vue/src/components/Skeleton/Skeleton.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type SkeletonVariant = "block" | "text" | "avatar" | "media" | "dataviz" | "actions";
export type SkeletonAnimate = "shimmer" | "wipe" | "pulse" | "none";
export type SkeletonDensity = "compact" | "regular" | "spacious";
export type SkeletonLines = number | { min: number; max: number };
export type SkeletonRadius = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  variant?: SkeletonVariant;
  animate?: SkeletonAnimate;
  density?: SkeletonDensity;
  aspectRatio?: string;
  lines?: SkeletonLines;
  radius?: SkeletonRadius;
  decorative?: boolean;
  ariaLabel?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  variant: "block",
  animate: "shimmer",
  density: "regular",
  decorative: true,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "skeleton",
  props.variant ? `skeleton--${props.variant}` : null,
  props.animate ? `skeleton--${props.animate}` : null,
  props.density ? `skeleton--${props.density}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" :role="(props.decorative ? 'presentation' : 'status')" :aria-busy="(props.decorative ? 'false' : 'true')" :aria-hidden="(props.decorative ? 'true' : 'false')" :aria-label="props.ariaLabel" :data-testid="props['data-testid']" data-fsds-component="skeleton"></div>
</template>
