// packages/ds-angular/src/components/Card/Card.component.ts
// @generated:start imports
import { Component, Input, ChangeDetectionStrategy } from "@angular/core";
import { NgClass } from "@angular/common";
import { StackComponent } from "../../primitives/index.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type CardStatus = "completed" | "in-progress" | "planned" | "deprecated" | "category" | "complexity";
export type CardDensity = "default" | "inset";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-card",
  standalone: true,
  imports: [NgClass, StackComponent],
  host: { "data-fsds-component": "card" },
  template: `<fsds-stack role="group" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CardComponent {
  @Input() interactive?: boolean;
  @Input() status?: CardStatus;
  @Input() density?: CardDensity = "default";

  classes(): string {
    const parts: Array<string | null | undefined> = ["card"];
    if (this.status) parts.push(`card--${this.status}`);
    if ((this.density ?? "default")) parts.push(`card--${(this.density ?? "default")}`);
    if (this.interactive) parts.push("card--interactive");
    return parts.filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-card-header",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="header" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CardHeaderComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["card__header", this.class].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-card-content",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CardContentComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["card__content", this.class].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-card-footer",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="footer" variant="horizontal" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CardFooterComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["card__footer", this.class].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-card-description",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="p" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CardDescriptionComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["card__description", this.class].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-react/src/components/Card/Card.tsx
// @generated:start imports
import { type ReactNode } from "react";
import { Stack } from "../../primitives";
import "./Card.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type CardStatus = "completed" | "in-progress" | "planned" | "deprecated" | "category" | "complexity";

export type CardDensity = "default" | "inset";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface CardProps {
  interactive?: boolean;
  status?: CardStatus;
  density?: CardDensity;
  className?: string;
  "data-testid"?: string;
  children?: ReactNode;
}
// @generated:end

// @generated:start subcomponents
export interface CardHeaderProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function CardHeader({
  children,
  className,
  "data-testid": testId,
}: CardHeaderProps) {
  const classNames = ["card__header", className].filter(Boolean).join(" ");
  return (
    <Stack as="header" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface CardContentProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function CardContent({
  children,
  className,
  "data-testid": testId,
}: CardContentProps) {
  const classNames = ["card__content", className].filter(Boolean).join(" ");
  return (
    <Stack className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface CardFooterProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function CardFooter({
  children,
  className,
  "data-testid": testId,
}: CardFooterProps) {
  const classNames = ["card__footer", className].filter(Boolean).join(" ");
  return (
    <Stack as="footer" variant="horizontal" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface CardDescriptionProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function CardDescription({
  children,
  className,
  "data-testid": testId,
}: CardDescriptionProps) {
  const classNames = ["card__description", className].filter(Boolean).join(" ");
  return (
    <Stack as="p" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}
// @generated:end

// @generated:start component
export function Card({
  status,
  density = "default",
  interactive,
  className,
  "data-testid": testId,
  children,
  ...rest
}: CardProps) {
  const classNames = [
    "card",
    status && `card--${status}`,
    density && `card--${density}`,
    interactive && "card--interactive",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <Stack
      role="group"
      className={classNames}
      data-testid={testId}
      data-fsds-component="card"
      {...rest}
    >
      {children}
    </Stack>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end
