// packages/ds-vue/src/components/Card/Card.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { Stack } from "../../primitives/index.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type CardStatus = "completed" | "in-progress" | "planned" | "deprecated" | "category" | "complexity";
export type CardDensity = "default" | "inset";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  interactive?: boolean;
  status?: CardStatus;
  density?: CardDensity;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  interactive: undefined,
  density: "default",
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "card",
  props.status ? `card--${props.status}` : null,
  props.density ? `card--${props.density}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <Stack role="group" :data-testid="props['data-testid']" :class="classNames">
    <slot />
  </Stack>
</template>

// packages/ds-react/src/components/Card/Card.tsx
// @generated:start imports
import { type ReactNode } from "react";
import { Stack } from "../../primitives";
import "./Card.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type CardStatus = "completed" | "in-progress" | "planned" | "deprecated" | "category" | "complexity";

export type CardDensity = "default" | "inset";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface CardProps {
  interactive?: boolean;
  status?: CardStatus;
  density?: CardDensity;
  className?: string;
  "data-testid"?: string;
  children?: ReactNode;
}
// @generated:end

// @generated:start subcomponents
export interface CardHeaderProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function CardHeader({
  children,
  className,
  "data-testid": testId,
}: CardHeaderProps) {
  const classNames = ["card__header", className].filter(Boolean).join(" ");
  return (
    <Stack as="header" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface CardContentProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function CardContent({
  children,
  className,
  "data-testid": testId,
}: CardContentProps) {
  const classNames = ["card__content", className].filter(Boolean).join(" ");
  return (
    <Stack className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface CardFooterProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function CardFooter({
  children,
  className,
  "data-testid": testId,
}: CardFooterProps) {
  const classNames = ["card__footer", className].filter(Boolean).join(" ");
  return (
    <Stack as="footer" variant="horizontal" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface CardDescriptionProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function CardDescription({
  children,
  className,
  "data-testid": testId,
}: CardDescriptionProps) {
  const classNames = ["card__description", className].filter(Boolean).join(" ");
  return (
    <Stack as="p" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}
// @generated:end

// @generated:start component
export function Card({
  status,
  density = "default",
  className,
  "data-testid": testId,
  children,
  interactive,
  ...rest
}: CardProps) {
  const classNames = [
    "card",
    status && `card--${status}`,
    density && `card--${density}`,
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <Stack
      role="group"
      className={classNames}
      data-testid={testId}
      {...rest}
    >
      {children}
    </Stack>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end
