// packages/ds-svelte/src/components/Tabs/TabsTab.svelte
<script lang="ts">
// @generated:start imports
import { onMount, onDestroy } from "svelte";
import { useTabsContext } from "./useTabs.svelte.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  value: string;
  disabled?: boolean;
  class?: string;
  "data-testid"?: string;
  children?: import('svelte').Snippet;
}

let { value, disabled, class: className, "data-testid": dataTestid, children }: Props = $props();
// @generated:end

// @generated:start classes
const ctx = useTabsContext();

const isActive = $derived(ctx.activeTab === value);

const classes = $derived(
  [
    "tabs__tab",
    isActive && "tabs__tab--active",
    className,
  ]
    .filter(Boolean)
    .join(" "),
);
// @generated:end

// @generated:start trailing
onMount(() => {
  ctx.registerTab(value);
});

onDestroy(() => {
  ctx.unregisterTab(value);
});
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<button
  role="tab"
  type="button"
  class={classes}
  data-value={value}
  data-testid={dataTestid}
  id="{ctx.idBase}-tab-{value}"
  aria-controls="{ctx.idBase}-panel-{value}"
  aria-selected={isActive}
  tabindex={isActive ? 0 : -1}
  {disabled}
  onclick={() => ctx.setActiveTab(value)}
>
  {@render children?.()}
</button>

// packages/ds-vue/src/components/Tabs/TabsTab.vue
<script setup lang="ts">
// @generated:start imports
import { computed, onMounted, onUnmounted } from "vue";
import { useTabsContext } from "./useTabs.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  value: string;
  disabled?: boolean;
  class?: string;
  dataTestid?: string;
}

const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const ctx = useTabsContext();

const isActive = computed(() => ctx.activeTab.value === props.value);

const classNames = computed(() =>
  [
    "tabs__tab",
    isActive.value && "tabs__tab--active",
    props.class,
  ]
    .filter(Boolean)
    .join(" "),
);
// @generated:end

// @generated:start trailing
onMounted(() => {
  ctx.registerTab(props.value);
});

onUnmounted(() => {
  ctx.unregisterTab(props.value);
});
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <button
    role="tab"
    type="button"
    :class="classNames"
    :data-value="props.value"
    :data-testid="props.dataTestid"
    :id="`${ctx.idBase}-tab-${props.value}`"
    :aria-controls="`${ctx.idBase}-panel-${props.value}`"
    :aria-selected="isActive"
    :tabindex="isActive ? 0 : -1"
    :disabled="props.disabled"
    @click="ctx.setActiveTab(props.value)"
  >
    <slot />
  </button>
</template>
