// packages/ds-angular/src/components/Tabs/TabsPanel.component.ts
// @generated:start imports
import { Component, Input, computed, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass, NgIf } from "@angular/common";
import { useTabsContext } from "./useTabs.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-tabs-panel",
  standalone: true,
  imports: [NgClass, NgIf],
  template: `<div
  *ngIf="!ctx.unmountInactive() || isActive()"
  role="tabpanel"
  [ngClass]="classes()"
  [attr.id]="ctx.idBase + '-panel-' + value"
  [attr.aria-labelledby]="ctx.idBase + '-tab-' + value"
  [attr.tabindex]="0"
  [attr.hidden]="!isActive() ? true : null"
><ng-content /></div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TabsPanelComponent {
  @Input({ required: true }) value!: string;
  @Input() class?: string;
  @Input() dataTestid?: string;

  protected ctx = useTabsContext();

  isActive = computed(() => this.ctx.activeTab() === this.value);

  classes = computed(() =>
    ["tabs__panel", this.class].filter(Boolean).join(" "),
  );
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/Tabs/TabsPanel.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useTabsContext } from "./useTabs.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  value: string;
  class?: string;
  dataTestid?: string;
}

const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const ctx = useTabsContext();

const isActive = computed(() => ctx.activeTab.value === props.value);

const classNames = computed(() =>
  ["tabs__panel", props.class].filter(Boolean).join(" "),
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div
    v-if="!ctx.unmountInactive || isActive"
    role="tabpanel"
    :class="classNames"
    :id="`${ctx.idBase}-panel-${props.value}`"
    :aria-labelledby="`${ctx.idBase}-tab-${props.value}`"
    :tabindex="0"
    :data-testid="props.dataTestid"
    :hidden="!isActive ? true : undefined"
  >
    <slot />
  </div>
</template>
