// packages/ds-svelte/src/components/NavList/NavList.svelte
<script lang="ts">
// @generated:start imports

// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type NavListOrientation = "vertical" | "horizontal";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  orientation?: NavListOrientation;
  ariaLabel?: string;
  class?: string;
  children?: import('svelte').Snippet;
}

let { orientation = "vertical", ariaLabel, class: className, children }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "nav-list",
    orientation ? `nav-list--${orientation}` : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<nav class={classes} aria-label={ariaLabel} data-fsds-component="nav-list" data-fsds-box="">
  <ul class={'nav-list__list'}>
    {@render children?.()}
  </ul>
</nav>

// packages/ds-vue/src/components/NavList/NavList.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type NavListOrientation = "vertical" | "horizontal";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  orientation?: NavListOrientation;
  ariaLabel?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  orientation: "vertical",
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "nav-list",
  props.orientation ? `nav-list--${props.orientation}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <nav :class="classNames" :aria-label="props.ariaLabel" :data-testid="props['data-testid']" data-fsds-component="nav-list" data-fsds-box="">
    <ul :class="'nav-list__list'">
      <slot />
    </ul>
  </nav>
</template>
