// packages/ds-angular/src/primitives/hooks/createCompoundContext.ts
import { InjectionToken, inject } from '@angular/core';

/**
 * Angular equivalent of Vue's createCompoundContext / React's createContext.
 *
 * Returns a typed InjectionToken and a `useContext()` helper that throws a
 * descriptive error when used outside the providing component.
 *
 * Usage:
 *   const { token: TabsContextToken, useContext: useTabsContext } =
 *     createCompoundContext<TabsContextValue>("Tabs");
 *
 *   // In <Tabs> providers array:
 *   providers: [{ provide: TabsContextToken, useValue: state }]
 *
 *   // In any descendant <TabsTab> / <TabsPanel>:
 *   const ctx = useTabsContext();  // throws if outside <Tabs>
 */
export function createCompoundContext<T>(displayName: string): {
  token: InjectionToken<T>;
  useContext: () => T;
} {
  const token = new InjectionToken<T>(`${displayName}Context`);

  function useContext(): T {
    const ctx = inject(token, { optional: true });
    if (ctx == null) {
      throw new Error(
        `${displayName} compound component used outside of its provider. ` +
        `Ensure a parent component provides the "${displayName}Context" token.`,
      );
    }
    return ctx;
  }

  return { token, useContext };
}

// packages/ds-react-native/src/primitives/hooks/createCompoundContext.ts
import { type Context, createContext, useContext } from "react";

/**
 * Helper for compound components (Tabs, Accordion, Dropdown, Menu, …):
 * creates a typed React context plus a `useX` consumer that throws when
 * called outside the provider.
 *
 * Ported verbatim from the ds-react seed primitive — React Native is React,
 * and this helper touches no DOM, so the two implementations stay
 * byte-equivalent by construction. ds-react-native must not import it from
 * ds-react (no cross-package dependency); the port is the dependency boundary.
 *
 * Usage:
 *   const [TabsContextProvider, useTabsContext, TabsContext] =
 *     createCompoundContext<TabsContextValue>("Tabs");
 */
export function createCompoundContext<T>(
  name: string,
): [Context<T | null>["Provider"], () => T, Context<T | null>] {
  const ctx = createContext<T | null>(null);
  ctx.displayName = `${name}Context`;
  function useCompoundContext(): T {
    const value = useContext(ctx);
    if (value === null) {
      throw new Error(
        `${name} compound component used outside of <${name}> provider.`,
      );
    }
    return value;
  }
  return [ctx.Provider, useCompoundContext, ctx];
}
