// packages/ds-react/src/components/Walkthrough/Walkthrough.tsx
// @generated:start imports
import { type HTMLAttributes, type ReactNode, useEffect, useId, useState } from "react";
import { Stack } from "../../primitives";
import { useAnchoredPosition } from "../../primitives/surfaces/useAnchoredPosition";
import { useWalkthrough } from "./useWalkthrough";
import "./Walkthrough.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type WalkthroughPlacement = "top" | "bottom" | "left" | "right" | "auto";

export type WalkthroughStepSpec = { anchor: string; title: string; description?: string };
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface WalkthroughProps extends Omit<HTMLAttributes<HTMLDivElement>, "autoStart" | "children" | "className" | "closeOnOutsideClick" | "data-testid" | "defaultIndex" | "index" | "label" | "onComplete" | "onSkip" | "onStepChange" | "placement" | "steps" | "storageKey"> {
  steps?: WalkthroughStepSpec[];
  index?: number;
  defaultIndex?: number;
  onStepChange?: (index: number) => void;
  onComplete?: () => void;
  onSkip?: () => void;
  label?: string;
  storageKey?: string;
  autoStart?: boolean;
  closeOnOutsideClick?: boolean;
  placement?: WalkthroughPlacement;
  className?: string;
  "data-testid"?: string;
  slots?: {
    description?: ReactNode;
    title?: ReactNode;
  };
}
// @generated:end

// @generated:start subcomponents
export interface WalkthroughContentProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function WalkthroughContent({
  children,
  className,
  "data-testid": testId,
}: WalkthroughContentProps) {
  const classNames = ["walkthrough__content", className].filter(Boolean).join(" ");
  return (
    <Stack className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface WalkthroughTitleProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function WalkthroughTitle({
  children,
  className,
  "data-testid": testId,
}: WalkthroughTitleProps) {
  const classNames = ["walkthrough__title", className].filter(Boolean).join(" ");
  return (
    <Stack as="h3" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface WalkthroughDescriptionProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function WalkthroughDescription({
  children,
  className,
  "data-testid": testId,
}: WalkthroughDescriptionProps) {
  const classNames = ["walkthrough__description", className].filter(Boolean).join(" ");
  return (
    <Stack as="p" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}
// @generated:end

// @generated:start component
export function Walkthrough({
  index: controlledIndex,
  defaultIndex = 0,
  onStepChange,
  placement = "auto",
  className,
  "data-testid": testId,
  steps = [{"anchor":"#step-1","title":"Welcome to the tour"},{"anchor":"#step-2","title":"Browse your dashboard"},{"anchor":"#step-3","title":"Configure preferences"}],
  onComplete,
  onSkip,
  label = "Feature tour",
  storageKey,
  autoStart = false,
  closeOnOutsideClick = false,
  slots,
  ...rest
}: WalkthroughProps) {
  const { step, setStep, renderInPortal } = useWalkthrough({
    index: controlledIndex,
    defaultIndex,
    onStepChange,
    closeOnOutsideClick,
  });

  const [anchoredRootEl, setAnchoredRootEl] = useState<HTMLElement | null>(null);
  const [anchorTargetEl, setAnchorTargetEl] = useState<HTMLElement | null>(null);
  useEffect(() => {
    const selector = (steps ?? [])[step]?.anchor;
    setAnchorTargetEl(selector ? document.querySelector<HTMLElement>(selector) : null);
  }, [step, steps]);
  const anchoredPosition = useAnchoredPosition({
    anchor: anchorTargetEl,
    content: anchoredRootEl,
    open: true,
    placement: placement,
    collision: "flip-shift",
  });

  const classNames = [
    "walkthrough",
    placement && `walkthrough--${placement}`,
    className,
  ]
    .filter(Boolean)
    .join(" ");

  const instanceId = useId();

  return (
    renderInPortal(
    <Stack layout="native" className={`${classNames}`} role="status" aria-label={label} data-testid={testId} data-fsds-component="walkthrough" ref={(el) => setAnchoredRootEl(el instanceof HTMLElement ? el : null)} data-placement={anchoredPosition.placement} style={{ position: "fixed", top: `${anchoredPosition.top}px`, left: `${anchoredPosition.left}px`, visibility: anchoredPosition.ready ? "visible" : "hidden" }} {...rest}>
      <div className="walkthrough__content" role="group" aria-labelledby={slots?.title ? `${instanceId}-title` : undefined} aria-describedby={slots?.description ? `${instanceId}-description` : undefined}>
        <h3 className="walkthrough__title" aria-label={label} id={`${instanceId}-title`}>
          {slots?.title}
        </h3>
        <p className="walkthrough__description" id={`${instanceId}-description`}>
          {slots?.description}
        </p>
      </div>
      <div className="walkthrough__controls">
        <button className="walkthrough__skip" type="button" aria-label={"Skip tour"} />
        <button className="walkthrough__prev" type="button" aria-label={"Previous step"} />
        <div className="walkthrough__dots">
          {(steps ?? []).map((item, index) => <button className="walkthrough__dot" type="button" aria-label={item.title} data-step-index={index} key={index} />)}
        </div>
        <span className="walkthrough__counter" />
        <button className="walkthrough__next" type="button" aria-label={"Next step"} />
      </div>
    </Stack>
    )
  );
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/Walkthrough/Walkthrough.vue
<script setup lang="ts">
// @generated:start imports
import { computed, shallowRef, type ComponentPublicInstance, useId, watchEffect } from "vue";
import { useWalkthrough } from "./useWalkthrough.js";
import { useAnchoredPosition } from "../../primitives/surfaces/useAnchoredPosition.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type WalkthroughStepSpec = { anchor: string; title: string; description?: string };
export type WalkthroughPlacement = "top" | "bottom" | "left" | "right" | "auto";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  steps?: WalkthroughStepSpec[];
  index?: number;
  defaultIndex?: number;
  onStepChange?: (index: number) => void;
  onComplete?: () => void;
  onSkip?: () => void;
  label?: string;
  storageKey?: string;
  autoStart?: boolean;
  closeOnOutsideClick?: boolean;
  placement?: WalkthroughPlacement;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  steps: () => ([{"anchor":"#step-1","title":"Welcome to the tour"},{"anchor":"#step-2","title":"Browse your dashboard"},{"anchor":"#step-3","title":"Configure preferences"}]),
  defaultIndex: 0,
  label: "Feature tour",
  autoStart: false,
  closeOnOutsideClick: false,
  placement: "auto",
});
// @generated:end

// @generated:start hook
const behavior = useWalkthrough({
  index: () => props.index,
  defaultIndex: props.defaultIndex,
  onStepChange: props.onStepChange,
  closeOnOutsideClick: props.closeOnOutsideClick,
});
// @generated:end

// @generated:start anchoredPosition
const anchoredRootEl = shallowRef<HTMLElement | null>(null);
function setAnchoredRootEl(el: Element | ComponentPublicInstance | null): void {
  anchoredRootEl.value = el instanceof HTMLElement ? el : null;
}
const anchorTargetEl = shallowRef<HTMLElement | null>(null);
watchEffect(
  () => {
    const selector = (props.steps ?? [])[behavior.step.value]?.anchor;
    anchorTargetEl.value = selector ? document.querySelector<HTMLElement>(selector) : null;
  },
  { flush: "post" },
);
const anchoredPosition = useAnchoredPosition({
  anchor: () => anchorTargetEl.value,
  content: () => anchoredRootEl.value,
  open: () => true,
  placement: () => props.placement,
  collision: () => "flip-shift",
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "walkthrough",
  props.placement ? `walkthrough--${props.placement}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @generated:start fieldAssociation
const instanceId = useId();
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <Teleport to="body">
    <div :class="classNames" role="status" :aria-label="props.label" :data-testid="props['data-testid']" data-fsds-component="walkthrough" data-fsds-box="" :ref="setAnchoredRootEl" :data-placement="anchoredPosition.placement" :style="{ position: 'fixed', top: `${anchoredPosition.top}px`, left: `${anchoredPosition.left}px`, visibility: anchoredPosition.ready ? 'visible' : 'hidden' }">
      <div :class="'walkthrough__content'" role="group" :aria-labelledby="$slots.title ? `${instanceId}-title` : undefined" :aria-describedby="$slots.description ? `${instanceId}-description` : undefined">
        <h3 :class="'walkthrough__title'" :aria-label="props.label" :id="`${instanceId}-title`">
          <slot name="title" />
        </h3>
        <p :class="'walkthrough__description'" :id="`${instanceId}-description`">
          <slot name="description" />
        </p>
      </div>
      <div :class="'walkthrough__controls'">
        <button :class="'walkthrough__skip'" type="button" aria-label="Skip tour"></button>
        <button :class="'walkthrough__prev'" type="button" aria-label="Previous step"></button>
        <div :class="'walkthrough__dots'">
          <button v-for="(item, index) in (props.steps ?? [])" :key="index" :class="'walkthrough__dot'" type="button" :aria-label="item.title" :data-step-index="index"></button>
        </div>
        <span :class="'walkthrough__counter'"></span>
        <button :class="'walkthrough__next'" type="button" aria-label="Next step"></button>
      </div>
    </div>
  </Teleport>
</template>
