// packages/ds-svelte/src/components/Switch/Switch.svelte
<script lang="ts">
// @generated:start imports
import { useSwitch } from "./useSwitch.svelte.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type SwitchSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  checked?: boolean;
  defaultChecked?: boolean;
  onChange?: (checked: boolean) => void;
  size?: SwitchSize;
  disabled?: boolean;
  name?: string;
  value?: string;
  class?: string;
}

let { checked, defaultChecked, onChange, size = "md", disabled, name, value, class: className }: Props = $props();
// @generated:end

// @generated:start hook
const behavior = useSwitch({
  checked: () => checked,
  defaultChecked: () => defaultChecked,
  onChange: () => onChange,
});
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "switch",
    size ? `switch--${size}` : null,
    behavior.checked ? "switch--checked" : null,
    disabled ? "switch--disabled" : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<label class={classes}>
  <input class={'switch__input'} type="checkbox" role="switch" checked={behavior.checked} onchange={(e) => behavior.setChecked((e.currentTarget as HTMLInputElement).checked)} disabled={disabled} name={name} value={value} />
  <span class={'switch__track'} aria-hidden="true">
    <span class={'switch__thumb'}></span>
  </span>
</label>

// packages/ds-vue/src/components/Switch/Switch.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useSwitch } from "./useSwitch.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type SwitchSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  checked?: boolean;
  defaultChecked?: boolean;
  onChange?: (checked: boolean) => void;
  size?: SwitchSize;
  disabled?: boolean;
  name?: string;
  value?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  checked: undefined,
  defaultChecked: undefined,
  size: "md",
  disabled: undefined,
});
// @generated:end

// @generated:start hook
const behavior = useSwitch({
  checked: () => props.checked,
  defaultChecked: props.defaultChecked,
  onChange: props.onChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "switch",
  props.size ? `switch--${props.size}` : null,
  behavior.checked.value ? "switch--checked" : null,
  props.disabled ? "switch--disabled" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <label :class="classNames" :data-testid="props['data-testid']">
    <input :class="'switch__input'" type="checkbox" role="switch" @change="(e) => behavior.setChecked((e.target as HTMLInputElement).checked)" :checked="behavior.checked.value" :disabled="props.disabled" :name="props.name" :value="props.value" />
    <span :class="'switch__track'" aria-hidden="true">
      <span :class="'switch__thumb'"></span>
    </span>
  </label>
</template>
