// packages/ds-react/src/components/Details/Details.tsx
// @generated:start imports
import { canActivateInteraction } from "../../primitives/interaction.js";
import { type DetailsHTMLAttributes, type ReactNode, useId } from "react";
import { Stack } from "../../primitives";
import { Icon } from "../Icon/Icon";
import { useDetails } from "./useDetails";
import "./Details.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type DetailsVariant = "default" | "inline" | "compact";

export type DetailsIcon = "left" | "right" | "none";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface DetailsProps extends Omit<DetailsHTMLAttributes<HTMLDetailsElement>, "children" | "className" | "data-testid" | "defaultOpen" | "disabled" | "icon" | "onOpenChange" | "open" | "summary" | "variant"> {
  summary: string;
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  disabled?: boolean;
  variant?: DetailsVariant;
  icon?: DetailsIcon;
  className?: string;
  "data-testid"?: string;
  children?: ReactNode;
}
// @generated:end

// @generated:start subcomponents
export interface DetailsContentProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function DetailsContent({
  children,
  className,
  "data-testid": testId,
}: DetailsContentProps) {
  const classNames = ["details__content", className].filter(Boolean).join(" ");
  return (
    <Stack className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}
// @generated:end

// @generated:start component
export function Details({
  open: controlledOpen,
  defaultOpen,
  onOpenChange,
  variant = "default",
  icon = "left",
  disabled,
  className,
  "data-testid": testId,
  children,
  summary,
  ...rest
}: DetailsProps) {
  const { open, setOpen } = useDetails({
    open: controlledOpen,
    defaultOpen,
    onOpenChange,
  });

  const classNames = [
    "details",
    variant && `details--${variant}`,
    icon && `details--${icon}`,
    open && "details--open",
    disabled && "details--disabled",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  const instanceId = useId();

  return (
  <Stack layout="native" as="details" className={`${classNames}`} open={open} data-testid={testId} data-fsds-component="details" data-fsds-box="" {...rest}>
    <summary className="details__summary" onClick={(e) => { if (canActivateInteraction(e, true)) setOpen(!open); }} aria-disabled={disabled} aria-controls={open ? `${instanceId}-content` : undefined}>
      <span className="details__summaryContent">
        <Icon className="details__icon" name="chevron-down" size="sm" />
        <span className="details__summaryText">
          {summary}
        </span>
      </span>
    </summary>
    {open ? (
      <div className="details__content" id={`${instanceId}-content`}>
        {children}
      </div>
    ) : null}
  </Stack>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/Details/Details.vue
<script setup lang="ts">
// @generated:start imports
import { computed, useId } from "vue";
import { useDetails } from "./useDetails.js";
import Icon from "../Icon/Icon.vue";
import { canActivateInteraction } from "../../primitives/interaction.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type DetailsVariant = "default" | "inline" | "compact";
export type DetailsIcon = "left" | "right" | "none";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  summary: string;
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  disabled?: boolean;
  variant?: DetailsVariant;
  icon?: DetailsIcon;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  open: undefined,
  defaultOpen: undefined,
  disabled: undefined,
  variant: "default",
  icon: "left",
});
// @generated:end

// @generated:start hook
const behavior = useDetails({
  open: () => props.open,
  defaultOpen: props.defaultOpen,
  onOpenChange: props.onOpenChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "details",
  props.variant ? `details--${props.variant}` : null,
  props.icon ? `details--${props.icon}` : null,
  behavior.open.value ? "details--open" : null,
  props.disabled ? "details--disabled" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @generated:start fieldAssociation
const instanceId = useId();
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <details :class="classNames" :open="behavior.open.value" :data-testid="props['data-testid']" data-fsds-component="details" data-fsds-box="">
    <summary :class="'details__summary'" @click="(e: MouseEvent) => { if (canActivateInteraction(e, true)) behavior.setOpen(!behavior.open.value); }" :aria-disabled="props.disabled" :aria-controls="props.open ? `${instanceId}-content` : undefined">
      <span :class="'details__summaryContent'">
        <Icon :class="'details__icon'" name="chevron-down" size="sm" />
        <span :class="'details__summaryText'">
          {{ props.summary }}
        </span>
      </span>
    </summary>
    <div v-if="behavior.open.value" :class="'details__content'" :id="`${instanceId}-content`">
      <slot />
    </div>
  </details>
</template>
