// packages/ds-svelte/src/components/Details/Details.svelte
<script lang="ts">
// @generated:start imports
import { useDetails } from "./useDetails.svelte.js";
import Icon from "../Icon/Icon.svelte";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type DetailsVariant = "default" | "inline" | "compact";
type DetailsIcon = "left" | "right" | "none";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  summary: string;
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  disabled?: boolean;
  variant?: DetailsVariant;
  icon?: DetailsIcon;
  class?: string;
  children?: import('svelte').Snippet;
}

let { summary, open, defaultOpen, onOpenChange, disabled, variant = "default", icon = "left", class: className, children }: Props = $props();
// @generated:end

// @generated:start hook
const behavior = useDetails({
  open: () => open,
  defaultOpen: () => defaultOpen,
  onOpenChange: () => onOpenChange,
});
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "details",
    variant ? `details--${variant}` : null,
    icon ? `details--${icon}` : null,
    behavior.open ? "details--open" : null,
    disabled ? "details--disabled" : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @generated:start fieldAssociation
const instanceId = $props.id();
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<details class={classes} open={behavior.open} data-fsds-component="details" role="group">
  <summary class={'details__summary'} aria-controls={open ? `${instanceId}-content` : undefined}>
    <span class={'details__summaryContent'}>
      <Icon class={'details__icon'} name="chevron-down" size="sm" />
      <span class={'details__summaryText'}>{summary}</span>
    </span>
  </summary>
  {#if behavior.open}
  <div class={'details__content'} id={`${instanceId}-content`}>
    {@render children?.()}
  </div>
  {/if}
</details>

// packages/ds-vue/src/components/Details/Details.vue
<script setup lang="ts">
// @generated:start imports
import { computed, useId } from "vue";
import { useDetails } from "./useDetails.js";
import Icon from "../Icon/Icon.vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type DetailsVariant = "default" | "inline" | "compact";
export type DetailsIcon = "left" | "right" | "none";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  summary: string;
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  disabled?: boolean;
  variant?: DetailsVariant;
  icon?: DetailsIcon;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  open: undefined,
  defaultOpen: undefined,
  disabled: undefined,
  variant: "default",
  icon: "left",
});
// @generated:end

// @generated:start hook
const behavior = useDetails({
  open: () => props.open,
  defaultOpen: props.defaultOpen,
  onOpenChange: props.onOpenChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "details",
  props.variant ? `details--${props.variant}` : null,
  props.icon ? `details--${props.icon}` : null,
  behavior.open.value ? "details--open" : null,
  props.disabled ? "details--disabled" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @generated:start fieldAssociation
const instanceId = useId();
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <details :class="classNames" :open="behavior.open.value" role="group" :data-testid="props['data-testid']" data-fsds-component="details">
    <summary :class="'details__summary'" :aria-controls="props.open ? `${instanceId}-content` : undefined">
      <span :class="'details__summaryContent'">
        <Icon :class="'details__icon'" name="chevron-down" size="sm" />
        <span :class="'details__summaryText'">
          {{ props.summary }}
        </span>
      </span>
    </summary>
    <div v-if="behavior.open.value" :class="'details__content'" :id="`${instanceId}-content`">
      <slot />
    </div>
  </details>
</template>
