// packages/ds-vue/src/components/Badge/Badge.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type BadgeVariant = "default" | "status" | "counter" | "tag";
export type BadgeIntent = "info" | "success" | "warning" | "danger";
export type BadgeSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  variant?: BadgeVariant;
  intent?: BadgeIntent;
  size?: BadgeSize;
  icon?: unknown;
  showStatusIcon?: boolean;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  showStatusIcon: undefined,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "badge",
  props.variant ? `badge--${props.variant}` : null,
  props.intent ? `badge--${props.intent}` : null,
  props.size ? `badge--${props.size}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <span :class="classNames" :data-testid="props['data-testid']" data-fsds-component="badge" data-fsds-box="">
    <span v-if="props.icon" :class="'badge__icon'" aria-hidden="true">
      {{ props.icon }}
    </span>
    <span :class="'badge__content'">
      <slot />
    </span>
  </span>
</template>

// packages/ds-svelte/src/components/Badge/Badge.svelte
<script lang="ts">
// @generated:start imports

// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type BadgeVariant = "default" | "status" | "counter" | "tag";
type BadgeIntent = "info" | "success" | "warning" | "danger";
type BadgeSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  variant?: BadgeVariant;
  intent?: BadgeIntent;
  size?: BadgeSize;
  icon?: unknown;
  showStatusIcon?: boolean;
  class?: string;
  children?: import('svelte').Snippet;
}

let { variant, intent, size, icon, showStatusIcon, class: className, children }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "badge",
    variant ? `badge--${variant}` : null,
    intent ? `badge--${intent}` : null,
    size ? `badge--${size}` : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<span class={classes} data-fsds-component="badge" data-fsds-box="">
  {#if icon}
  <span class={'badge__icon'} aria-hidden="true">{icon}</span>
  {/if}
  <span class={'badge__content'}>
    {@render children?.()}
  </span>
</span>
