// packages/ds-vue/src/components/Sheet/Sheet.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useSheet } from "./useSheet.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type SheetSide = "top" | "right" | "bottom" | "left";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  side?: SheetSide;
  modal?: boolean;
  class?: string;
  "data-testid"?: string;
  "aria-label"?: string;
  "aria-labelledby"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  open: undefined,
  defaultOpen: undefined,
  side: "right",
  modal: true,
});
// @generated:end

// @generated:start hook
const behavior = useSheet({
  open: () => props.open,
  defaultOpen: props.defaultOpen,
  onOpenChange: props.onOpenChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "sheet",
  props.side ? `sheet--${props.side}` : null,
  behavior.openness.value ? "sheet--open" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" role="dialog" :data-testid="props['data-testid']" @click.self="behavior.setOpenness(false)">
    <div v-if="behavior.openness.value" :class="'sheet__overlay'" aria-hidden="true"></div>
    <div v-if="behavior.openness.value" :class="'sheet__content'" role="dialog" aria-modal="true" aria-labelledby="sheet-title-id" aria-describedby="sheet-description-id" :data-side="props.side">
      <div :class="'sheet__header'">
        <h2 :class="'sheet__title'">
          <slot name="title" />
        </h2>
        <p :class="'sheet__description'">
          <slot name="description" />
        </p>
        <button :class="'sheet__close'" type="button" aria-label="Close sheet"></button>
      </div>
      <div :class="'sheet__body'">
        <slot />
      </div>
      <div :class="'sheet__footer'"></div>
    </div>
  </div>
</template>

// packages/ds-svelte/src/components/Sheet/Sheet.svelte
<script lang="ts">
// @generated:start imports
import { useSheet } from "./useSheet.svelte.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type SheetSide = "top" | "right" | "bottom" | "left";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  side?: SheetSide;
  modal?: boolean;
  class?: string;
  children?: import('svelte').Snippet;
  description?: import('svelte').Snippet;
  title?: import('svelte').Snippet;
}

let { open, defaultOpen, onOpenChange, side = "right", modal = true, class: className, children, description, title }: Props = $props();
// @generated:end

// @generated:start hook
const behavior = useSheet({
  open: () => open,
  defaultOpen: () => defaultOpen,
  onOpenChange: () => onOpenChange,
});
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "sheet",
    side ? `sheet--${side}` : null,
    behavior.openness ? "sheet--open" : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} role="dialog" onclick={(e) => { if (e.target === e.currentTarget) { behavior.setOpenness(false); } }}>
  {#if behavior.openness}
  <div class={'sheet__overlay'} aria-hidden="true"></div>
  {/if}
  {#if behavior.openness}
  <div class={'sheet__content'} role="dialog" aria-modal="true" aria-labelledby="sheet-title-id" aria-describedby="sheet-description-id" data-side={side}>
    <div class={'sheet__header'}>
      <h2 class={'sheet__title'}>
        {@render title?.()}
      </h2>
      <p class={'sheet__description'}>
        {@render description?.()}
      </p>
      <button class={'sheet__close'} type="button" aria-label="Close sheet" onclick={() => behavior.setOpenness(!behavior.openness)}></button>
    </div>
    <div class={'sheet__body'}>
      {@render children?.()}
    </div>
    <div class={'sheet__footer'}></div>
  </div>
  {/if}
</div>
