// packages/ds-react/src/components/Sheet/Sheet.tsx
// @generated:start imports
import { canActivateInteraction } from "../../primitives/interaction.js";
import { type HTMLAttributes, type ReactNode, useId } from "react";
import { Stack } from "../../primitives";
import { useSheet } from "./useSheet";
import "./Sheet.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type SheetSide = "top" | "right" | "bottom" | "left";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface SheetProps extends Omit<HTMLAttributes<HTMLDivElement>, "ariaDescribedby" | "ariaLabel" | "ariaLabelledby" | "children" | "className" | "data-testid" | "defaultOpen" | "modal" | "onOpenChange" | "open" | "side"> {
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  side?: SheetSide;
  modal?: boolean;
  ariaLabel?: string;
  ariaLabelledby?: string;
  ariaDescribedby?: string;
  className?: string;
  "data-testid"?: string;
  children?: ReactNode;
  slots?: {
    description?: ReactNode;
    footer?: ReactNode;
    title?: ReactNode;
  };
}
// @generated:end

// @generated:start subcomponents
export interface SheetContentProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function SheetContent({
  children,
  className,
  "data-testid": testId,
}: SheetContentProps) {
  const classNames = ["sheet__content", className].filter(Boolean).join(" ");
  return (
    <Stack className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface SheetHeaderProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function SheetHeader({
  children,
  className,
  "data-testid": testId,
}: SheetHeaderProps) {
  const classNames = ["sheet__header", className].filter(Boolean).join(" ");
  return (
    <Stack className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface SheetTitleProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function SheetTitle({
  children,
  className,
  "data-testid": testId,
}: SheetTitleProps) {
  const classNames = ["sheet__title", className].filter(Boolean).join(" ");
  return (
    <Stack as="h3" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface SheetDescriptionProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function SheetDescription({
  children,
  className,
  "data-testid": testId,
}: SheetDescriptionProps) {
  const classNames = ["sheet__description", className].filter(Boolean).join(" ");
  return (
    <Stack as="p" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface SheetBodyProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function SheetBody({
  children,
  className,
  "data-testid": testId,
}: SheetBodyProps) {
  const classNames = ["sheet__body", className].filter(Boolean).join(" ");
  return (
    <Stack className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface SheetFooterProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function SheetFooter({
  children,
  className,
  "data-testid": testId,
}: SheetFooterProps) {
  const classNames = ["sheet__footer", className].filter(Boolean).join(" ");
  return (
    <Stack variant="horizontal" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}
// @generated:end

// @generated:start component
export function Sheet({
  open: controlledOpen,
  defaultOpen,
  onOpenChange,
  side = "right",
  className,
  "data-testid": testId,
  children,
  modal = true,
  ariaLabel,
  ariaLabelledby,
  ariaDescribedby,
  slots,
  ...rest
}: SheetProps) {
  const { panelRef, openness, setOpenness, renderInPortal } = useSheet({
    open: controlledOpen,
    defaultOpen,
    onOpenChange,
    modal,
  });

  const classNames = [
    "sheet",
    side && `sheet--${side}`,
    openness && "sheet--open",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  const instanceId = useId();

  return (
    renderInPortal(
    <Stack layout="native" className={`${classNames}`} data-testid={testId} data-fsds-component="sheet" data-fsds-box="" {...rest}>
      {openness ? (
        <div className="sheet__overlay" aria-hidden="true" onClick={(e) => { if (e.target === e.currentTarget) setOpenness(false); }} />
      ) : null}
      {openness ? (
        <div className="sheet__content" role="dialog" aria-modal={modal} aria-label={ariaLabel} data-side={side} ref={panelRef} aria-labelledby={[slots?.title && !ariaLabel ? `${instanceId}-title` : null, ariaLabelledby].filter(Boolean).join(" ") || undefined} aria-describedby={[slots?.description ? `${instanceId}-description` : null, ariaDescribedby].filter(Boolean).join(" ") || undefined}>
          <div className="sheet__header">
            <h2 className="sheet__title" id={`${instanceId}-title`}>
              {slots?.title}
            </h2>
            <p className="sheet__description" id={`${instanceId}-description`}>
              {slots?.description}
            </p>
            <button className="sheet__close" type="button" aria-label="Close sheet" onClick={(e) => { if (canActivateInteraction(e, false)) setOpenness(false); }} />
          </div>
          <div className="sheet__body">
            {children}
          </div>
          <div className="sheet__footer">
            {slots?.footer}
          </div>
        </div>
      ) : null}
    </Stack>
    )
  );
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-svelte/src/components/Sheet/Sheet.svelte
<script lang="ts">
// @generated:start imports
import { canActivateInteraction } from "../../primitives/interaction.js";
import { useSheet } from "./useSheet.svelte.js";
import { portal } from "../../primitives/index.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type SheetSide = "top" | "right" | "bottom" | "left";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  side?: SheetSide;
  modal?: boolean;
  ariaLabel?: string;
  ariaLabelledby?: string;
  ariaDescribedby?: string;
  class?: string;
  children?: import('svelte').Snippet;
  description?: import('svelte').Snippet;
  footer?: import('svelte').Snippet;
  title?: import('svelte').Snippet;
}

let { open, defaultOpen, onOpenChange, side = "right", modal = true, ariaLabel, ariaLabelledby, ariaDescribedby, class: className, children, description, footer, title }: Props = $props();
// @generated:end

// @generated:start hook
const behavior = useSheet({
  open: () => open,
  defaultOpen: () => defaultOpen,
  onOpenChange: () => onOpenChange,
  modal: () => modal,
});
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "sheet",
    side ? `sheet--${side}` : null,
    behavior.openness ? "sheet--open" : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @generated:start fieldAssociation
const instanceId = $props.id();
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} data-fsds-component="sheet" data-fsds-box="" use:portal={{ enabled: true }}>
  {#if behavior.openness}
  <div class={'sheet__overlay'} aria-hidden="true" onclick={(e) => { if (e.target === e.currentTarget) { behavior.setOpenness(false); } }}></div>
  {/if}
  {#if behavior.openness}
  <div class={'sheet__content'} bind:this={behavior.panelRef.el} role="dialog" aria-modal={modal} aria-label={ariaLabel} data-side={side} aria-labelledby={[title && !ariaLabel ? `${instanceId}-title` : null, ariaLabelledby].filter(Boolean).join(' ') || undefined} aria-describedby={[description ? `${instanceId}-description` : null, ariaDescribedby].filter(Boolean).join(' ') || undefined}>
    <div class={'sheet__header'}>
      <h2 class={'sheet__title'} id={`${instanceId}-title`}>
        {@render title?.()}
      </h2>
      <p class={'sheet__description'} id={`${instanceId}-description`}>
        {@render description?.()}
      </p>
      <button class={'sheet__close'} type="button" aria-label="Close sheet" onclick={(e) => { if (canActivateInteraction(e, false)) behavior.setOpenness(false); }}></button>
    </div>
    <div class={'sheet__body'}>
      {@render children?.()}
    </div>
    <div class={'sheet__footer'}>
      {@render footer?.()}
    </div>
  </div>
  {/if}
</div>
