// examples/settings/react/src/App.tsx
import { useState } from "react";
import {
  Stack,
  Card,
  CardHeader,
  CardContent,
  CardFooter,
  Field,
  Input,
  Switch,
  Button,
  Dialog,
  DialogHeader,
  DialogTitle,
  DialogBody,
  DialogFooter,
  Tooltip,
} from "@full-stack-ds/react";

export function App() {
  const [displayName, setDisplayName] = useState("Ada Lovelace");
  const [email, setEmail] = useState("ada@example.com");
  const [darkMode, setDarkMode] = useState(false);
  const [emailNotifications, setEmailNotifications] = useState(true);
  const [confirmOpen, setConfirmOpen] = useState(false);
  const [confirmation, setConfirmation] = useState("");

  const deleteEnabled = confirmation === "DELETE";

  return (
    <Stack variant="vertical" as="main">
      <Card>
        <CardHeader>Profile</CardHeader>
        <CardContent>
          <Stack variant="vertical">
            <Field name="displayName" label="Display name" required>
              <Input
                value={displayName}
                onChange={setDisplayName}
                required
              />
            </Field>
            <Field name="email" label="Email" required>
              <Input
                type="email"
                value={email}
                onChange={setEmail}
                required
              />
            </Field>
          </Stack>
        </CardContent>
        <CardFooter>
          <Button
            variant="primary"
            onClick={() =>
              console.log("save profile", { displayName, email })
            }
          >
            Save profile
          </Button>
        </CardFooter>
      </Card>

      <Card>
        <CardHeader>Preferences</CardHeader>
        <CardContent>
          <Stack variant="vertical">
            <Stack variant="horizontal">
              <span>Dark mode</span>
              <Switch checked={darkMode} onChange={setDarkMode} />
            </Stack>
            <Stack variant="horizontal">
              <Tooltip>
                <Tooltip.Trigger>Email notifications</Tooltip.Trigger>
                <Tooltip.Content>
                  Product announcements and security alerts only.
                </Tooltip.Content>
              </Tooltip>
              <Switch
                checked={emailNotifications}
                onChange={setEmailNotifications}
              />
            </Stack>
          </Stack>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>Danger zone</CardHeader>
        <CardContent>
          Permanently delete your account. This cannot be undone.
        </CardContent>
        <CardFooter>
          <Button
            variant="destructive"
            onClick={() => setConfirmOpen(true)}
          >
            Delete account
          </Button>
        </CardFooter>
      </Card>

      <Dialog
        open={confirmOpen}
        onOpenChange={setConfirmOpen}
        modal
        dismissible
      >
        <DialogHeader>
          <DialogTitle>Delete account?</DialogTitle>
        </DialogHeader>
        <DialogBody>
          <Stack variant="vertical">
            <p>
              This will permanently remove your account. Type DELETE to
              confirm.
            </p>
            <Input
              name="confirmation"
              value={confirmation}
              onChange={setConfirmation}
            />
          </Stack>
        </DialogBody>
        <DialogFooter>
          <Button
            variant="secondary"
            onClick={() => {
              setConfirmation("");
              setConfirmOpen(false);
            }}
          >
            Cancel
          </Button>
          <Button
            variant="destructive"
            disabled={!deleteEnabled}
            onClick={() => {
              console.log("delete account");
              setConfirmation("");
              setConfirmOpen(false);
            }}
          >
            Delete
          </Button>
        </DialogFooter>
      </Dialog>
    </Stack>
  );
}

// examples/settings/vue/src/App.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import {
  Stack,
  Card,
  CardHeader,
  CardContent,
  CardFooter,
  Field,
  Input,
  Switch,
  Button,
  Dialog,
  DialogHeader,
  DialogTitle,
  DialogBody,
  DialogFooter,
  Tooltip,
  TooltipTrigger,
  TooltipContent,
} from "@full-stack-ds/vue";

const displayName = ref("Ada Lovelace");
const email = ref("ada@example.com");
const darkMode = ref(false);
const emailNotifications = ref(true);
const confirmOpen = ref(false);
const confirmation = ref("");

const deleteEnabled = computed(() => confirmation.value === "DELETE");

function saveProfile() {
  console.log("save profile", {
    displayName: displayName.value,
    email: email.value,
  });
}

function cancelDelete() {
  confirmation.value = "";
  confirmOpen.value = false;
}

function deleteAccount() {
  console.log("delete account");
  confirmation.value = "";
  confirmOpen.value = false;
}
</script>

<template>
  <Stack variant="vertical" as="main">
    <Card>
      <CardHeader>Profile</CardHeader>
      <CardContent>
        <Stack variant="vertical">
          <Field name="displayName" label="Display name" required>
            <Input
              :value="displayName"
              :onChange="(value) => (displayName = value)"
              required
            />
          </Field>
          <Field name="email" label="Email" required>
            <Input
              type="email"
              :value="email"
              :onChange="(value) => (email = value)"
              required
            />
          </Field>
        </Stack>
      </CardContent>
      <CardFooter>
        <Button variant="primary" :onClick="saveProfile">
          Save profile
        </Button>
      </CardFooter>
    </Card>

    <Card>
      <CardHeader>Preferences</CardHeader>
      <CardContent>
        <Stack variant="vertical">
          <Stack variant="horizontal">
            <span>Dark mode</span>
            <Switch
              :checked="darkMode"
              :onChange="(checked) => (darkMode = checked)"
            />
          </Stack>
          <Stack variant="horizontal">
            <Tooltip>
              <TooltipTrigger>Email notifications</TooltipTrigger>
              <TooltipContent>
                Product announcements and security alerts only.
              </TooltipContent>
            </Tooltip>
            <Switch
              :checked="emailNotifications"
              :onChange="(checked) => (emailNotifications = checked)"
            />
          </Stack>
        </Stack>
      </CardContent>
    </Card>

    <Card>
      <CardHeader>Danger zone</CardHeader>
      <CardContent>
        Permanently delete your account. This cannot be undone.
      </CardContent>
      <CardFooter>
        <Button variant="destructive" :onClick="() => (confirmOpen = true)">
          Delete account
        </Button>
      </CardFooter>
    </Card>

    <Dialog
      :open="confirmOpen"
      :onOpenChange="(open) => (confirmOpen = open)"
      modal
      dismissible
    >
      <DialogHeader>
        <DialogTitle>Delete account?</DialogTitle>
      </DialogHeader>
      <DialogBody>
        <Stack variant="vertical">
          <p>
            This will permanently remove your account. Type DELETE to confirm.
          </p>
          <Input
            name="confirmation"
            :value="confirmation"
            :onChange="(value) => (confirmation = value)"
          />
        </Stack>
      </DialogBody>
      <DialogFooter>
        <Button variant="secondary" :onClick="cancelDelete">
          Cancel
        </Button>
        <Button
          variant="destructive"
          :disabled="!deleteEnabled"
          :onClick="deleteAccount"
        >
          Delete
        </Button>
      </DialogFooter>
    </Dialog>
  </Stack>
</template>
