// packages/ds-svelte/src/components/AnimatedSection/AnimatedSection.svelte
<script lang="ts">
// @generated:start imports

// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type AnimatedSectionAs = "section" | "div" | "article" | "main" | "aside" | "header" | "footer";
type AnimatedSectionVariant = "fade-up" | "fade-in" | "slide-in" | "stagger-children";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  as?: AnimatedSectionAs;
  variant?: AnimatedSectionVariant;
  duration?: number;
  stagger?: number;
  delay?: number;
  triggerOnScroll?: boolean;
  scrollStart?: string;
  class?: string;
  children?: import('svelte').Snippet;
}

let { as, variant, duration, stagger, delay, triggerOnScroll, scrollStart, class: className, children }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "animated-section",
    as ? `animated-section--${as}` : null,
    variant ? `animated-section--${variant}` : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<section class={classes}>
  {@render children?.()}
</section>

// packages/ds-angular/src/components/AnimatedSection/AnimatedSection.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass } from "@angular/common";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type AnimatedSectionAs = "section" | "div" | "article" | "main" | "aside" | "header" | "footer";
export type AnimatedSectionVariant = "fade-up" | "fade-in" | "slide-in" | "stagger-children";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-animated-section",
  standalone: true,
  imports: [NgClass],
  template: `<section [ngClass]="classes()">
  <ng-content />
</section>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AnimatedSectionComponent {
  @Input() as?: AnimatedSectionAs;
  @Input() variant?: AnimatedSectionVariant;
  @Input() duration?: number;
  @Input() stagger?: number;
  @Input() delay?: number;
  @Input() triggerOnScroll?: boolean;
  @Input() scrollStart?: string;
  @Input() class?: string;

  classes(): string {
    return [
      "animated-section",
      this.as ? `animated-section--${this.as}` : null,
      this.variant ? `animated-section--${this.variant}` : null,
      this.class,
    ].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end
