// packages/ds-vue/src/components/Avatar/Avatar.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import Image from "../Image/Image.vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  src?: string;
  name: string;
  initials?: string;
  priority?: boolean;
  size?: string;
  class?: string;
  dataTestid?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  priority: undefined,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "avatar",
  props.size ? `avatar--${props.size}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" :aria-label="props.name" role="img" :data-testid="props.dataTestid" data-fsds-component="avatar" data-fsds-box="">
    <Image v-if="props.src" :class="'avatar__image'" :src="props.src" alt="" />
    <span v-if="props.initials" :class="'avatar__initials'">
      {{ props.initials }}
    </span>
  </div>
</template>

// packages/ds-react/src/components/Avatar/Avatar.tsx
// @generated:start imports
import { type HTMLAttributes, type ReactNode } from "react";
import { Stack } from "../../primitives";
import { Image } from "../Image/Image";
import "./Avatar.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface AvatarProps extends Omit<HTMLAttributes<HTMLDivElement>, "children" | "className" | "data-testid" | "initials" | "name" | "priority" | "size" | "src"> {
  src?: string;
  name: string;
  initials?: string;
  priority?: boolean;
  size?: string;
  className?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start subcomponents

// @generated:end

// @generated:start component
export function Avatar({
  size,
  className,
  "data-testid": testId,
  src,
  name,
  initials,
  priority,
  ...rest
}: AvatarProps) {
  const classNames = [
    "avatar",
    size && `avatar--${size}`,
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <Stack layout="native" className={`${classNames}`} aria-label={name} role="img" data-testid={testId} data-fsds-component="avatar" data-fsds-box="" {...rest}>
    {src ? (
      <Image className="avatar__image" src={src} alt={""} />
    ) : null}
    {initials ? (
      <span className="avatar__initials">
        {initials}
      </span>
    ) : null}
  </Stack>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end
