// packages/ds-vue/src/components/Breadcrumbs/Breadcrumbs.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  ariaLabel?: string;
  separator?: string;
  class?: string;
  dataTestid?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  ariaLabel: "Breadcrumb",
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "breadcrumbs",
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <nav :class="classNames" :aria-label="props.ariaLabel" :data-testid="props.dataTestid" data-fsds-component="breadcrumbs" data-fsds-box="">
    <ol :class="'breadcrumbs__list'">
      <slot />
    </ol>
  </nav>
</template>

// packages/ds-angular/src/components/Breadcrumbs/Breadcrumbs.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass } from "@angular/common";
import { StackComponent } from "../../primitives/index.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-breadcrumbs",
  standalone: true,
  imports: [NgClass],
  host: { "data-fsds-component": "breadcrumbs" },
  template: `<nav [ngClass]="classes()" [attr.aria-label]="(ariaLabel ?? 'Breadcrumb')">
  <ol [ngClass]="'breadcrumbs__list'">
    <ng-content />
  </ol>
</nav>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BreadcrumbsComponent {
  @Input() ariaLabel?: string = "Breadcrumb";
  @Input() separator?: string;
  @Input() class?: string;

  classes(): string {
    return [
      "breadcrumbs",
      this.class,
    ].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-breadcrumbs-list",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="ul" variant="horizontal" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BreadcrumbsListComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["breadcrumbs__list", this.class].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end
