// packages/ds-codegen/src/frameworks/angular/hook-source.ts
/**
 * Angular behavior hook emitter — the framework-equivalent of
 * `frameworks/vue/hook-source.ts`. Produces a `useX.ts` file that
 * composes Angular-side primitives shipped from `@full-stack-ds/angular`.
 *
 * Dispatches on the same `ir.behavior.normalized*` fields as React and Vue,
 * proving the IR is framework-neutral. Output shape uses Angular 17+ signals:
 * `Signal<T>` for reactive state, plain ref-like objects for DOM handles.
 *
 * Angular's lifecycle is handled via `DestroyRef`, which the consuming
 * component passes in (injected with `inject(DestroyRef)` in the constructor
 * or field initializer). The generated function always accepts a `destroyRef`
 * on its options so primitives can self-clean.
 */
import type { ComponentIR, NormalizedChannelIR } from "../../ir.js";
import { renderSections, type Section } from "../../preserve.js";

interface PrimitiveBindings {
  useControllableState: NormalizedChannelIR[];
  useFocusTrap: boolean;
  useScrollLock: boolean;
  usePortal: boolean;
  useAnchorToggle: boolean;
  /** Standalone Escape dismissal for trap-focus components (Modal). */
  useDismissal: boolean;
  /** Prop name that gates Escape dismissal (e.g. closeOnEscape). */
  escapeEnabledByProp: string | undefined;
}

// ---------------------------------------------------------------------------
// Binding resolution (identical logic to Vue hook-source.ts)
// ---------------------------------------------------------------------------

function resolveBindings(ir: ComponentIR): PrimitiveBindings | null {
  const channels = ir.behavior.normalizedChannels;
  const focus = ir.behavior.focus;
  const portal = ir.behavior.portal;
  const triggers = ir.behavior.normalizedDismissalTriggers;

  const hasFocusTrap = focus?.strategy === "trap";
  const hasScrollLock = focus?.scrollLock === true;
  const hasPortal = portal?.enabled === true;
  const escapeTrigger = triggers.find((t) => t.event === "escape");
  const hasEscape = escapeTrigger !== undefined;
  const hasOutsideClick = triggers.some(
    (t) => t.event === "outsideClick" || t.event === "overlayClick",
  );
  // AnchorToggle needs a boolean "open" state. Components without a boolean
  // channel (e.g. Walkthrough's `step: number`) get standalone Dismissal
  // instead — avoids handing AnchorToggle a number-typed value where it
  // expects a boolean.
  const hasBooleanOpenChannel = channels.some(
    (c) => c.valueType === "boolean" || c.name === "open",
  );
  const useAnchor =
    !hasFocusTrap && (hasEscape || hasOutsideClick) && hasBooleanOpenChannel;
  // Standalone dismissal for trap-focus components: outside-click is handled
  // template-side (overlay onClick), so only Escape needs a document listener.
  const useDismissal = !useAnchor && hasEscape;

  if (
    channels.length === 0 &&
    !hasFocusTrap &&
    !hasScrollLock &&
    !hasPortal &&
    !useAnchor &&
    !useDismissal
  ) {
    return null;
  }

  return {
    useControllableState: channels,
    useFocusTrap: hasFocusTrap,
    useScrollLock: hasScrollLock,
    usePortal: hasPortal,
    useAnchorToggle: useAnchor,
    useDismissal,
    escapeEnabledByProp: escapeTrigger?.enabledByProp,
  };
}

// ---------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------

function generateImports(bindings: PrimitiveBindings): string {
  const coreNamed = new Set<string>();
  coreNamed.add("DestroyRef");

  if (bindings.useControllableState.length > 0) {
    coreNamed.add("type Signal");
  }
  if (bindings.useFocusTrap || bindings.useScrollLock || bindings.useAnchorToggle) {
    coreNamed.add("type Signal");
  }

  const primitives: string[] = [];
  if (bindings.useControllableState.length > 0) {
    primitives.push("createControllableState");
  }
  if (bindings.useFocusTrap) primitives.push("createFocusTrap");
  if (bindings.useScrollLock) primitives.push("createScrollLock");
  if (bindings.usePortal) primitives.push("createPortal");
  if (bindings.useAnchorToggle) primitives.push("createAnchorToggle");
  if (bindings.useDismissal) primitives.push("createDismissal");

  const lines: string[] = [];
  lines.push(
    `import { ${[...coreNamed].sort().join(", ")} } from "@angular/core";`,
  );
  if (primitives.length > 0) {
    lines.push(
      `import { ${primitives.sort().join(", ")} } from "../../primitives/index.js";`,
    );
  }
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Inline types
// ---------------------------------------------------------------------------

function generateInlineTypes(
  ir: ComponentIR,
  bindings: PrimitiveBindings,
): string {
  const referenced = new Set<string>();
  for (const ch of bindings.useControllableState) {
    if (ch.valueType && ir.definedTypes[ch.valueType]) {
      referenced.add(ch.valueType);
    }
  }
  if (referenced.size === 0) return "";
  const lines: string[] = [];
  for (const name of [...referenced].sort()) {
    const def = ir.definedTypes[name];
    if (def.kind === "union" && def.values) {
      lines.push(
        `export type ${name} = ${def.values.map((v) => `"${v}"`).join(" | ")};`,
      );
    } else if (def.kind === "alias" && def.alias) {
      lines.push(`export type ${name} = ${def.alias};`);
    }
  }
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Options / Result interfaces
// ---------------------------------------------------------------------------

function generateOptionsInterface(
  ir: ComponentIR,
  bindings: PrimitiveBindings,
): string {
  const lines: string[] = [`export interface Use${ir.name}Options {`];

  for (const ch of bindings.useControllableState) {
    const t = ch.valueType ?? "unknown";
    // Angular: controlled values are getter-shaped so signal/computed
    // reactivity flows through @Input updates. Consumer pattern:
    // useX({ checked: () => this.checked, ... }).
    lines.push(`  ${ch.valueProp}?: () => ${t} | undefined;`);
    if (ch.defaultValueProp) lines.push(`  ${ch.defaultValueProp}?: ${t};`);
    lines.push(`  ${ch.changeHandlerProp}?: (value: ${t}) => void;`);
  }

  for (const t of ir.behavior.normalizedDismissalTriggers) {
    if (!t.enabledByProp) continue;
    lines.push(`  ${t.enabledByProp}?: boolean;`);
  }

  if (bindings.usePortal) {
    const targetProp = ir.behavior.portal?.targetProp;
    if (targetProp) lines.push(`  ${targetProp}?: Element | string;`);
  }

  // DestroyRef is always required — the consuming component injects it
  lines.push(`  destroyRef: DestroyRef;`);

  lines.push(`}`);
  return lines.join("\n");
}

function generateResultInterface(
  ir: ComponentIR,
  bindings: PrimitiveBindings,
): string {
  const lines: string[] = [`export interface Use${ir.name}Result {`];

  for (const ch of bindings.useControllableState) {
    const t = ch.valueType ?? "unknown";
    const setter = `set${capitalize(ch.name)}`;
    lines.push(`  ${ch.name}: Signal<${t}>;`);
    lines.push(`  ${setter}: (next: ${t}) => void;`);
  }

  if (
    bindings.useFocusTrap ||
    bindings.usePortal ||
    bindings.useAnchorToggle ||
    bindings.useDismissal
  ) {
    lines.push(`  panelRef: { nativeElement: HTMLElement | null };`);
  }
  if (bindings.useAnchorToggle) {
    lines.push(`  anchorRef: { nativeElement: HTMLElement | null };`);
  }
  if (bindings.usePortal) {
    lines.push(`  portalTarget: Signal<Element | null>;`);
  }

  lines.push(`}`);
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Function body
// ---------------------------------------------------------------------------

function generateBody(ir: ComponentIR, bindings: PrimitiveBindings): string {
  const lines: string[] = [];
  // Options default: cast to any so the destroyRef is "required" only at runtime
  lines.push(
    `export function use${ir.name}(options: Use${ir.name}Options): Use${ir.name}Result {`,
  );

  // `openChannel` must be the boolean/"open" controllable-state binding
  // when AnchorToggle is present — components like Select declare a
  // selection channel first, and wiring AnchorToggle to that mis-types it.
  const openChannel =
    bindings.useControllableState.find(
      (c) => c.valueType === "boolean" || c.name === "open",
    ) ?? bindings.useControllableState[0];
  const anchorOwnsChannel =
    bindings.useAnchorToggle &&
    !!openChannel &&
    openChannel.valueType === "boolean";

  for (const ch of bindings.useControllableState) {
    if (anchorOwnsChannel && ch === openChannel) continue;
    const setter = `set${capitalize(ch.name)}`;
    const t = ch.valueType ?? "unknown";
    const def = defaultExprFor(ch.defaultValueProp, t);
    const defaultExpr = ch.defaultValueProp
      ? `options.${ch.defaultValueProp} ?? ${def}`
      : def;
    lines.push(
      `  const { value: ${ch.name}, set: ${setter} } = createControllableState<${t}>({`,
    );
    // options.<valueProp> is itself a getter; pass it directly.
    lines.push(`    controlled: options.${ch.valueProp},`);
    lines.push(`    defaultValue: ${defaultExpr},`);
    lines.push(`    onChange: options.${ch.changeHandlerProp},`);
    lines.push(`  });`);
    lines.push(``);
  }

  if (bindings.useFocusTrap || bindings.usePortal || bindings.useDismissal) {
    lines.push(`  const panelRef: { nativeElement: HTMLElement | null } = { nativeElement: null };`);
  }

  if (bindings.useAnchorToggle && openChannel) {
    // Only emit defaultOpen when the contract declares one for the open
    // channel — components like Toast omit it (external state controller).
    const defaultOpenLine = openChannel.defaultValueProp
      ? `    defaultOpen: options.${openChannel.defaultValueProp} ?? false,`
      : `    defaultOpen: false,`;
    lines.push(
      `  const anchorToggle = createAnchorToggle({`,
      `    open: options.${openChannel.valueProp},`,
      defaultOpenLine,
      `    onOpenChange: options.${openChannel.changeHandlerProp},`,
      `    destroyRef: options.destroyRef,`,
      `  });`,
      ``,
    );
  }

  if (bindings.useFocusTrap) {
    const channel = bindings.useControllableState.find(
      (c) => c.valueType === "boolean" || c.name === "open",
    );
    const activeRef = channel ? channel.name : `{ value: true } as unknown as Signal<boolean>`;
    lines.push(`  createFocusTrap(panelRef, { active: ${activeRef}, destroyRef: options.destroyRef });`);
    lines.push(``);
  }

  if (bindings.useScrollLock) {
    const channel = bindings.useControllableState.find(
      (c) => c.valueType === "boolean" || c.name === "open",
    );
    const activeSignal = channel?.name ?? "{ value: true } as unknown as Signal<boolean>";
    lines.push(`  createScrollLock(${activeSignal}, options.destroyRef);`);
    lines.push(``);
  }

  if (bindings.usePortal) {
    const targetProp = ir.behavior.portal?.targetProp;
    const target = targetProp ? `() => options.${targetProp}` : "() => undefined";
    lines.push(`  const { target: portalTarget } = createPortal({`);
    lines.push(`    enabled: true,`);
    lines.push(`    target: ${target},`);
    lines.push(`  });`);
    lines.push(``);
  }

  if (bindings.useDismissal) {
    const channel = bindings.useControllableState.find(
      (c) => c.valueType === "boolean" || c.name === "open",
    );
    const openGetter = channel ? `() => ${channel.name}()` : `() => true`;
    const setterCall = channel
      ? `set${capitalize(channel.name)}(false)`
      : `void 0`;
    const closeOnEscapeGetter = bindings.escapeEnabledByProp
      ? `() => options.${bindings.escapeEnabledByProp}`
      : `() => true`;
    lines.push(`  createDismissal({`);
    lines.push(`    open: ${openGetter},`);
    lines.push(`    closeOnEscape: ${closeOnEscapeGetter},`);
    lines.push(`    onDismiss: () => { ${setterCall}; },`);
    lines.push(`    destroyRef: options.destroyRef,`);
    lines.push(`  });`);
    lines.push(``);
  }

  // Build return object
  lines.push(`  return {`);
  for (const ch of bindings.useControllableState) {
    const setter = `set${capitalize(ch.name)}`;
    if (anchorOwnsChannel && ch === openChannel) {
      lines.push(`    ${ch.name}: anchorToggle.open,`);
      lines.push(`    ${setter}: anchorToggle.setOpen,`);
    } else {
      lines.push(`    ${ch.name},`);
      lines.push(`    ${setter},`);
    }
  }
  if (bindings.useAnchorToggle) {
    lines.push(`    anchorRef: anchorToggle.anchorRef,`);
    lines.push(`    panelRef: anchorToggle.panelRef,`);
  } else if (
    bindings.useFocusTrap ||
    bindings.usePortal ||
    bindings.useDismissal
  ) {
    lines.push(`    panelRef,`);
  }
  if (bindings.usePortal) {
    lines.push(`    portalTarget,`);
  }
  lines.push(`  };`);
  lines.push(`}`);
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function defaultExprFor(
  _defaultProp: string | undefined,
  valueType: string,
): string {
  if (valueType === "boolean") return "false";
  if (valueType === "number") return "0";
  if (valueType === "string") return '""';
  return "undefined as never";
}

function capitalize(s: string): string {
  return s[0].toUpperCase() + s.slice(1);
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

export function generateAngularHookSource(ir: ComponentIR): string | null {
  const bindings = resolveBindings(ir);
  if (!bindings) return null;

  const importsBody = generateImports(bindings);
  const inlineTypesBody = generateInlineTypes(ir, bindings);
  const optionsBody = generateOptionsInterface(ir, bindings);
  const resultBody = generateResultInterface(ir, bindings);
  const hookBody = generateBody(ir, bindings);

  const typesBody = [inlineTypesBody, optionsBody, resultBody]
    .filter((s) => s.length > 0)
    .join("\n\n");

  const blank = (): Section => ({ kind: "between", body: "" });
  const sections: Section[] = [
    { kind: "generated", id: "imports", body: importsBody },
    blank(),
    { kind: "custom", id: "imports", body: "" },
    blank(),
    { kind: "generated", id: "types", body: typesBody },
    blank(),
    { kind: "custom", id: "types", body: "" },
    blank(),
    { kind: "generated", id: "hook", body: hookBody },
    blank(),
    { kind: "custom", id: "trailing", body: "" },
    blank(),
  ];

  return renderSections(sections, "line");
}

// packages/ds-codegen/src/frameworks/react/hook-source.ts
/**
 * React behavior hook emitter.
 *
 * Reads the normalized behavior fields on `ComponentIR` and produces a
 * `use<Name>.ts` file that composes the primitive hooks shipped from
 * `@full-stack-ds/react/primitives/hooks`. The generator is purely
 * declarative — it dispatches on contract data:
 *
 *   - `behavior.normalizedChannels`            → useControllableState per channel
 *   - `behavior.focus?.strategy === "trap"`    → useFocusTrap
 *   - `behavior.focus?.scrollLock === true`    → useScrollLock
 *   - `behavior.portal?.enabled === true`      → usePortal
 *   - `behavior.normalizedDismissalTriggers`   → useAnchorToggle (when no
 *                                                focus trap; otherwise the
 *                                                trap + Escape listener pair
 *                                                handles dismissal)
 *
 * Returns `null` when no behavior field is populated; the CLI uses that
 * signal to skip emission.
 */
import type {
  ComponentIR,
  NormalizedChannelIR,
  ResolvedPropIR,
} from "../../ir.js";
import { renderSections, type Section } from "../../preserve.js";

interface PrimitiveBindings {
  useControllableState: NormalizedChannelIR[];
  useFocusTrap: boolean;
  useScrollLock: boolean;
  usePortal: boolean;
  useAnchorToggle: boolean;
  useDismissal: boolean;
  hasEscapeTrigger: boolean;
  hasOutsideClickTrigger: boolean;
}

/**
 * Determine which primitive hooks the contract's behavior fields map onto.
 * Returns `null` when no primitive is required (the contract has no
 * behavior worth lifting and the generator should skip emission).
 */
function resolveBindings(ir: ComponentIR): PrimitiveBindings | null {
  const channels = ir.behavior.normalizedChannels;
  const focus = ir.behavior.focus;
  const portal = ir.behavior.portal;
  const triggers = ir.behavior.normalizedDismissalTriggers;

  const hasFocusTrap = focus?.strategy === "trap";
  const hasScrollLock = focus?.scrollLock === true;
  const hasPortal = portal?.enabled === true;
  const hasEscapeTrigger = triggers.some((t) => t.event === "escape");
  const hasOutsideClickTrigger = triggers.some(
    (t) => t.event === "outsideClick" || t.event === "overlayClick",
  );
  // Prefer useAnchorToggle when there's no focus trap (overlay-style components).
  // Focus-trap components (Modal) use useDismissal directly for escape handling.
  // useAnchorToggle requires a boolean "open" channel — components with only
  // non-boolean channels (e.g. Walkthrough's step index) fall through to
  // standalone useDismissal instead.
  const hasBooleanOpenChannel = channels.some(
    (c) => c.valueType === "boolean" || c.name === "open",
  );
  const useAnchor =
    !hasFocusTrap &&
    (hasEscapeTrigger || hasOutsideClickTrigger) &&
    hasBooleanOpenChannel;
  // Modal-pattern: useFocusTrap + escape trigger → useDismissal for escape key.
  // Also used as the fallback when AnchorToggle can't be wired (no boolean channel).
  const useDismissalHook =
    (hasFocusTrap && hasEscapeTrigger) ||
    (!useAnchor && hasEscapeTrigger);

  if (
    channels.length === 0 &&
    !hasFocusTrap &&
    !hasScrollLock &&
    !hasPortal &&
    !useAnchor
  ) {
    return null;
  }

  return {
    useControllableState: channels,
    useFocusTrap: hasFocusTrap,
    useScrollLock: hasScrollLock,
    usePortal: hasPortal,
    useAnchorToggle: useAnchor,
    useDismissal: useDismissalHook,
    hasEscapeTrigger,
    hasOutsideClickTrigger,
  };
}

/**
 * Look up a hook prop by name in the contract's `props.hook.members` list,
 * which the IR carries on `behavior.<...>` indirectly. We re-derive it from
 * the raw contract via `behavior` instead of `styledProps` because hook
 * props are a separate API surface.
 */
function findHookProp(
  ir: ComponentIR,
  name: string,
): ResolvedPropIR | undefined {
  return ir.styledProps.find((p) => p.name === name);
}

/**
 * Build the `Use<Name>Options` interface body. Each entry corresponds to a
 * hook prop the generator references in the body. Today this is the union
 * of channel props (value/default/onChange), dismissal toggle props, and
 * focus/portal target refs.
 */
function generateOptionsInterface(
  ir: ComponentIR,
  bindings: PrimitiveBindings,
): string {
  const lines: string[] = [`export interface Use${ir.name}Options {`];

  for (const ch of bindings.useControllableState) {
    const t = ch.valueType ?? "unknown";
    lines.push(`  /** Controlled "${ch.name}" value. */`);
    lines.push(`  ${ch.valueProp}?: ${t};`);
    if (ch.defaultValueProp) {
      lines.push(`  /** Initial uncontrolled "${ch.name}" value. */`);
      lines.push(`  ${ch.defaultValueProp}?: ${t};`);
    }
    lines.push(`  /** Called when "${ch.name}" changes. */`);
    lines.push(`  ${ch.changeHandlerProp}?: (value: ${t}) => void;`);
  }

  for (const t of ir.behavior.normalizedDismissalTriggers) {
    if (!t.enabledByProp) continue;
    lines.push(
      `  /** ${t.description ?? `Whether "${t.event}" dismissal is enabled.`} */`,
    );
    lines.push(`  ${t.enabledByProp}?: boolean;`);
  }

  if (bindings.useFocusTrap) {
    const initial = ir.behavior.focus?.initialFocus;
    const returnTo = ir.behavior.focus?.returnFocus;
    if (initial?.startsWith("prop:")) {
      lines.push(
        `  /** Element to focus when the component activates. */`,
      );
      lines.push(`  ${initial.slice(5)}?: RefObject<HTMLElement | null>;`);
    }
    if (returnTo?.startsWith("prop:")) {
      lines.push(`  /** Element to focus when the component deactivates. */`);
      lines.push(`  ${returnTo.slice(5)}?: RefObject<HTMLElement | null>;`);
    }
  }

  if (bindings.usePortal) {
    const targetProp = ir.behavior.portal?.targetProp;
    if (targetProp) {
      lines.push(
        `  /** DOM element or selector for the portal mount point. */`,
      );
      lines.push(`  ${targetProp}?: Element | string;`);
    }
  }

  lines.push(`}`);
  return lines.join("\n");
}

/**
 * Build the `Use<Name>Result` interface — the public shape the component
 * binds to. Composed from whichever primitive bindings are active.
 */
function generateResultInterface(
  ir: ComponentIR,
  bindings: PrimitiveBindings,
): string {
  const lines: string[] = [`export interface Use${ir.name}Result {`];

  for (const ch of bindings.useControllableState) {
    const t = ch.valueType ?? "unknown";
    const setter = `set${capitalize(ch.name)}`;
    lines.push(`  ${ch.name}: ${t};`);
    lines.push(`  ${setter}: (next: ${t}) => void;`);
  }

  if (bindings.useFocusTrap || bindings.usePortal || bindings.useAnchorToggle) {
    lines.push(`  panelRef: RefObject<HTMLDivElement | null>;`);
  }
  if (bindings.useAnchorToggle) {
    lines.push(`  anchorRef: RefObject<HTMLElement | null>;`);
  }
  if (bindings.usePortal) {
    lines.push(`  renderInPortal: (node: ReactNode) => ReactNode;`);
  }

  lines.push(`}`);
  return lines.join("\n");
}

function generateImports(bindings: PrimitiveBindings): string {
  const reactNamed: string[] = [];
  const reactTypes: string[] = [];
  if (bindings.useFocusTrap || bindings.usePortal || bindings.useAnchorToggle) {
    reactNamed.push("useRef");
    reactTypes.push("type RefObject");
  }
  if (bindings.usePortal) reactTypes.push("type ReactNode");

  const primitives: string[] = [];
  if (bindings.useControllableState.length > 0)
    primitives.push("useControllableState");
  if (bindings.useDismissal) primitives.push("useDismissal");
  if (bindings.useFocusTrap) primitives.push("useFocusTrap");
  if (bindings.useScrollLock) primitives.push("useScrollLock");
  if (bindings.usePortal) primitives.push("usePortal");
  if (bindings.useAnchorToggle) primitives.push("useAnchorToggle");

  const lines: string[] = [];
  if (reactNamed.length > 0 || reactTypes.length > 0) {
    const all = [...reactTypes, ...reactNamed].sort();
    lines.push(`import { ${all.join(", ")} } from "react";`);
  }
  if (primitives.length > 0) {
    lines.push(
      `import { ${primitives.sort().join(", ")} } from "../../primitives/hooks";`,
    );
  }
  return lines.join("\n");
}

/**
 * Emit `export type X = ...;` declarations for any contract-defined types
 * referenced by channels. The hook file self-contains these so it works
 * regardless of whether the component file (legacy or migrated) exports them.
 * Types are exported so consumers (and the component) can reuse them.
 */
function generateInlineTypes(
  ir: ComponentIR,
  bindings: PrimitiveBindings,
): string {
  const referenced = new Set<string>();
  for (const ch of bindings.useControllableState) {
    if (ch.valueType && ir.definedTypes[ch.valueType]) {
      referenced.add(ch.valueType);
    }
  }
  if (referenced.size === 0) return "";

  const lines: string[] = [];
  for (const name of [...referenced].sort()) {
    const def = ir.definedTypes[name];
    if (def.kind === "union" && def.values) {
      lines.push(
        `export type ${name} = ${def.values.map((v) => `"${v}"`).join(" | ")};`,
      );
    } else if (def.kind === "alias" && def.alias) {
      lines.push(`export type ${name} = ${def.alias};`);
    }
  }
  return lines.join("\n");
}

/**
 * Select the channel that represents the component's open/closed (visibility)
 * state — the one `useAnchorToggle` should manage. Prefers a boolean channel
 * named `open` or `expanded`; falls back to any boolean channel; returns
 * `undefined` when none qualify (in which case `useAnchorToggle` should not be
 * wired to any channel — its open state is internal). Callers must check that
 * the contract actually carries one before treating anchor-toggle as owning a
 * channel.
 */
function pickOpenChannel(
  channels: NormalizedChannelIR[],
): NormalizedChannelIR | undefined {
  const boolChannels = channels.filter((c) => c.valueType === "boolean");
  return (
    boolChannels.find((c) => c.name === "open") ??
    boolChannels.find((c) => c.name === "expanded") ??
    boolChannels[0]
  );
}

function generateBody(ir: ComponentIR, bindings: PrimitiveBindings): string {
  const lines: string[] = [];
  lines.push(
    `export function use${ir.name}(options: Use${ir.name}Options = {}): Use${ir.name}Result {`,
  );

  // useAnchorToggle internally manages an open boolean via useControllableState,
  // so when present we elide the redundant per-hook call for the channel it owns.
  // The channel must be boolean — non-boolean channels (Walkthrough's step:number,
  // Select's value:string|string[]) are left alone and managed by useControllableState
  // independently of anchor-toggle's internal open state.
  const openChannel = pickOpenChannel(bindings.useControllableState);
  const anchorOwnsChannel =
    bindings.useAnchorToggle &&
    !!openChannel &&
    openChannel.valueType === "boolean";

  // Channels (skipping the one anchorToggle handles)
  for (const ch of bindings.useControllableState) {
    if (anchorOwnsChannel && ch === openChannel) continue;
    const setter = `set${capitalize(ch.name)}`;
    const t = ch.valueType ?? "unknown";
    const def = defaultExprFor(ir, ch.defaultValueProp, t);
    const defaultExpr = ch.defaultValueProp
      ? `options.${ch.defaultValueProp} ?? ${def}`
      : def;
    lines.push(
      `  const [${ch.name}, ${setter}] = useControllableState<${t}>({`,
    );
    lines.push(`    controlled: options.${ch.valueProp},`);
    lines.push(`    defaultValue: ${defaultExpr},`);
    lines.push(`    onChange: options.${ch.changeHandlerProp},`);
    lines.push(`  });`);
    lines.push(``);
  }

  // Refs (panel/anchor)
  if (bindings.useFocusTrap || bindings.usePortal) {
    lines.push(`  const panelRef = useRef<HTMLDivElement>(null);`);
  }
  if (bindings.useAnchorToggle) {
    lines.push(`  // anchor + panel refs come from useAnchorToggle below.`);
  }

  // useDismissal (focus-trap components: Modal, etc.) — escape key handling
  if (bindings.useDismissal) {
    const openChannel = bindings.useControllableState.find(
      (c) => c.valueType === "boolean",
    );
    const escapeProp = ir.behavior.normalizedDismissalTriggers.find(
      (t) => t.event === "escape",
    )?.enabledByProp;
    if (openChannel) {
      const setter = `set${capitalize(openChannel.name)}`;
      lines.push(`  useDismissal({`);
      lines.push(`    open: ${openChannel.name},`);
      lines.push(`    onDismiss: () => ${setter}(false),`);
      if (escapeProp) {
        lines.push(`    closeOnEscape: options.${escapeProp} !== false,`);
      }
      lines.push(`  });`);
      lines.push(``);
    }
  }

  // useAnchorToggle composition (overlay-style components without focus trap).
  // Wires the boolean open-channel into anchor-toggle when one exists; when
  // the contract has dismissal/portal but no boolean channel (rare), the
  // anchor-toggle runs with an internal default-false open state.
  if (bindings.useAnchorToggle) {
    const escapeProp = ir.behavior.normalizedDismissalTriggers.find(
      (t) => t.event === "escape",
    )?.enabledByProp;
    const outsideProp = ir.behavior.normalizedDismissalTriggers.find(
      (t) => t.event === "outsideClick" || t.event === "overlayClick",
    )?.enabledByProp;
    lines.push(`  const anchorToggle = useAnchorToggle({`);
    if (openChannel && openChannel.valueType === "boolean") {
      lines.push(`    open: options.${openChannel.valueProp},`);
      // Only reference options.<defaultValueProp> when the channel declared one;
      // otherwise pass a literal false so we don't reference an undeclared option.
      if (openChannel.defaultValueProp) {
        lines.push(
          `    defaultOpen: options.${openChannel.defaultValueProp} ?? false,`,
        );
      } else {
        lines.push(`    defaultOpen: false,`);
      }
      lines.push(`    onOpenChange: options.${openChannel.changeHandlerProp},`);
    }
    if (escapeProp) {
      lines.push(`    closeOnEscape: options.${escapeProp} !== false,`);
    }
    if (outsideProp) {
      lines.push(
        `    closeOnOutsideClick: options.${outsideProp} !== false,`,
      );
    }
    lines.push(`  });`, ``);
  }

  // Focus trap
  if (bindings.useFocusTrap) {
    const channel = bindings.useControllableState.find((c) =>
      c.valueType === "boolean" || c.name === "open",
    );
    const activeExpr = channel ? channel.name : "true";
    const initial = ir.behavior.focus?.initialFocus;
    const returnTo = ir.behavior.focus?.returnFocus;
    const initialRef =
      initial?.startsWith("prop:")
        ? `options.${initial.slice(5)}`
        : "undefined";
    const returnRef =
      returnTo?.startsWith("prop:")
        ? `options.${returnTo.slice(5)}`
        : "undefined";
    lines.push(`  useFocusTrap(panelRef, {`);
    lines.push(`    active: ${activeExpr},`);
    if (initialRef !== "undefined")
      lines.push(`    initialFocusRef: ${initialRef},`);
    if (returnRef !== "undefined")
      lines.push(`    returnFocusRef: ${returnRef},`);
    lines.push(`  });`, ``);
  }

  // Scroll lock
  if (bindings.useScrollLock) {
    const channel = bindings.useControllableState.find((c) =>
      c.valueType === "boolean" || c.name === "open",
    );
    lines.push(`  useScrollLock(${channel?.name ?? "true"});`);
    lines.push(``);
  }

  // Portal
  if (bindings.usePortal) {
    const targetProp = ir.behavior.portal?.targetProp;
    const target = targetProp ? `options.${targetProp}` : "undefined";
    lines.push(`  const portal = usePortal({`);
    lines.push(`    enabled: true,`);
    if (target !== "undefined") lines.push(`    target: ${target},`);
    lines.push(`  });`, ``);
  }

  // Build return object
  lines.push(`  return {`);
  for (const ch of bindings.useControllableState) {
    const setter = `set${capitalize(ch.name)}`;
    if (anchorOwnsChannel && ch === openChannel) {
      lines.push(`    ${ch.name}: anchorToggle.open,`);
      lines.push(`    ${setter}: anchorToggle.setOpen,`);
    } else {
      lines.push(`    ${ch.name},`);
      lines.push(`    ${setter},`);
    }
  }
  if (bindings.useAnchorToggle) {
    lines.push(`    anchorRef: anchorToggle.anchorRef,`);
    lines.push(`    panelRef: anchorToggle.panelRef as RefObject<HTMLDivElement | null>,`);
  } else if (bindings.useFocusTrap || bindings.usePortal) {
    lines.push(`    panelRef,`);
  }
  if (bindings.usePortal) {
    lines.push(`    renderInPortal: portal.render,`);
  }
  lines.push(`  };`);
  lines.push(`}`);
  return lines.join("\n");
}

function defaultExprFor(
  ir: ComponentIR,
  defaultProp: string | undefined,
  valueType: string,
): string {
  // Source default from the matching hook member if available.
  if (defaultProp) {
    const member = findHookProp(ir, defaultProp);
    if (member?.defaultExpr) return member.defaultExpr;
  }
  if (valueType === "boolean") return "false";
  if (valueType === "number") return "0";
  if (valueType === "string") return '""';
  return "undefined as never";
}

function capitalize(s: string): string {
  return s[0].toUpperCase() + s.slice(1);
}

/**
 * Generate the full `use<Name>.ts` source for a component IR. Returns
 * `null` when the contract has no behavior worth lifting.
 */
export function generateReactHookSource(ir: ComponentIR): string | null {
  const bindings = resolveBindings(ir);
  if (!bindings) return null;

  const importsBody = generateImports(bindings);
  const inlineTypesBody = generateInlineTypes(ir, bindings);
  const optionsBody = generateOptionsInterface(ir, bindings);
  const resultBody = generateResultInterface(ir, bindings);
  const hookBody = generateBody(ir, bindings);

  const typesBody = [inlineTypesBody, optionsBody, resultBody]
    .filter((s) => s.length > 0)
    .join("\n\n");

  const blank = (): Section => ({ kind: "between", body: "" });
  const sections: Section[] = [
    { kind: "generated", id: "imports", body: importsBody },
    blank(),
    { kind: "custom", id: "imports", body: "" },
    blank(),
    { kind: "generated", id: "types", body: typesBody },
    blank(),
    { kind: "custom", id: "types", body: "" },
    blank(),
    { kind: "generated", id: "hook", body: hookBody },
    blank(),
    { kind: "custom", id: "trailing", body: "" },
    blank(),
  ];

  return renderSections(sections, "line");
}
