// packages/ds-codegen/src/frameworks/angular/surface-tests.ts
/**
 * Angular behavioral tests for the Anchored Presence Surface family.
 *
 * Parity with React (499ed17), Vue (38454fe), Svelte (43863a0,
 * 29f3fb4), and Lit (c4ed447). Covers default-host vs directive-based
 * host adoption, ARIA wiring, controlled/uncontrolled state, disabled
 * suppression, closeOn* opt-outs, grace path, unmount cleanup, and
 * the consumer-preventDefault opt-out.
 *
 * Stack: Jest + jest-preset-angular + TestBed. Native event dispatch.
 */
import type { ComponentIR } from "../../ir.js";
import { isAnchoredPresenceKind } from "../../semantics.js";

export function generateAngularSurfaceTest(ir: ComponentIR): string {
  const surface = ir.surface;
  if (!surface) {
    throw new Error(
      `generateAngularSurfaceTest called on ${ir.name} without ir.surface`,
    );
  }
  if (!isAnchoredPresenceKind(surface.kind)) {
    throw new Error(
      `Angular surface test emitter expected an anchored-presence kind (got "${surface.kind}"). ` +
        `Add the kind to ANCHORED_PRESENCE_KINDS in semantics.ts when its substrate is ready.`,
    );
  }
  // Test-body shape is kind-specific (Tooltip's hover/focus contract
  // vs Popover's click contract). Each kind has its own scaffold
  // function; dispatch on kind here. Body emission is realization,
  // not policy.
  if (surface.kind === "popover") {
    return emitPopoverTests(ir);
  }
  return emitTooltipTests(ir);
}

function kebab(name: string): string {
  return name.replace(/([A-Z])/g, "-$1").toLowerCase().replace(/^-/, "");
}

function emitTooltipTests(ir: ComponentIR): string {
  const name = ir.name;
  const cssPrefix = ir.cssPrefix;
  const rootTag = `fsds-${kebab(name)}`;
  const triggerTag = `${rootTag}-trigger`;
  const contentTag = `${rootTag}-content`;

  const importsBody = [
    `import { describe, expect, it, beforeEach, jest } from "@jest/globals";`,
    `import { Component } from "@angular/core";`,
    `import { TestBed } from "@angular/core/testing";`,
    `import { ${name}Component } from "../${name}.component";`,
    `import { ${name}TriggerComponent } from "../${name}Trigger.component";`,
    `import { ${name}TriggerDirective } from "../${name}Trigger.directive";`,
    `import { ${name}ContentComponent } from "../${name}Content.component";`,
    ``,
    `// jsdom doesn't ship PointerEvent. Polyfill via MouseEvent so the`,
    `// substrate's pointerenter/pointerleave listeners receive an event`,
    `// object with the right \`type\`, \`relatedTarget\`, \`cancelable\`, and`,
    `// \`defaultPrevented\` semantics. We only need the relatedTarget +`,
    `// defaultPrevented surface, so MouseEvent suffices.`,
    `if (typeof globalThis.PointerEvent === "undefined") {`,
    `  (globalThis as unknown as { PointerEvent: typeof MouseEvent }).PointerEvent = MouseEvent as unknown as typeof PointerEvent;`,
    `}`,
  ].join("\n");

  const testsBody = `function mount(setup: (host: TooltipFixture) => void = () => {}) {
  const fixture = TestBed.createComponent(TooltipFixture);
  setup(fixture.componentInstance);
  fixture.detectChanges();
  return fixture;
}

async function settle(): Promise<void> {
  // Resolve queued microtasks (substrate open-triggers defer via
  // queueMicrotask for consumer-preventDefault support).
  await Promise.resolve();
  await Promise.resolve();
}

function getAnchor(host: HTMLElement, adopted: boolean): HTMLElement {
  if (adopted) return host.querySelector("[data-testid='anchor']") as HTMLElement;
  // Default-host: <fsds-tooltip-trigger> renders a <button> inside
  // itself, which the directive registers as the anchor.
  return host.querySelector("[data-testid='trigger-host'] button") as HTMLElement;
}

function getContentEl(host: HTMLElement): HTMLElement | null {
  const el = host.querySelector("[data-testid='content']") as HTMLElement | null;
  return el?.hasAttribute("data-${cssPrefix}-content") ? el : null;
}

beforeEach(() => {
  TestBed.configureTestingModule({ imports: [TooltipFixture] });
});

describe("${name} — compound API surface (default-host)", () => {
  it("renders the trigger but not the content when closed", () => {
    const fixture = mount();
    const host = fixture.nativeElement as HTMLElement;
    expect(getAnchor(host, false)).toBeTruthy();
    expect(getContentEl(host)).toBeNull();
  });

  it("renders the content when defaultOpen=true", () => {
    const fixture = mount((c) => { c.defaultOpen = true; });
    const host = fixture.nativeElement as HTMLElement;
    expect(getContentEl(host)).toBeTruthy();
    expect(getContentEl(host)?.getAttribute("role")).toBe("tooltip");
  });

  it("opens on pointerenter (hover) over the default <button>", async () => {
    const fixture = mount();
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    anchor.dispatchEvent(new PointerEvent("pointerenter", { bubbles: true }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeTruthy();
  });

  it("opens on focus over the default <button>", async () => {
    const fixture = mount();
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    anchor.dispatchEvent(new FocusEvent("focus"));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeTruthy();
  });

  it("closes on pointerleave from the anchor (no grace path into content)", async () => {
    const fixture = mount((c) => { c.defaultOpen = true; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    anchor.dispatchEvent(new PointerEvent("pointerleave", { bubbles: true, relatedTarget: document.body }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeNull();
  });

  it("closes on Escape", async () => {
    const fixture = mount((c) => { c.defaultOpen = true; });
    const host = fixture.nativeElement as HTMLElement;
    document.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape", bubbles: true }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeNull();
  });

  it("closes on focus leaving the surface boundary (focusout)", async () => {
    // Boundary semantics: the substrate listens via focusout
    // (which bubbles, unlike blur) for focus leaving the anchor +
    // content surface. Focus moving from anchor to an outside node
    // dismisses; focus moving from anchor INTO content does not.
    const fixture = mount((c) => { c.defaultOpen = true; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    anchor.dispatchEvent(new FocusEvent("focusout", { bubbles: true, relatedTarget: document.body }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeNull();
  });

  it("wires aria-describedby from anchor to content when open", () => {
    const fixture = mount((c) => { c.defaultOpen = true; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    const content = getContentEl(host)!;
    const id = content.getAttribute("id");
    expect(id).toBeTruthy();
    expect(anchor.getAttribute("aria-describedby")).toBe(id);
  });

  it("does NOT set aria-describedby when closed", () => {
    const fixture = mount();
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    expect(anchor.getAttribute("aria-describedby")).toBeNull();
  });

  it("fires onOpenChange on uncontrolled open", async () => {
    const spy = jest.fn();
    const fixture = mount((c) => { c.onOpenChange = spy; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    anchor.dispatchEvent(new PointerEvent("pointerenter", { bubbles: true }));
    await settle();
    expect(spy).toHaveBeenCalledWith(true);
  });

  it("respects disabled — pointerenter does not open", async () => {
    const fixture = mount((c) => { c.disabled = true; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    anchor.dispatchEvent(new PointerEvent("pointerenter", { bubbles: true }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeNull();
  });

  it("disabled root does not fire onOpenChange on hover", async () => {
    const spy = jest.fn();
    const fixture = mount((c) => { c.disabled = true; c.onOpenChange = spy; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    anchor.dispatchEvent(new PointerEvent("pointerenter", { bubbles: true }));
    await settle();
    expect(spy).not.toHaveBeenCalled();
  });

  it("controlled open prop overrides internal state", async () => {
    // Phase 1: mount with open=false; verify pointerenter does NOT open.
    const fixture = mount((c) => { c.open = false; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    anchor.dispatchEvent(new PointerEvent("pointerenter", { bubbles: true }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeNull();
    // Phase 2: mount a fresh fixture with open=true; verify content is
    // rendered. We mount fresh instead of mutating because jest-preset-
    // angular's strict change-detection rejects post-detectChanges
    // mutation of consumer @Input bindings.
    fixture.destroy();
    const fixture2 = mount((c) => { c.open = true; });
    const host2 = fixture2.nativeElement as HTMLElement;
    expect(getContentEl(host2)).toBeTruthy();
  });

  it("pointerleave INTO content does not close (grace path)", async () => {
    const fixture = mount((c) => { c.defaultOpen = true; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    const content = getContentEl(host)!;
    anchor.dispatchEvent(new PointerEvent("pointerleave", { bubbles: true, relatedTarget: content }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeTruthy();
  });

  it("closeOnEscape=false prevents Escape dismissal", async () => {
    const fixture = mount((c) => { c.defaultOpen = true; c.closeOnEscape = false; });
    const host = fixture.nativeElement as HTMLElement;
    document.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape", bubbles: true }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeTruthy();
  });

  it("closeOnBlur=false prevents boundary-focusout dismissal", async () => {
    const fixture = mount((c) => { c.defaultOpen = true; c.closeOnBlur = false; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    anchor.dispatchEvent(new FocusEvent("focusout", { bubbles: true, relatedTarget: document.body }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeTruthy();
  });

  it("destroying the fixture removes document-level listeners", async () => {
    const spy = jest.fn();
    const fixture = mount((c) => { c.defaultOpen = true; c.onOpenChange = spy; });
    fixture.destroy();
    document.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape", bubbles: true }));
    await settle();
    expect(spy).not.toHaveBeenCalled();
  });
});

describe("${name} — directive-based host adoption", () => {
  it("uses the adopted <a> as the actual anchor (no nested button)", () => {
    const fixture = mount((c) => { c.adopted = true; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, true);
    expect(anchor.tagName).toBe("A");
    expect(anchor.hasAttribute("data-${cssPrefix}-trigger")).toBe(true);
    // There should be NO <button> rendered alongside it because we
    // chose the adopted path.
    expect(host.querySelector("button")).toBeNull();
  });

  it("adopted host opens on pointerenter", async () => {
    const fixture = mount((c) => { c.adopted = true; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, true);
    anchor.dispatchEvent(new PointerEvent("pointerenter", { bubbles: true }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeTruthy();
  });

  it("adopted host opens on focus", async () => {
    const fixture = mount((c) => { c.adopted = true; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, true);
    anchor.dispatchEvent(new FocusEvent("focus"));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeTruthy();
  });

  it("adopted host receives aria-describedby when open", () => {
    const fixture = mount((c) => { c.adopted = true; c.defaultOpen = true; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, true);
    const content = getContentEl(host)!;
    expect(anchor.getAttribute("aria-describedby")).toBe(content.getAttribute("id"));
  });

  it("consumer event.preventDefault() suppresses the surface handler", async () => {
    const surfaceSpy = jest.fn();
    const fixture = mount((c) => {
      c.adopted = true;
      c.onOpenChange = surfaceSpy;
      c.onConsumerPointerEnter = (e) => e.preventDefault();
    });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, true);
    anchor.dispatchEvent(new PointerEvent("pointerenter", { bubbles: true, cancelable: true }));
    await settle();
    fixture.detectChanges();
    expect(surfaceSpy).not.toHaveBeenCalled();
    expect(getContentEl(host)).toBeNull();
  });
});`;

  return [
    `// @generated:start imports`,
    importsBody,
    `import { NgIf } from "@angular/common";`,
    `// @generated:end`,
    ``,
    `// @generated:start fixture`,
    // Use the corrected version (without the duplicate imports block)
    `@Component({`,
    `  selector: "${rootTag}-fixture",`,
    `  standalone: true,`,
    `  imports: [`,
    `    NgIf,`,
    `    ${name}Component,`,
    `    ${name}TriggerComponent,`,
    `    ${name}TriggerDirective,`,
    `    ${name}ContentComponent,`,
    `  ],`,
    `  template: \``,
    `    <${rootTag}`,
    `      [open]="open"`,
    `      [defaultOpen]="defaultOpen"`,
    `      [disabled]="disabled"`,
    `      [closeOnEscape]="closeOnEscape"`,
    `      [closeOnBlur]="closeOnBlur"`,
    `      [onOpenChange]="onOpenChange"`,
    `    >`,
    `      <ng-container *ngIf="adopted">`,
    `        <a fsds${name}Trigger href="#help" data-testid="anchor" (pointerenter)="onConsumerPointerEnter && onConsumerPointerEnter($event)">Save</a>`,
    `      </ng-container>`,
    `      <ng-container *ngIf="!adopted">`,
    `        <${triggerTag} data-testid="trigger-host">Save</${triggerTag}>`,
    `      </ng-container>`,
    `      <${contentTag} data-testid="content">Help text</${contentTag}>`,
    `    </${rootTag}>`,
    `  \`,`,
    `})`,
    `class TooltipFixture {`,
    `  open?: boolean;`,
    `  defaultOpen?: boolean;`,
    `  disabled?: boolean;`,
    `  closeOnEscape?: boolean;`,
    `  closeOnBlur?: boolean;`,
    `  adopted = false;`,
    `  onOpenChange?: (v: boolean) => void;`,
    `  onConsumerPointerEnter?: (e: PointerEvent) => void;`,
    `}`,
    `// @generated:end`,
    ``,
    `// @generated:start tests`,
    testsBody,
    `// @generated:end`,
    ``,
    `// @custom:start tests`,
    ``,
    `// @custom:end`,
    ``,
  ].join("\n");
}

function emitPopoverTests(ir: ComponentIR): string {
  const name = ir.name;
  const cssPrefix = ir.cssPrefix;
  const rootTag = `fsds-${kebab(name)}`;
  const triggerTag = `${rootTag}-trigger`;
  const contentTag = `${rootTag}-content`;

  const importsBody = [
    `import { describe, expect, it, beforeEach, jest } from "@jest/globals";`,
    `import { Component } from "@angular/core";`,
    `import { TestBed } from "@angular/core/testing";`,
    `import { ${name}Component } from "../${name}.component";`,
    `import { ${name}TriggerComponent } from "../${name}Trigger.component";`,
    `import { ${name}TriggerDirective } from "../${name}Trigger.directive";`,
    `import { ${name}ContentComponent } from "../${name}Content.component";`,
  ].join("\n");

  const testsBody = `function mount(setup: (host: PopoverFixture) => void = () => {}) {
  const fixture = TestBed.createComponent(PopoverFixture);
  setup(fixture.componentInstance);
  fixture.detectChanges();
  return fixture;
}

async function settle(): Promise<void> {
  // Resolve queued microtasks (substrate open-triggers defer via
  // queueMicrotask for consumer-preventDefault support).
  await Promise.resolve();
  await Promise.resolve();
}

function getAnchor(host: HTMLElement, adopted: boolean): HTMLElement {
  if (adopted) return host.querySelector("[data-testid='anchor']") as HTMLElement;
  // Default-host: <fsds-popover-trigger> renders a <button> inside
  // itself, which the directive registers as the anchor.
  return host.querySelector("[data-testid='trigger-host'] button") as HTMLElement;
}

function getContentEl(host: HTMLElement): HTMLElement | null {
  const el = host.querySelector("[data-testid='content']") as HTMLElement | null;
  return el?.hasAttribute("data-${cssPrefix}-content") ? el : null;
}

beforeEach(() => {
  TestBed.configureTestingModule({ imports: [PopoverFixture] });
});

describe("${name} — compound API surface (default-host)", () => {
  it("renders the trigger but not the content when closed", () => {
    const fixture = mount();
    const host = fixture.nativeElement as HTMLElement;
    expect(getAnchor(host, false)).toBeTruthy();
    expect(getContentEl(host)).toBeNull();
  });

  it("renders the content when defaultOpen=true", () => {
    const fixture = mount((c) => { c.defaultOpen = true; });
    const host = fixture.nativeElement as HTMLElement;
    expect(getContentEl(host)).toBeTruthy();
  });

  it("opens on click of the default <button>", async () => {
    const fixture = mount();
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    anchor.dispatchEvent(new MouseEvent("click", { bubbles: true }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeTruthy();
  });

  it("toggles closed on a second click of the default <button>", async () => {
    const fixture = mount((c) => { c.defaultOpen = true; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    anchor.dispatchEvent(new MouseEvent("click", { bubbles: true }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeNull();
  });

  it("closes on Escape", async () => {
    const fixture = mount((c) => { c.defaultOpen = true; });
    const host = fixture.nativeElement as HTMLElement;
    document.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape", bubbles: true }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeNull();
  });

  it("closes on outside-click", async () => {
    const fixture = mount((c) => { c.defaultOpen = true; });
    const host = fixture.nativeElement as HTMLElement;
    document.body.dispatchEvent(new MouseEvent("mousedown", { bubbles: true }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeNull();
  });

  it("click inside content does not count as outside-click", async () => {
    const fixture = mount((c) => { c.defaultOpen = true; });
    const host = fixture.nativeElement as HTMLElement;
    const content = getContentEl(host)!;
    content.dispatchEvent(new MouseEvent("mousedown", { bubbles: true }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeTruthy();
  });

  it("focus moving from anchor into content stays open (boundary)", async () => {
    const fixture = mount((c) => { c.defaultOpen = true; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    const content = getContentEl(host)!;
    anchor.dispatchEvent(new FocusEvent("focusout", { bubbles: true, relatedTarget: content }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeTruthy();
  });

  it("focus moving from content to outside closes (boundary-focusout)", async () => {
    const fixture = mount((c) => { c.defaultOpen = true; });
    const host = fixture.nativeElement as HTMLElement;
    const content = getContentEl(host)!;
    content.dispatchEvent(new FocusEvent("focusout", { bubbles: true, relatedTarget: document.body }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeNull();
  });

  it("focus moving from anchor to outside closes (boundary-focusout)", async () => {
    const fixture = mount((c) => { c.defaultOpen = true; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    anchor.dispatchEvent(new FocusEvent("focusout", { bubbles: true, relatedTarget: document.body }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeNull();
  });

  it("wires aria-controls + aria-expanded on the anchor when open", () => {
    const fixture = mount((c) => { c.defaultOpen = true; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    const content = getContentEl(host)!;
    const id = content.getAttribute("id");
    expect(id).toBeTruthy();
    expect(anchor.getAttribute("aria-controls")).toBe(id);
    expect(anchor.getAttribute("aria-expanded")).toBe("true");
  });

  it("aria-expanded reflects closed state", () => {
    const fixture = mount();
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    expect(anchor.getAttribute("aria-expanded")).toBe("false");
  });

  it("content has no forced ARIA role (policy: defaultContentRole=null)", () => {
    const fixture = mount((c) => { c.defaultOpen = true; });
    const host = fixture.nativeElement as HTMLElement;
    const content = getContentEl(host)!;
    expect(content.getAttribute("role")).toBeNull();
  });

  it("fires onOpenChange on uncontrolled open", async () => {
    const spy = jest.fn();
    const fixture = mount((c) => { c.onOpenChange = spy; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    anchor.dispatchEvent(new MouseEvent("click", { bubbles: true }));
    await settle();
    expect(spy).toHaveBeenCalledWith(true);
  });

  it("respects disabled — click does not open", async () => {
    const fixture = mount((c) => { c.disabled = true; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    anchor.dispatchEvent(new MouseEvent("click", { bubbles: true }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeNull();
  });

  it("controlled open prop overrides internal state", async () => {
    // Phase 1: mount with open=false; verify click does NOT open.
    const fixture = mount((c) => { c.open = false; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    anchor.dispatchEvent(new MouseEvent("click", { bubbles: true }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeNull();
    // Phase 2: mount a fresh fixture with open=true; verify content is
    // rendered. We mount fresh instead of mutating because jest-preset-
    // angular's strict change-detection rejects post-detectChanges
    // mutation of consumer @Input bindings.
    fixture.destroy();
    const fixture2 = mount((c) => { c.open = true; });
    const host2 = fixture2.nativeElement as HTMLElement;
    expect(getContentEl(host2)).toBeTruthy();
  });

  it("closeOnEscape=false prevents Escape dismissal", async () => {
    const fixture = mount((c) => { c.defaultOpen = true; c.closeOnEscape = false; });
    const host = fixture.nativeElement as HTMLElement;
    document.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape", bubbles: true }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeTruthy();
  });

  it("closeOnOutsideClick=false prevents outside-click dismissal", async () => {
    const fixture = mount((c) => { c.defaultOpen = true; c.closeOnOutsideClick = false; });
    const host = fixture.nativeElement as HTMLElement;
    document.body.dispatchEvent(new MouseEvent("mousedown", { bubbles: true }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeTruthy();
  });

  it("closeOnBlur=false prevents boundary-focusout dismissal", async () => {
    const fixture = mount((c) => { c.defaultOpen = true; c.closeOnBlur = false; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, false);
    anchor.dispatchEvent(new FocusEvent("focusout", { bubbles: true, relatedTarget: document.body }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeTruthy();
  });

  it("destroying the fixture removes document-level listeners", async () => {
    const spy = jest.fn();
    const fixture = mount((c) => { c.defaultOpen = true; c.onOpenChange = spy; });
    fixture.destroy();
    document.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape", bubbles: true }));
    await settle();
    expect(spy).not.toHaveBeenCalled();
  });
});

describe("${name} — directive-based host adoption", () => {
  it("uses the adopted <a> as the actual anchor (no nested button)", () => {
    const fixture = mount((c) => { c.adopted = true; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, true);
    expect(anchor.tagName).toBe("A");
    expect(anchor.hasAttribute("data-${cssPrefix}-trigger")).toBe(true);
    expect(host.querySelector("button")).toBeNull();
  });

  it("adopted host opens on click", async () => {
    const fixture = mount((c) => { c.adopted = true; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, true);
    anchor.dispatchEvent(new MouseEvent("click", { bubbles: true }));
    await settle();
    fixture.detectChanges();
    expect(getContentEl(host)).toBeTruthy();
  });

  it("adopted host receives aria-controls + aria-expanded when open", () => {
    const fixture = mount((c) => { c.adopted = true; c.defaultOpen = true; });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, true);
    const content = getContentEl(host)!;
    expect(anchor.getAttribute("aria-controls")).toBe(content.getAttribute("id"));
    expect(anchor.getAttribute("aria-expanded")).toBe("true");
  });

  it("consumer event.preventDefault() suppresses the surface handler", async () => {
    const surfaceSpy = jest.fn();
    const fixture = mount((c) => {
      c.adopted = true;
      c.onOpenChange = surfaceSpy;
      c.onConsumerClick = (e) => e.preventDefault();
    });
    const host = fixture.nativeElement as HTMLElement;
    const anchor = getAnchor(host, true);
    anchor.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
    await settle();
    fixture.detectChanges();
    expect(surfaceSpy).not.toHaveBeenCalled();
    expect(getContentEl(host)).toBeNull();
  });
});`;

  return [
    `// @generated:start imports`,
    importsBody,
    `import { NgIf } from "@angular/common";`,
    `// @generated:end`,
    ``,
    `// @generated:start fixture`,
    `@Component({`,
    `  selector: "${rootTag}-fixture",`,
    `  standalone: true,`,
    `  imports: [`,
    `    NgIf,`,
    `    ${name}Component,`,
    `    ${name}TriggerComponent,`,
    `    ${name}TriggerDirective,`,
    `    ${name}ContentComponent,`,
    `  ],`,
    `  template: \``,
    `    <${rootTag}`,
    `      [open]="open"`,
    `      [defaultOpen]="defaultOpen"`,
    `      [disabled]="disabled"`,
    `      [closeOnEscape]="closeOnEscape"`,
    `      [closeOnBlur]="closeOnBlur"`,
    `      [closeOnOutsideClick]="closeOnOutsideClick"`,
    `      [onOpenChange]="onOpenChange"`,
    `    >`,
    `      <ng-container *ngIf="adopted">`,
    `        <a fsds${name}Trigger href="#open" data-testid="anchor" (click)="onConsumerClick && onConsumerClick($event)">Open</a>`,
    `      </ng-container>`,
    `      <ng-container *ngIf="!adopted">`,
    `        <${triggerTag} data-testid="trigger-host">Open</${triggerTag}>`,
    `      </ng-container>`,
    `      <${contentTag} data-testid="content">Body</${contentTag}>`,
    `    </${rootTag}>`,
    `  \`,`,
    `})`,
    `class PopoverFixture {`,
    `  open?: boolean;`,
    `  defaultOpen?: boolean;`,
    `  disabled?: boolean;`,
    `  closeOnEscape?: boolean;`,
    `  closeOnBlur?: boolean;`,
    `  closeOnOutsideClick?: boolean;`,
    `  adopted = false;`,
    `  onOpenChange?: (v: boolean) => void;`,
    `  onConsumerClick?: (e: MouseEvent) => void;`,
    `}`,
    `// @generated:end`,
    ``,
    `// @generated:start tests`,
    testsBody,
    `// @generated:end`,
    ``,
    `// @custom:start tests`,
    ``,
    `// @custom:end`,
    ``,
  ].join("\n");
}

// packages/ds-codegen/src/frameworks/react/surface-tests.ts
/**
 * React behavioral tests for the Anchored Presence Surface family.
 *
 * Replaces the legacy class-token-only test plan with assertions against
 * actual surface state and ARIA wiring. Tests cover:
 *   - hover on trigger opens content
 *   - focus on trigger opens content
 *   - pointer-leave on trigger closes content
 *   - blur on trigger closes content
 *   - Escape closes content
 *   - aria-describedby on trigger references the content's id when open
 *   - disabled prop suppresses open
 *   - onOpenChange fires on uncontrolled open
 */
import type { ComponentIR } from "../../ir.js";
import { isAnchoredPresenceKind } from "../../semantics.js";

export function generateReactSurfaceTest(ir: ComponentIR): string {
  const surface = ir.surface;
  if (!surface) {
    throw new Error(
      `generateReactSurfaceTest called on ${ir.name} without ir.surface`,
    );
  }
  if (!isAnchoredPresenceKind(surface.kind)) {
    throw new Error(
      `React surface test emitter expected an anchored-presence kind (got "${surface.kind}"). ` +
        `Add the kind to ANCHORED_PRESENCE_KINDS in semantics.ts when its substrate is ready.`,
    );
  }
  // Test-body shape is kind-specific (Tooltip's hover/focus contract
  // vs Popover's click contract). Each kind has its own scaffold
  // function; dispatch on kind here. Body emission is realization,
  // not policy — the policy already said "this kind belongs in the
  // anchored family." Adding a new anchored kind without a scaffold
  // function here would fall through to the tooltip-shaped tests,
  // which is wrong but loud.
  if (surface.kind === "popover") {
    return emitPopoverScaffoldTests(ir);
  }
  return emitTooltipTests(ir);
}

/**
 * Minimal Popover test scaffold emitted by atom B. Asserts the
 * Popover-specific contract shape (click toggles, aria-controls +
 * aria-expanded, asChild adoption, accessibility) without the full
 * behavioral coverage matrix. Atom C extends this with the deep
 * behavioral suite (focus boundary, outside-click, controlled
 * override, disabled, etc.) inside the @custom block.
 */
function emitPopoverScaffoldTests(ir: ComponentIR): string {
  const name = ir.name;
  const cssPrefix = ir.cssPrefix;
  const importsBody = [
    `import { createRef } from "react";`,
    `import { describe, it, expect, vi } from "vitest";`,
    `import { render, screen, fireEvent, act } from "@testing-library/react";`,
    `import { axe } from "vitest-axe";`,
    `import { ${name} } from "../${name}";`,
    ``,
    `declare module "vitest" {`,
    `  interface Assertion<T> {`,
    `    toHaveNoViolations(): void;`,
    `  }`,
    `}`,
  ].join("\n");

  const testsBody = `function renderPopover(props: Partial<React.ComponentProps<typeof ${name}>> = {}) {
  return render(
    <${name} {...props}>
      <${name}.Trigger data-testid="trigger">Open</${name}.Trigger>
      <${name}.Content data-testid="content">
        <button data-testid="content-button">action</button>
      </${name}.Content>
    </${name}>,
  );
}

describe("${name} — compound API surface", () => {
  it("renders the trigger but not the content when closed", () => {
    renderPopover();
    expect(screen.getByTestId("trigger")).toBeInTheDocument();
    expect(screen.queryByTestId("content")).toBeNull();
  });

  it("renders the content when defaultOpen={true}", () => {
    renderPopover({ defaultOpen: true });
    expect(screen.getByTestId("content")).toBeInTheDocument();
  });

  it("opens on click of the trigger", () => {
    renderPopover();
    const trigger = screen.getByTestId("trigger");
    act(() => {
      fireEvent.click(trigger);
    });
    expect(screen.getByTestId("content")).toBeInTheDocument();
  });

  it("toggles closed on a second click of the trigger", () => {
    renderPopover({ defaultOpen: true });
    const trigger = screen.getByTestId("trigger");
    act(() => {
      fireEvent.click(trigger);
    });
    expect(screen.queryByTestId("content")).toBeNull();
  });

  it("closes on Escape", () => {
    renderPopover({ defaultOpen: true });
    act(() => {
      fireEvent.keyDown(document, { key: "Escape" });
    });
    expect(screen.queryByTestId("content")).toBeNull();
  });

  it("wires aria-controls + aria-expanded on the trigger", () => {
    renderPopover({ defaultOpen: true });
    const trigger = screen.getByTestId("trigger");
    const content = screen.getByTestId("content");
    const id = content.getAttribute("id");
    expect(id).toBeTruthy();
    expect(trigger).toHaveAttribute("aria-controls", id);
    expect(trigger).toHaveAttribute("aria-expanded", "true");
  });

  it("aria-expanded reflects closed state", () => {
    renderPopover();
    const trigger = screen.getByTestId("trigger");
    expect(trigger).toHaveAttribute("aria-expanded", "false");
  });

  it("fires onOpenChange on uncontrolled open", () => {
    const spy = vi.fn();
    renderPopover({ onOpenChange: spy });
    act(() => {
      fireEvent.click(screen.getByTestId("trigger"));
    });
    expect(spy).toHaveBeenCalledWith(true);
  });

  it("respects disabled — click does not open", () => {
    renderPopover({ disabled: true });
    act(() => {
      fireEvent.click(screen.getByTestId("trigger"));
    });
    expect(screen.queryByTestId("content")).toBeNull();
  });

  it("unmount removes document-level listeners (no setOpen after unmount)", () => {
    const spy = vi.fn();
    const { unmount } = renderPopover({ defaultOpen: true, onOpenChange: spy });
    unmount();
    act(() => {
      fireEvent.keyDown(document, { key: "Escape" });
    });
    expect(spy).not.toHaveBeenCalled();
  });
});

describe("${name} — asChild adoption", () => {
  it("renders the adopted child as the actual host (no nested button)", () => {
    render(
      <${name}>
        <${name}.Trigger asChild>
          <a href="#open" data-testid="trigger">Open</a>
        </${name}.Trigger>
        <${name}.Content data-testid="content">Body</${name}.Content>
      </${name}>,
    );
    const trigger = screen.getByTestId("trigger");
    expect(trigger.tagName).toBe("A");
    expect(trigger.parentElement?.querySelector("button")).toBeNull();
  });

  it("default-host behavior is unchanged when asChild is absent", () => {
    renderPopover();
    expect(screen.getByTestId("trigger").tagName).toBe("BUTTON");
  });

  it("asChild opens on click over the adopted child", () => {
    render(
      <${name}>
        <${name}.Trigger asChild>
          <a href="#open" data-testid="trigger">Open</a>
        </${name}.Trigger>
        <${name}.Content data-testid="content">Body</${name}.Content>
      </${name}>,
    );
    act(() => {
      fireEvent.click(screen.getByTestId("trigger"));
    });
    expect(screen.getByTestId("content")).toBeInTheDocument();
  });

  it("asChild — consumer event.preventDefault() suppresses the surface handler", () => {
    const surfaceSpy = vi.fn();
    render(
      <${name} onOpenChange={surfaceSpy}>
        <${name}.Trigger asChild>
          <a
            href="#open"
            data-testid="trigger"
            onClick={(e) => e.preventDefault()}
          >
            Open
          </a>
        </${name}.Trigger>
        <${name}.Content data-testid="content">Body</${name}.Content>
      </${name}>,
    );
    act(() => {
      fireEvent.click(screen.getByTestId("trigger"));
    });
    expect(surfaceSpy).not.toHaveBeenCalled();
    expect(screen.queryByTestId("content")).toBeNull();
  });

  it("asChild forwards the consumer's ref to the adopted DOM node", () => {
    const consumerRef = createRef<HTMLAnchorElement>();
    render(
      <${name}>
        <${name}.Trigger asChild>
          <a href="#open" data-testid="trigger" ref={consumerRef}>Open</a>
        </${name}.Trigger>
        <${name}.Content data-testid="content">Body</${name}.Content>
      </${name}>,
    );
    expect(consumerRef.current).not.toBeNull();
    expect(consumerRef.current?.tagName).toBe("A");
  });

  it("asChild applies the data-${cssPrefix}-trigger marker to the adopted host", () => {
    render(
      <${name}>
        <${name}.Trigger asChild>
          <a href="#open" data-testid="trigger">Open</a>
        </${name}.Trigger>
        <${name}.Content data-testid="content">Body</${name}.Content>
      </${name}>,
    );
    expect(screen.getByTestId("trigger")).toHaveAttribute("data-${cssPrefix}-trigger");
  });
});

describe("${name} — accessibility", () => {
  it("has no unexpected axe violations when closed", async () => {
    const { container } = renderPopover();
    const results = (await axe(container)) as unknown as { violations: Array<{ id: string }> };
    expect(results.violations.map((v) => v.id)).toEqual([]);
  });

  it("has no unexpected axe violations when open", async () => {
    const { container } = renderPopover({ defaultOpen: true });
    const results = (await axe(container)) as unknown as { violations: Array<{ id: string }> };
    expect(results.violations.map((v) => v.id)).toEqual([]);
  });
});`;

  return [
    `// @generated:start imports`,
    importsBody,
    `// @generated:end`,
    ``,
    `// @generated:start tests`,
    testsBody,
    `// @generated:end`,
    ``,
    `// @custom:start tests`,
    ``,
    `// @custom:end`,
    ``,
  ].join("\n");
}

function emitTooltipTests(ir: ComponentIR): string {
  const name = ir.name;
  const cssPrefix = ir.cssPrefix;
  const importsBody = [
    `import { createRef } from "react";`,
    `import { describe, it, expect, vi } from "vitest";`,
    `import { render, screen, fireEvent, act } from "@testing-library/react";`,
    `import { axe } from "vitest-axe";`,
    `import { ${name} } from "../${name}";`,
    ``,
    `declare module "vitest" {`,
    `  interface Assertion<T> {`,
    `    toHaveNoViolations(): void;`,
    `  }`,
    `}`,
  ].join("\n");

  const testsBody = `function renderTooltip(props: Partial<React.ComponentProps<typeof ${name}>> = {}) {
  return render(
    <${name} {...props}>
      <${name}.Trigger data-testid="trigger">Open</${name}.Trigger>
      <${name}.Content data-testid="content">Help text</${name}.Content>
    </${name}>,
  );
}

describe("${name} — compound API surface", () => {
  it("renders the trigger but not the content when closed", () => {
    renderTooltip();
    expect(screen.getByTestId("trigger")).toBeInTheDocument();
    expect(screen.queryByTestId("content")).toBeNull();
  });

  it("renders the content when defaultOpen={true}", () => {
    renderTooltip({ defaultOpen: true });
    expect(screen.getByTestId("content")).toBeInTheDocument();
    expect(screen.getByTestId("content")).toHaveAttribute("role", "tooltip");
  });

  it("opens on pointerenter (hover) over the trigger", () => {
    renderTooltip();
    const trigger = screen.getByTestId("trigger");
    act(() => {
      fireEvent.pointerEnter(trigger);
    });
    expect(screen.getByTestId("content")).toBeInTheDocument();
  });

  it("opens on focus over the trigger", () => {
    renderTooltip();
    const trigger = screen.getByTestId("trigger");
    act(() => {
      fireEvent.focus(trigger);
    });
    expect(screen.getByTestId("content")).toBeInTheDocument();
  });

  it("closes on pointerleave from the trigger (no grace path into content)", () => {
    renderTooltip({ defaultOpen: true });
    const trigger = screen.getByTestId("trigger");
    act(() => {
      fireEvent.pointerLeave(trigger, { relatedTarget: document.body });
    });
    expect(screen.queryByTestId("content")).toBeNull();
  });

  it("closes on Escape", () => {
    renderTooltip({ defaultOpen: true });
    act(() => {
      fireEvent.keyDown(document, { key: "Escape" });
    });
    expect(screen.queryByTestId("content")).toBeNull();
  });

  it("closes on blur from the trigger", () => {
    renderTooltip({ defaultOpen: true });
    const trigger = screen.getByTestId("trigger");
    act(() => {
      fireEvent.blur(trigger, { relatedTarget: document.body });
    });
    expect(screen.queryByTestId("content")).toBeNull();
  });

  it("wires aria-describedby from trigger to content when open", () => {
    renderTooltip({ defaultOpen: true });
    const trigger = screen.getByTestId("trigger");
    const content = screen.getByTestId("content");
    const id = content.getAttribute("id");
    expect(id).toBeTruthy();
    expect(trigger).toHaveAttribute("aria-describedby", id);
  });

  it("does NOT set aria-describedby when closed", () => {
    renderTooltip();
    const trigger = screen.getByTestId("trigger");
    expect(trigger).not.toHaveAttribute("aria-describedby");
  });

  it("fires onOpenChange on uncontrolled open", () => {
    const spy = vi.fn();
    renderTooltip({ onOpenChange: spy });
    const trigger = screen.getByTestId("trigger");
    act(() => {
      fireEvent.pointerEnter(trigger);
    });
    expect(spy).toHaveBeenCalledWith(true);
  });

  it("respects disabled — pointerenter does not open", () => {
    renderTooltip({ disabled: true });
    const trigger = screen.getByTestId("trigger");
    act(() => {
      fireEvent.pointerEnter(trigger);
    });
    expect(screen.queryByTestId("content")).toBeNull();
  });

  it("disabled root still respects onOpenChange not firing on hover", () => {
    const spy = vi.fn();
    renderTooltip({ disabled: true, onOpenChange: spy });
    const trigger = screen.getByTestId("trigger");
    act(() => {
      fireEvent.pointerEnter(trigger);
    });
    expect(spy).not.toHaveBeenCalled();
  });

  it("controlled open prop overrides internal state", () => {
    const { rerender } = renderTooltip({ open: false });
    const trigger = screen.getByTestId("trigger");
    act(() => {
      fireEvent.pointerEnter(trigger);
    });
    expect(screen.queryByTestId("content")).toBeNull();
    rerender(
      <${name} open={true}>
        <${name}.Trigger data-testid="trigger">Open</${name}.Trigger>
        <${name}.Content data-testid="content">Help text</${name}.Content>
      </${name}>,
    );
    expect(screen.getByTestId("content")).toBeInTheDocument();
  });

  it("pointerleave INTO content does not close (grace path)", () => {
    renderTooltip({ defaultOpen: true });
    const trigger = screen.getByTestId("trigger");
    const content = screen.getByTestId("content");
    act(() => {
      fireEvent.pointerLeave(trigger, { relatedTarget: content });
    });
    // Surface should stay open because the pointer moved into the content.
    expect(screen.queryByTestId("content")).toBeInTheDocument();
  });

  it("closeOnEscape={false} prevents Escape dismissal", () => {
    renderTooltip({ defaultOpen: true, closeOnEscape: false });
    act(() => {
      fireEvent.keyDown(document, { key: "Escape" });
    });
    expect(screen.queryByTestId("content")).toBeInTheDocument();
  });

  it("closeOnBlur={false} prevents blur dismissal", () => {
    renderTooltip({ defaultOpen: true, closeOnBlur: false });
    const trigger = screen.getByTestId("trigger");
    act(() => {
      fireEvent.blur(trigger, { relatedTarget: document.body });
    });
    expect(screen.queryByTestId("content")).toBeInTheDocument();
  });

  it("unmount removes document-level listeners (no setOpen after unmount)", () => {
    const spy = vi.fn();
    const { unmount } = renderTooltip({ defaultOpen: true, onOpenChange: spy });
    unmount();
    // Document-level Escape listener should be torn down; firing it now
    // must not invoke setOpen on the unmounted instance.
    act(() => {
      fireEvent.keyDown(document, { key: "Escape" });
    });
    expect(spy).not.toHaveBeenCalled();
  });
});

describe("${name} — asChild adoption", () => {
  it("renders the adopted child as the actual host (no nested button)", () => {
    render(
      <${name}>
        <${name}.Trigger asChild>
          <a href="#help" data-testid="trigger">Help</a>
        </${name}.Trigger>
        <${name}.Content data-testid="content">Help text</${name}.Content>
      </${name}>,
    );
    const trigger = screen.getByTestId("trigger");
    expect(trigger.tagName).toBe("A");
    // No default <button> host was rendered alongside it.
    expect(trigger.parentElement?.querySelector("button")).toBeNull();
  });

  it("default-host behavior is unchanged when asChild is absent", () => {
    render(
      <${name}>
        <${name}.Trigger data-testid="trigger">Open</${name}.Trigger>
        <${name}.Content data-testid="content">Help text</${name}.Content>
      </${name}>,
    );
    expect(screen.getByTestId("trigger").tagName).toBe("BUTTON");
  });

  it("asChild opens on pointerenter over the adopted child", () => {
    render(
      <${name}>
        <${name}.Trigger asChild>
          <a href="#help" data-testid="trigger">Help</a>
        </${name}.Trigger>
        <${name}.Content data-testid="content">Help text</${name}.Content>
      </${name}>,
    );
    act(() => {
      fireEvent.pointerEnter(screen.getByTestId("trigger"));
    });
    expect(screen.getByTestId("content")).toBeInTheDocument();
  });

  it("asChild opens on focus over the adopted child", () => {
    render(
      <${name}>
        <${name}.Trigger asChild>
          <a href="#help" data-testid="trigger">Help</a>
        </${name}.Trigger>
        <${name}.Content data-testid="content">Help text</${name}.Content>
      </${name}>,
    );
    act(() => {
      fireEvent.focus(screen.getByTestId("trigger"));
    });
    expect(screen.getByTestId("content")).toBeInTheDocument();
  });

  it("asChild wires aria-describedby onto the adopted child when open", () => {
    render(
      <${name} defaultOpen>
        <${name}.Trigger asChild>
          <a href="#help" data-testid="trigger">Help</a>
        </${name}.Trigger>
        <${name}.Content data-testid="content">Help text</${name}.Content>
      </${name}>,
    );
    const trigger = screen.getByTestId("trigger");
    const content = screen.getByTestId("content");
    expect(trigger).toHaveAttribute("aria-describedby", content.getAttribute("id"));
  });

  it("asChild preserves the consumer's onPointerEnter handler", () => {
    const consumerSpy = vi.fn();
    const surfaceSpy = vi.fn();
    render(
      <${name} onOpenChange={surfaceSpy}>
        <${name}.Trigger asChild>
          <a href="#help" data-testid="trigger" onPointerEnter={consumerSpy}>
            Help
          </a>
        </${name}.Trigger>
        <${name}.Content data-testid="content">Help text</${name}.Content>
      </${name}>,
    );
    act(() => {
      fireEvent.pointerEnter(screen.getByTestId("trigger"));
    });
    expect(consumerSpy).toHaveBeenCalled();
    expect(surfaceSpy).toHaveBeenCalledWith(true);
  });

  it("asChild preserves the consumer's onFocus handler", () => {
    const consumerSpy = vi.fn();
    render(
      <${name}>
        <${name}.Trigger asChild>
          <a href="#help" data-testid="trigger" onFocus={consumerSpy}>
            Help
          </a>
        </${name}.Trigger>
        <${name}.Content data-testid="content">Help text</${name}.Content>
      </${name}>,
    );
    act(() => {
      fireEvent.focus(screen.getByTestId("trigger"));
    });
    expect(consumerSpy).toHaveBeenCalled();
  });

  it("asChild — consumer event.preventDefault() suppresses the surface handler", () => {
    const surfaceSpy = vi.fn();
    render(
      <${name} onOpenChange={surfaceSpy}>
        <${name}.Trigger asChild>
          <a
            href="#help"
            data-testid="trigger"
            onPointerEnter={(e) => e.preventDefault()}
          >
            Help
          </a>
        </${name}.Trigger>
        <${name}.Content data-testid="content">Help text</${name}.Content>
      </${name}>,
    );
    act(() => {
      fireEvent.pointerEnter(screen.getByTestId("trigger"));
    });
    expect(surfaceSpy).not.toHaveBeenCalled();
    expect(screen.queryByTestId("content")).toBeNull();
  });

  it("asChild forwards the consumer's ref to the adopted DOM node", () => {
    const consumerRef = createRef<HTMLAnchorElement>();
    render(
      <${name}>
        <${name}.Trigger asChild>
          <a href="#help" data-testid="trigger" ref={consumerRef}>
            Help
          </a>
        </${name}.Trigger>
        <${name}.Content data-testid="content">Help text</${name}.Content>
      </${name}>,
    );
    expect(consumerRef.current).not.toBeNull();
    expect(consumerRef.current?.tagName).toBe("A");
  });

  it("asChild throws when no child is provided", () => {
    // React.Children.only logs an internal error and rethrows; we
    // catch the throw at render time.
    const consoleErrorSpy = vi
      .spyOn(console, "error")
      .mockImplementation(() => {});
    expect(() =>
      render(
        <${name}>
          <${name}.Trigger asChild>{null}</${name}.Trigger>
          <${name}.Content data-testid="content">Help text</${name}.Content>
        </${name}>,
      ),
    ).toThrow();
    consoleErrorSpy.mockRestore();
  });

  it("asChild throws when multiple children are provided", () => {
    const consoleErrorSpy = vi
      .spyOn(console, "error")
      .mockImplementation(() => {});
    expect(() =>
      render(
        <${name}>
          <${name}.Trigger asChild>
            <a href="#a">A</a>
            <a href="#b">B</a>
          </${name}.Trigger>
          <${name}.Content data-testid="content">Help text</${name}.Content>
        </${name}>,
      ),
    ).toThrow();
    consoleErrorSpy.mockRestore();
  });

  it("asChild throws when child is a string (not a valid element)", () => {
    // React.Children.only rejects strings up front; we don't need to
    // reach our own isValidElement guard. Either message is acceptable
    // as long as render() throws loudly.
    const consoleErrorSpy = vi
      .spyOn(console, "error")
      .mockImplementation(() => {});
    expect(() =>
      render(
        <${name}>
          <${name}.Trigger asChild>Help text</${name}.Trigger>
          <${name}.Content data-testid="content">Help text</${name}.Content>
        </${name}>,
      ),
    ).toThrow();
    consoleErrorSpy.mockRestore();
  });

  it("asChild applies the data-${cssPrefix}-trigger marker to the adopted host", () => {
    render(
      <${name}>
        <${name}.Trigger asChild>
          <a href="#help" data-testid="trigger">Help</a>
        </${name}.Trigger>
        <${name}.Content data-testid="content">Help text</${name}.Content>
      </${name}>,
    );
    expect(screen.getByTestId("trigger")).toHaveAttribute("data-${cssPrefix}-trigger");
  });
});

describe("${name} — accessibility", () => {
  it("has no unexpected axe violations when closed", async () => {
    const { container } = renderTooltip();
    const results = (await axe(container)) as unknown as { violations: Array<{ id: string }> };
    expect(results.violations.map((v) => v.id)).toEqual([]);
  });

  it("has no unexpected axe violations when open", async () => {
    const { container } = renderTooltip({ defaultOpen: true });
    const results = (await axe(container)) as unknown as { violations: Array<{ id: string }> };
    expect(results.violations.map((v) => v.id)).toEqual([]);
  });
});`;

  return [
    `// @generated:start imports`,
    importsBody,
    `// @generated:end`,
    ``,
    `// @generated:start tests`,
    testsBody,
    `// @generated:end`,
    ``,
    `// @custom:start tests`,
    ``,
    `// @custom:end`,
    ``,
  ].join("\n");
}
