// packages/ds-vue/src/components/Postcard/Postcard.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type PostcardAuthor = { name: string; handle: string; avatar: string };
export type PostcardStats = { likes: number; replies: number; reposts: number };
export type PostcardEmbed = { type: 'image' | 'video' | 'audio'; url: string; aspectRatio: { width: number; height: number } };
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  postId: string;
  author: PostcardAuthor;
  timestamp: string;
  stats: PostcardStats;
  embed?: PostcardEmbed;
  type?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "postcard",
  props.type ? `postcard--${props.type}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <article :class="classNames" :data-testid="props['data-testid']">
    <div :class="'postcard__header'">
      <div :class="'postcard__userInfo'">
        <span :class="'postcard__displayName'"></span>
        <span :class="'postcard__handle'"></span>
      </div>
      <time :class="'postcard__timestamp'"></time>
    </div>
    <div :class="'postcard__content'">
      <slot />
    </div>
    <div :class="'postcard__footer'">
      <div :class="'postcard__stats'">
        <span :class="'postcard__stat'"></span>
      </div>
    </div>
  </article>
</template>

// packages/ds-react/src/components/Postcard/Postcard.tsx
// @generated:start imports
import { type ReactNode } from "react";
import { Stack } from "../../primitives";
import "./Postcard.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type PostcardAuthor = { name: string; handle: string; avatar: string };

export type PostcardStats = { likes: number; replies: number; reposts: number };

export type PostcardEmbed = { type: 'image' | 'video' | 'audio'; url: string; aspectRatio: { width: number; height: number } };
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface PostcardProps {
  postId: string;
  author: PostcardAuthor;
  timestamp: string;
  stats: PostcardStats;
  embed?: PostcardEmbed;
  type?: string;
  className?: string;
  "data-testid"?: string;
  children?: ReactNode;
}
// @generated:end

// @generated:start subcomponents
export interface PostcardHeaderProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function PostcardHeader({
  children,
  className,
  "data-testid": testId,
}: PostcardHeaderProps) {
  const classNames = ["postcard__header", className].filter(Boolean).join(" ");
  return (
    <Stack as="header" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface PostcardContentProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function PostcardContent({
  children,
  className,
  "data-testid": testId,
}: PostcardContentProps) {
  const classNames = ["postcard__content", className].filter(Boolean).join(" ");
  return (
    <Stack className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface PostcardFooterProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function PostcardFooter({
  children,
  className,
  "data-testid": testId,
}: PostcardFooterProps) {
  const classNames = ["postcard__footer", className].filter(Boolean).join(" ");
  return (
    <Stack as="footer" variant="horizontal" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}
// @generated:end

// @generated:start component
export function Postcard({
  type,
  className,
  "data-testid": testId,
  children,
  postId,
  author,
  timestamp,
  stats,
  embed,
  ...rest
}: PostcardProps) {
  const classNames = [
    "postcard",
    type && `postcard--${type}`,
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <article className={`${classNames}`} data-testid={testId} {...rest}>
    <div className="postcard__header">
      <div className="postcard__userInfo">
        <span className="postcard__displayName" />
        <span className="postcard__handle" />
      </div>
      <time className="postcard__timestamp" />
    </div>
    <div className="postcard__content">
      {children}
    </div>
    <div className="postcard__footer">
      <div className="postcard__stats">
        <span className="postcard__stat" />
      </div>
    </div>
  </article>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end
