// packages/ds-vue/src/components/Table/TableRow.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  class?: string;
  dataTestid?: string;
  id?: string;
  style?: string;
}

const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const classNames = computed(() =>
  ["table__row", props.class].filter(Boolean).join(" "),
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <tr :class="classNames" :data-testid="props.dataTestid" :id="props.id" :style="props.style">
    <slot />
  </tr>
</template>

// packages/ds-svelte/src/components/Table/TableRow.svelte
<script lang="ts">
// @generated:start imports

// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  class?: string;
  "data-testid"?: string;
  children?: import('svelte').Snippet;
  id?: string;
  style?: string;
}

let { class: className, "data-testid": dataTestid, children, id, style }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(["table__row", className].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<tr class={classes} data-testid={dataTestid} {id} {style}>
  {@render children?.()}
</tr>
