// packages/ds-svelte/src/components/Stat/Stat.svelte
<script lang="ts">
// @generated:start imports

// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type StatSize = "sm" | "md" | "lg";
type StatTrend = "up" | "down" | "neutral";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  size?: StatSize;
  trend?: StatTrend;
  class?: string;
  children?: import('svelte').Snippet;
}

let { size = "md", trend, class: className, children }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "stat",
    size ? `stat--${size}` : null,
    trend ? `stat--${trend}` : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} data-fsds-component="stat" data-fsds-box="">
  {@render children?.()}
</div>

// packages/ds-angular/src/components/Stat/Stat.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass } from "@angular/common";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type StatSize = "sm" | "md" | "lg";
export type StatTrend = "up" | "down" | "neutral";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-stat",
  standalone: true,
  imports: [NgClass],
  host: { "data-fsds-component": "stat" },
  template: `<div [ngClass]="classes()" data-fsds-box="">
  <ng-content />
</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class StatComponent {
  @Input() size?: StatSize = "md";
  @Input() trend?: StatTrend;
  @Input() class?: string;

  classes(): string {
    return [
      "stat",
      (this.size ?? "md") ? `stat--${(this.size ?? "md")}` : null,
      this.trend ? `stat--${this.trend}` : null,
      this.class,
    ].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end
