// packages/ds-vue/src/components/Input/Input.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useFieldAssociation } from "../../primitives/index.js";
import { useInput } from "./useInput.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  type?: string;
  value?: string;
  defaultValue?: string;
  onChange?: (value: string) => void;
  placeholder?: string;
  disabled?: boolean;
  invalid?: boolean;
  required?: boolean;
  name?: string;
  ariaLabel?: string;
  ariaLabelledby?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  disabled: undefined,
  invalid: undefined,
  required: undefined,
});
// @generated:end

// @generated:start hook
const behavior = useInput({
  value: () => props.value,
  defaultValue: props.defaultValue,
  onChange: props.onChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "input",
  props.disabled ? "input--disabled" : null,
  props.invalid ? "input--invalid" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @generated:start fieldAssociation
const fieldAssociation = useFieldAssociation();
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <input :class="classNames" @input="(e) => behavior.setValue((e.target as HTMLInputElement).value)" :type="props.type" :value="behavior.value.value" :disabled="props.disabled" :aria-invalid="props.invalid" :placeholder="props.placeholder" :name="props.name" :required="props.required" :aria-label="props.ariaLabel" :aria-labelledby="props.ariaLabelledby" :id="fieldAssociation?.controlId" :aria-describedby="fieldAssociation?.describedBy" :data-testid="props['data-testid']" data-fsds-component="input" data-fsds-box="" />
</template>

// packages/ds-angular/src/components/Input/Input.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass } from "@angular/common";
import { useInput } from "./useInput.js";
import { FieldAssociationService } from "../../primitives/index.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-input",
  standalone: true,
  imports: [NgClass],
  host: { "data-fsds-component": "input" },
  template: `<input [ngClass]="classes()" (input)="handleValueChange($event)" [value]="behavior.value()" [disabled]="disabled" [attr.aria-invalid]="invalid" [type]="type" [placeholder]="placeholder" [name]="name" [required]="required" [attr.aria-label]="ariaLabel" [attr.aria-labelledby]="ariaLabelledby" [attr.id]="fieldAssociation?.current?.controlId" [attr.aria-describedby]="fieldAssociation?.current?.describedBy" data-fsds-box="" />`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class InputComponent {
  @Input() type?: string;
  @Input() value?: string;
  @Input() defaultValue?: string;
  @Input() onChange?: (value: string) => void;
  @Input() placeholder?: string;
  @Input() disabled?: boolean;
  @Input() invalid?: boolean;
  @Input() required?: boolean;
  @Input() name?: string;
  @Input() ariaLabel?: string;
  @Input() ariaLabelledby?: string;
  @Input() class?: string;
  protected fieldAssociation = inject(FieldAssociationService, { optional: true });

  private destroyRef = inject(DestroyRef);
  protected behavior = useInput({
    value: () => this.value,
    defaultValue: this.defaultValue,
    onChange: (v) => this.onChange?.(v),
    destroyRef: this.destroyRef,
  });

  classes = computed(() =>
    [
      "input",
      this.disabled ? "input--disabled" : null,
      this.invalid ? "input--invalid" : null,
      this.class,
    ].filter(Boolean).join(" "),
  );

  protected handleValueChange(event: Event): void {
    this.behavior.setValue((event.target as HTMLInputElement).value);
  }
}
// @generated:end

// @custom:start trailing

// @custom:end
