// packages/ds-vue/src/components/ShowMore/ShowMore.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useShowMore } from "./useShowMore.js";
import { canActivateInteraction } from "../../primitives/interaction.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  expanded?: boolean;
  defaultExpanded?: boolean;
  onExpandedChange?: (expanded: boolean) => void;
  maxLines?: number;
  showMoreLabel?: string;
  showLessLabel?: string;
  class?: string;
  dataTestid?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  expanded: undefined,
  defaultExpanded: undefined,
  maxLines: 3,
  showMoreLabel: "Show more",
  showLessLabel: "Show less",
});
// @generated:end

// @generated:start hook
const behavior = useShowMore({
  expanded: () => props.expanded,
  defaultExpanded: props.defaultExpanded,
  onExpandedChange: props.onExpandedChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "show-more",
  behavior.expanded.value ? "show-more--expanded" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" :data-testid="props.dataTestid" data-fsds-component="show-more" data-fsds-box="">
    <div :class="'show-more__content'" :style="{ '--fsds-show-more-content-max-lines': props.maxLines }">
      <slot />
    </div>
    <button :class="'show-more__trigger'" type="button" @click="(e: MouseEvent) => { if (canActivateInteraction(e, false)) behavior.setExpanded(!behavior.expanded.value); }" :aria-expanded="behavior.expanded.value">
      {{ (behavior.expanded.value ? props.showLessLabel : props.showMoreLabel) }}
    </button>
  </div>
</template>

// packages/ds-angular/src/components/ShowMore/ShowMore.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass } from "@angular/common";
import { StackComponent } from "../../primitives/index.js";
import { useShowMore } from "./useShowMore.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-show-more",
  standalone: true,
  imports: [NgClass],
  host: { "data-fsds-component": "show-more" },
  template: `<div [ngClass]="classes()" data-fsds-box="">
  <div [ngClass]="'show-more__content'" [style.--fsds-show-more-content-max-lines]="(maxLines ?? 3)">
    <ng-content />
  </div>
  <button [ngClass]="'show-more__trigger'" type="button" (click)="behavior.setExpanded(!behavior.expanded())" [attr.aria-expanded]="behavior.expanded()">
    {{ (behavior.expanded() ? (showLessLabel ?? 'Show less') : (showMoreLabel ?? 'Show more')) }}
  </button>
</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ShowMoreComponent {
  @Input() expanded?: boolean;
  @Input() defaultExpanded?: boolean;
  @Input() onExpandedChange?: (expanded: boolean) => void;
  @Input() maxLines?: number = 3;
  @Input() showMoreLabel?: string = "Show more";
  @Input() showLessLabel?: string = "Show less";
  @Input() class?: string;

  private destroyRef = inject(DestroyRef);
  protected behavior = useShowMore({
    expanded: () => this.expanded,
    defaultExpanded: this.defaultExpanded,
    onExpandedChange: (v) => this.onExpandedChange?.(v),
    destroyRef: this.destroyRef,
  });

  classes = computed(() =>
    [
      "show-more",
      this.behavior.expanded() ? "show-more--expanded" : null,
      this.class,
    ].filter(Boolean).join(" "),
  );
}

@Component({
  selector: "fsds-show-more-content",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ShowMoreContentComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["show-more__content", this.class].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-show-more-trigger",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="button" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ShowMoreTriggerComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["show-more__trigger", this.class].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end
