// packages/ds-vue/src/components/Accordion/AccordionTrigger.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useAccordionContext } from "./useAccordion.js";
import Icon from "../Icon/Icon.vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  value: string;
  class?: string;
  dataTestid?: string;
}

const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const ctx = useAccordionContext();

const isOpen = computed(() => ctx.isItemOpen(props.value));

const classNames = computed(() =>
  [
    "accordion__trigger",
    isOpen.value && "accordion__trigger--open",
    props.class,
  ]
    .filter(Boolean)
    .join(" "),
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <h3 class="accordion__header">
    <button
      type="button"
      :class="classNames"
      data-disclosure-trigger
      :data-value="props.value"
      :id="`${ctx.idBase}-trigger-${props.value}`"
      :aria-controls="`${ctx.idBase}-content-${props.value}`"
      :aria-expanded="isOpen"
      :disabled="ctx.disabled"
      :data-testid="props.dataTestid"
      @click="ctx.toggleItem(props.value)"
    >
      <slot />
      <Icon :class="'accordion__chevron'" name="chevron-down" size="sm" />
    </button>
  </h3>
</template>

// packages/ds-svelte/src/components/Accordion/AccordionTrigger.svelte
<script lang="ts">
// @generated:start imports
import { useAccordionContext } from "./useAccordion.svelte.js";
import Icon from "../Icon/Icon.svelte";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  value: string;
  class?: string;
  "data-testid"?: string;
  children?: import('svelte').Snippet;
}

let { value, class: className, "data-testid": dataTestid, children }: Props = $props();
// @generated:end

// @generated:start classes
const ctx = useAccordionContext();

const isOpen = $derived(ctx.isItemOpen(value));

const classes = $derived(
  [
    "accordion__trigger",
    isOpen && "accordion__trigger--open",
    className,
  ]
    .filter(Boolean)
    .join(" "),
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<h3 class="accordion__header">
<button
  type="button"
  class={classes}
  data-disclosure-trigger=""
  data-value={value}
  id="{ctx.idBase}-trigger-{value}"
  aria-controls="{ctx.idBase}-content-{value}"
  aria-expanded={isOpen}
  disabled={ctx.disabled}
  data-testid={dataTestid}
  onclick={() => ctx.toggleItem(value)}
>
  {@render children?.()}
  <Icon class={'accordion__chevron'} name="chevron-down" size="sm" />
</button>
</h3>
