// packages/ds-svelte/src/components/Checkbox/Checkbox.svelte
<script lang="ts">
// @generated:start imports
import { useCheckbox } from "./useCheckbox.svelte.js";
import { useFieldAssociation } from "../../primitives/index.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type CheckboxSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  size?: CheckboxSize;
  checked?: boolean;
  defaultChecked?: boolean;
  onChange?: (checked: boolean) => void;
  indeterminate?: boolean;
  disabled?: boolean;
  name?: string;
  value?: string;
  ariaLabel?: string;
  ariaLabelledby?: string;
  class?: string;
}

let { size = "md", checked, defaultChecked, onChange, indeterminate, disabled, name, value, ariaLabel, ariaLabelledby, class: className }: Props = $props();
// @generated:end

// @generated:start hook
const behavior = useCheckbox({
  checked: () => checked,
  defaultChecked: () => defaultChecked,
  onChange: () => onChange,
});
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "checkbox",
    size ? `checkbox--${size}` : null,
    behavior.checked ? "checkbox--checked" : null,
    disabled ? "checkbox--disabled" : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @generated:start fieldAssociation
const fieldAssociation = useFieldAssociation();
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<label class={classes} data-fsds-component="checkbox" data-fsds-box="">
  <input class={'checkbox__input'} type="checkbox" onchange={(e) => behavior.setChecked((e.currentTarget as HTMLInputElement).checked)} checked={behavior.checked} disabled={disabled} name={name} value={value} aria-label={ariaLabel} aria-labelledby={ariaLabelledby} aria-checked={(indeterminate ? "mixed" : behavior.checked)} indeterminate={indeterminate} id={fieldAssociation?.().controlId} aria-describedby={fieldAssociation?.().describedBy} />
  <span class={'checkbox__indicator'} aria-hidden="true"></span>
</label>

// packages/ds-vue/src/components/Checkbox/Checkbox.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useFieldAssociation } from "../../primitives/index.js";
import { useCheckbox } from "./useCheckbox.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type CheckboxSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  size?: CheckboxSize;
  checked?: boolean;
  defaultChecked?: boolean;
  onChange?: (checked: boolean) => void;
  indeterminate?: boolean;
  disabled?: boolean;
  name?: string;
  value?: string;
  ariaLabel?: string;
  ariaLabelledby?: string;
  class?: string;
  dataTestid?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  size: "md",
  checked: undefined,
  defaultChecked: undefined,
  indeterminate: undefined,
  disabled: undefined,
});
// @generated:end

// @generated:start hook
const behavior = useCheckbox({
  checked: () => props.checked,
  defaultChecked: props.defaultChecked,
  onChange: props.onChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "checkbox",
  props.size ? `checkbox--${props.size}` : null,
  behavior.checked.value ? "checkbox--checked" : null,
  props.disabled ? "checkbox--disabled" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @generated:start fieldAssociation
const fieldAssociation = useFieldAssociation();
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <label :class="classNames" :data-testid="props.dataTestid" data-fsds-component="checkbox" data-fsds-box="">
    <input :class="'checkbox__input'" type="checkbox" @change="(e) => behavior.setChecked((e.target as HTMLInputElement).checked)" :checked="behavior.checked.value" :disabled="props.disabled" :name="props.name" :value="props.value" :aria-label="props.ariaLabel" :aria-labelledby="props.ariaLabelledby" :aria-checked="(props.indeterminate ? 'mixed' : behavior.checked.value)" :indeterminate="props.indeterminate" :id="fieldAssociation?.controlId" :aria-describedby="fieldAssociation?.describedBy" />
    <span :class="'checkbox__indicator'" aria-hidden="true"></span>
  </label>
</template>
