// packages/ds-svelte/src/components/ShowMore/ShowMore.svelte
<script lang="ts">
// @generated:start imports
import { canActivateInteraction } from "../../primitives/interaction.js";
import { useShowMore } from "./useShowMore.svelte.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  expanded?: boolean;
  defaultExpanded?: boolean;
  onExpandedChange?: (expanded: boolean) => void;
  maxLines?: number;
  showMoreLabel?: string;
  showLessLabel?: string;
  class?: string;
  children?: import('svelte').Snippet;
}

let { expanded, defaultExpanded, onExpandedChange, maxLines = 3, showMoreLabel = "Show more", showLessLabel = "Show less", class: className, children }: Props = $props();
// @generated:end

// @generated:start hook
const behavior = useShowMore({
  expanded: () => expanded,
  defaultExpanded: () => defaultExpanded,
  onExpandedChange: () => onExpandedChange,
});
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "show-more",
    behavior.expanded ? "show-more--expanded" : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} data-fsds-component="show-more" data-fsds-box="">
  <div class={'show-more__content'} style:--fsds-show-more-content-max-lines={maxLines}>
    {@render children?.()}
  </div>
  <button class={'show-more__trigger'} type="button" onclick={(e) => { if (canActivateInteraction(e, false)) behavior.setExpanded(!behavior.expanded); }} aria-expanded={behavior.expanded}>{(behavior.expanded ? showLessLabel : showMoreLabel)}</button>
</div>

// packages/ds-vue/src/components/ShowMore/ShowMore.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useShowMore } from "./useShowMore.js";
import { canActivateInteraction } from "../../primitives/interaction.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  expanded?: boolean;
  defaultExpanded?: boolean;
  onExpandedChange?: (expanded: boolean) => void;
  maxLines?: number;
  showMoreLabel?: string;
  showLessLabel?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  expanded: undefined,
  defaultExpanded: undefined,
  maxLines: 3,
  showMoreLabel: "Show more",
  showLessLabel: "Show less",
});
// @generated:end

// @generated:start hook
const behavior = useShowMore({
  expanded: () => props.expanded,
  defaultExpanded: props.defaultExpanded,
  onExpandedChange: props.onExpandedChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "show-more",
  behavior.expanded.value ? "show-more--expanded" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" :data-testid="props['data-testid']" data-fsds-component="show-more" data-fsds-box="">
    <div :class="'show-more__content'" :style="{ '--fsds-show-more-content-max-lines': props.maxLines }">
      <slot />
    </div>
    <button :class="'show-more__trigger'" type="button" @click="(e: MouseEvent) => { if (canActivateInteraction(e, false)) behavior.setExpanded(!behavior.expanded.value); }" :aria-expanded="behavior.expanded.value">
      {{ (behavior.expanded.value ? props.showLessLabel : props.showMoreLabel) }}
    </button>
  </div>
</template>
