// packages/ds-react/src/components/ShowMore/ShowMore.tsx
// @generated:start imports
import { type ReactNode } from "react";
import { Stack } from "../../primitives";
import { useShowMore } from "./useShowMore";
import "./ShowMore.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface ShowMoreProps {
  expanded?: boolean;
  defaultExpanded?: boolean;
  onExpandedChange?: (expanded: boolean) => void;
  maxLines?: number;
  showMoreLabel?: string;
  showLessLabel?: string;
  className?: string;
  "data-testid"?: string;
  children?: ReactNode;
}
// @generated:end

// @generated:start subcomponents
export interface ShowMoreContentProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function ShowMoreContent({
  children,
  className,
  "data-testid": testId,
}: ShowMoreContentProps) {
  const classNames = ["show-more__content", className].filter(Boolean).join(" ");
  return (
    <Stack className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface ShowMoreTriggerProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function ShowMoreTrigger({
  children,
  className,
  "data-testid": testId,
}: ShowMoreTriggerProps) {
  const classNames = ["show-more__trigger", className].filter(Boolean).join(" ");
  return (
    <Stack as="button" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}
// @generated:end

// @generated:start component
export function ShowMore({
  expanded: controlledExpanded,
  defaultExpanded,
  onExpandedChange,
  className,
  "data-testid": testId,
  children,
  maxLines = 3,
  showMoreLabel = "Show more",
  showLessLabel = "Show less",
  ...rest
}: ShowMoreProps) {
  const { expanded, setExpanded } = useShowMore({
    expanded: controlledExpanded,
    defaultExpanded,
    onExpandedChange,
  });

  const classNames = [
    "show-more",
    expanded && "show-more--expanded",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <div className={`${classNames}`} data-testid={testId} {...rest}>
    <div className="show-more__content">
      {children}
    </div>
    <button className="show-more__trigger" type="button" aria-expanded={expanded} onClick={() => setExpanded(!expanded)}>
      {showMoreLabel}
    </button>
  </div>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/ShowMore/ShowMore.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useShowMore } from "./useShowMore.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  expanded?: boolean;
  defaultExpanded?: boolean;
  onExpandedChange?: (expanded: boolean) => void;
  maxLines?: number;
  showMoreLabel?: string;
  showLessLabel?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  maxLines: 3,
  showMoreLabel: "Show more",
  showLessLabel: "Show less",
});
// @generated:end

// @generated:start hook
const behavior = useShowMore({
  expanded: () => props.expanded,
  defaultExpanded: props.defaultExpanded,
  onExpandedChange: props.onExpandedChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "show-more",
  behavior.expanded.value ? "show-more--expanded" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" :data-testid="props['data-testid']">
    <div :class="'show-more__content'">
      <slot />
    </div>
    <button :class="'show-more__trigger'" type="button" :aria-expanded="behavior.expanded.value" @click="() => behavior.setExpanded(!behavior.expanded.value)">
      {{ props.showMoreLabel }}
    </button>
  </div>
</template>
