// packages/ds-codegen/src/frameworks/react/surface-emit.ts
/**
 * React emitter — Anchored Presence Surface path.
 *
 * Activated for any `ir.surface` with part attachment and anchored
 * positioning (per shared semantics policy). Emits the compound
 * API:
 *
 *   <Surface>
 *     <Surface.Trigger>...</Surface.Trigger>
 *     <Surface.Content>...</Surface.Content>
 *   </Surface>
 *
 * The emitter is data-driven on the AnchoredSurfacePolicy returned
 * by `resolveAnchoredSurfacePolicy` — Tooltip and Popover share the
 * same code path; only the contract differs (dismissal modes, anchor
 * relation, content role).
 *
 * Bypasses the legacy `ir.dom` and compound-state-container paths
 * entirely — this is forward-facing replacement, not augmentation.
 */
import type { ComponentIR, SurfaceIR } from "../../ir.js";
import {
  isPartAnchoredSurface,
  resolveAnchoredSurfacePolicy,
  type AnchoredSurfacePolicy,
  type PublicDismissalProp,
} from "../../semantics.js";

export function isSurfaceComponent(ir: ComponentIR): boolean {
  // Kind-aware like svelte/angular/lit: non-anchored kinds (dialog, sheet,
  // toast, …) may declare a surface taxonomy block for fact-tracking while
  // keeping the existing generic/hook emission path on web.
  return ir.surface !== undefined && isPartAnchoredSurface(ir.surface);
}

export function generateReactSurfaceComponentSource(ir: ComponentIR): string {
  const surface = ir.surface;
  if (!surface) {
    throw new Error(
      `generateReactSurfaceComponentSource called on ${ir.name} without ir.surface`,
    );
  }
  if (!isPartAnchoredSurface(surface)) {
    throw new Error(
      `React surface emitter expected part attachment with anchored positioning (got "${surface.kind}").`,
    );
  }
  const policy = resolveAnchoredSurfacePolicy(surface);
  return emitAnchoredSurfaceSource(ir, surface, policy);
}

function emitAnchoredSurfaceSource(
  ir: ComponentIR,
  surface: SurfaceIR,
  policy: AnchoredSurfacePolicy,
): string {
  const name = ir.name;
  const cssPrefix = ir.cssPrefix;
  const placementValues: string[] | undefined = ir.variants["placement"];
  const placementType = placementValues ? `${name}Placement` : "string";

  // Surface lookups
  const openTriggersList = JSON.stringify(surface.openTriggers);
  const anchorRelation = surface.anchor?.relation ?? "describedby";
  const ariaAttrForAnchor =
    anchorRelation === "describedby"
      ? "aria-describedby"
      : anchorRelation === "controls-expanded"
        ? "aria-controls"
        : anchorRelation === "labelledby"
          ? "aria-labelledby"
          : null;

  const placementTypeAlias = placementValues
    ? `export type ${placementType} = ${placementValues.map((v) => `"${v}"`).join(" | ")};\n`
    : "";

  // Positioning + portal are driven by the contract:
  //   - surface.positioning.strategy === "anchored" → emit
  //     useAnchoredPosition wiring on Content and apply position: fixed
  //   - behavior.portal.enabled === true            → wrap Content in
  //     createPortal targeting document.body
  // Both flags are independent: a contract can opt into anchored
  // positioning without portalling (the content stays in-tree but uses
  // fixed positioning), though Popover and Tooltip enable both.
  const positioningEnabled = surface.positioning?.strategy === "anchored";
  const portalEnabled = ir.behavior.portal?.enabled === true;
  const collision = surface.positioning?.collision ?? "flip-shift";

  const reactImports = [
    `type ReactNode`,
    `type HTMLAttributes`,
    `type ButtonHTMLAttributes`,
    `createContext`,
    `useContext`,
  ];
  const extraImportLines: string[] = [];
  if (portalEnabled) {
    extraImportLines.push(`import { createPortal } from "react-dom";`);
    extraImportLines.push(
      `import { usePortalTarget } from "../../primitives/hooks";`,
    );
  }
  if (positioningEnabled) {
    extraImportLines.push(
      `import { useAnchoredPosition } from "../../primitives/surfaces/useAnchoredPosition";`,
    );
  }

  const imports = [
    `import {`,
    ...reactImports.map((line) => `  ${line},`),
    `} from "react";`,
    `import { useAnchoredSurface, type SurfaceTriggerHandlers } from "../../primitives/surfaces/useAnchoredSurface";`,
    `import { bindInteractionHost } from "../../primitives/InteractionHost";`,
    ...extraImportLines,
    `import "./${name}.css";`,
  ].join("\n");

  // Policy-derived facts. The default content role and the public
  // dismissal-prop spec list now live in shared semantics
  // (AnchoredSurfacePolicy) — see docs/codegen-authority.md.
  const contentRole = policy.defaultContentRole;
  const dismissalProps = policy.publicDismissalProps.filter(
    (spec): spec is PublicDismissalProp & { prop: string } => spec.prop !== null,
  );

  // Stable types
  const typesBody = placementTypeAlias.trimEnd();

  // Compound props
  const closeOnPropLines = dismissalProps
    .map((spec) => `  ${spec.prop}?: boolean;`)
    .join("\n");
  const propsBody = `export interface ${name}Props {
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  placement?: ${placementType};
  disabled?: boolean;
${closeOnPropLines}
  className?: string;
  "data-testid"?: string;
  children?: ReactNode;
}

export interface ${name}TriggerProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  /**
   * Adopt the consumer's single child element as the trigger host
   * instead of rendering a default \`<button>\`. The adopted element
   * receives the merged ref, ARIA props, data marker, and surface
   * event handlers. Consumer event handlers run first; if they call
   * \`event.preventDefault()\` the surface handler is suppressed.
   */
  asChild?: boolean;
  children?: ReactNode;
}

export interface ${name}ContentProps extends HTMLAttributes<HTMLDivElement> {
  children?: ReactNode;
}`;

  // The compound context exposes the surface state to Trigger/Content.
  // Positioning-aware contexts also carry the live anchor/content nodes
  // and the resolved placement so Content can call useAnchoredPosition
  // without re-implementing the registration plumbing.
  const positioningContextLines = positioningEnabled
    ? `\n  anchorEl: HTMLElement | null;\n  contentEl: HTMLElement | null;\n  placement: ${placementType} | undefined;`
    : "";
  const contextBody = `interface ${name}ContextValue {
  open: boolean;
  contentId: string;
  ariaAttrForAnchor: ${ariaAttrForAnchor ? `"${ariaAttrForAnchor}"` : "null"};
  registerAnchor: (node: HTMLElement | null) => void;
  registerAnchorRefOnly: (node: HTMLElement | null) => void;
  registerContent: (node: HTMLElement | null) => void;
  getTriggerHandlers: () => SurfaceTriggerHandlers;${positioningContextLines}
}

const ${name}Context = createContext<${name}ContextValue | null>(null);
${name}Context.displayName = "${name}Context";

function use${name}Context(): ${name}ContextValue {
  const value = useContext(${name}Context);
  if (value === null) {
    throw new Error(
      "${name} compound component used outside of <${name}> provider.",
    );
  }
  return value;
}`;

  // Root component
  const destructuredCloseProps = dismissalProps
    .map((spec) => `  ${spec.prop} = ${spec.defaultValue},`)
    .join("\n");

  // Build the runtime dismissal array literal. Each declared
  // dismissal mode contributes one entry: gated by its closeOn* prop
  // when the policy says the mode is public + runtime-toggleable,
  // otherwise inlined as a string literal.
  const dismissalEntries = policy.publicDismissalProps
    .map((spec) =>
      spec.prop && spec.runtimeToggleable
        ? `${spec.prop} && "${spec.mode}"`
        : `"${spec.mode}"`,
    );
  const dismissalTypeUnion = policy.publicDismissalProps
    .map((spec) => `"${spec.mode}"`)
    .join(" | ");

  const rootBody = `export function ${name}({
  open,
  defaultOpen,
  onOpenChange,
  placement,
  disabled,
  className,
${destructuredCloseProps}
  "data-testid": testId,
  children,
}: ${name}Props) {
  const dismissal = [
    ${dismissalEntries.join(",\n    ")},
  ].filter(Boolean) as readonly (${dismissalTypeUnion})[];

  const surface = useAnchoredSurface({
    open,
    defaultOpen,
    onOpenChange,
    openTriggers: ${openTriggersList},
    dismissal,
    anchorRelation: "${anchorRelation}",
    disabled,
  });

  const classNames = [
    "${cssPrefix}",
    placement && \`${cssPrefix}--\${placement}\`,
    disabled && "${cssPrefix}--disabled",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <${name}Context.Provider
      value={{
        open: surface.open,
        contentId: surface.contentId,
        ariaAttrForAnchor: ${ariaAttrForAnchor ? `"${ariaAttrForAnchor}"` : "null"},
        registerAnchor: surface.registerAnchor,
        registerAnchorRefOnly: surface.registerAnchorRefOnly,
        registerContent: surface.registerContent,
        getTriggerHandlers: surface.getTriggerHandlers,${positioningEnabled ? `\n        anchorEl: surface.anchorEl,\n        contentEl: surface.contentEl,\n        placement,` : ""}
      }}
    >
      <span className={classNames} data-testid={testId}>
        {children}
      </span>
    </${name}Context.Provider>
  );
}`;

  // Trigger subcomponent (default host: <button>). aria wiring is
  // emitted to match the surface's anchorRelation exactly — dead
  // branches for other relations are deliberately omitted to keep tsc
  // narrowing clean.
  const triggerAriaProps = (() => {
    if (anchorRelation === "describedby") {
      // aria-describedby on the anchor references the content id only
      // when the surface is actually open; otherwise screen readers
      // would announce a non-rendered description.
      return `  const ariaProps = ctx.open
    ? { "aria-describedby": ctx.contentId }
    : {};`;
    }
    if (anchorRelation === "controls-expanded") {
      return `  const ariaProps = {
    "aria-controls": ctx.contentId,
    "aria-expanded": ctx.open,
  };`;
    }
    if (anchorRelation === "labelledby") {
      return `  const ariaProps = ctx.open
    ? { "aria-labelledby": ctx.contentId }
    : {};`;
    }
    return `  const ariaProps = {};`;
  })();

  const triggerBody = `${name}.Trigger = function ${name}Trigger({
  asChild,
  children,
  ...rest
}: ${name}TriggerProps) {
  const ctx = use${name}Context();
${triggerAriaProps}

  if (asChild) {
    return adoptChildAsTrigger({
      child: children,
      ctx,
      ariaProps,
      rest,
    });
  }

  return (
    <button
      type="button"
      ref={(node) => ctx.registerAnchor(node)}
      data-${cssPrefix}-trigger=""
      {...ariaProps}
      {...rest}
    >
      {children}
    </button>
  );
};

interface AdoptChildArgs {
  child: ReactNode;
  ctx: ${name}ContextValue;
  ariaProps: Record<string, unknown>;
  rest: Omit<${name}TriggerProps, "asChild" | "children">;
}

function adoptChildAsTrigger({ child, ctx, ariaProps, rest }: AdoptChildArgs) {
  return bindInteractionHost(child, rest, ariaProps, ctx.getTriggerHandlers() as Record<string, unknown>, {
    "data-${cssPrefix}-trigger": "",
    ref: ctx.registerAnchorRefOnly,
  });
}`;

  // Content subcomponent. For surfaces that declare a content role
  // (Tooltip emits role="tooltip"), the role is emitted as an
  // attribute. Popover-family surfaces omit the role — the contract
  // anchor.relation already supplies the semantic relationship via
  // aria-controls/aria-expanded on the trigger, and forcing a
  // role="dialog" would imply modal semantics that Popover does not
  // satisfy. Consumers wanting an explicit role can pass one via
  // `...rest`.
  const contentRoleAttr =
    contentRole !== null ? `\n      role="${contentRole}"` : "";

  // Positioning + portal wiring on the Content subcomponent.
  // - Positioning: call useAnchoredPosition with the anchor + content
  //   nodes already tracked by the surface. The hook returns
  //   { top, left, ready }; we apply fixed-position style on the div
  //   and hide it (visibility) until first measurement to avoid a
  //   flash at (0, 0). Passes collision strategy from the contract.
  // - Portal: when enabled, wrap the div in createPortal(node, document.body).
  //   Guard against SSR by checking typeof document; falls back to in-place
  //   render server-side, which positioning hooks will correct on hydration.
  const portalTargetHookCall = portalEnabled
    ? `\n  const portalTarget = usePortalTarget();`
    : "";
  const positioningHookCall = positioningEnabled
    ? `\n  const position = useAnchoredPosition({
    anchor: ctx.anchorEl,
    content: ctx.contentEl,
    open: ctx.open,
    placement: ctx.placement ?? "auto",
    collision: "${collision}",
    ${portalEnabled ? "boundary: portalTarget," : ""}
  });`
    : "";
  // Consumer style is spread first so our computed positioning wins.
  // Destructure rest.style out into a named local so consumers can still
  // pass style through (it merges with our computed top/left, with our
  // values taking precedence). The remaining rest spread (sans style)
  // attaches everything else verbatim.
  const positioningStyleProp = positioningEnabled
    ? `\n      style={{
        ...consumerStyle,
        position: "fixed",
        top: \`\${position.top}px\`,
        left: \`\${position.left}px\`,
        visibility: position.ready ? "visible" : "hidden",
      }}
      data-placement={position.placement}`
    : "";
  const restSpread = positioningEnabled
    ? "{...restWithoutStyle}"
    : "{...rest}";
  const restDestructure = positioningEnabled
    ? `\n  const { style: consumerStyle, ...restWithoutStyle } = rest;`
    : "";
  const contentDiv = `<div
      ref={(node) => ctx.registerContent(node)}
      id={ctx.contentId}${contentRoleAttr}${positioningStyleProp}
      data-${cssPrefix}-content=""
      ${restSpread}
    >
      {children}
    </div>`;
  const portalWrappedContent = portalEnabled
    ? `portalTarget !== null
    ? createPortal(
        ${contentDiv.split("\n").map((line) => `    ${line}`).join("\n").trim()},
        portalTarget,
      )
    : (
        ${contentDiv.split("\n").map((line) => `    ${line}`).join("\n").trim()}
      )`
    : `(\n    ${contentDiv}\n  )`;

  const contentBody = `${name}.Content = function ${name}Content({
  children,
  ...rest
}: ${name}ContentProps) {
  const ctx = use${name}Context();${portalTargetHookCall}${positioningHookCall}${restDestructure}
  if (!ctx.open) return null;
  return ${portalWrappedContent};
};`;

  return [
    `// @generated:start imports`,
    imports,
    `// @generated:end`,
    ``,
    `// @custom:start imports`,
    ``,
    `// @custom:end`,
    ``,
    `// @generated:start types`,
    typesBody,
    `// @generated:end`,
    ``,
    `// @custom:start types`,
    ``,
    `// @custom:end`,
    ``,
    `// @generated:start props`,
    propsBody,
    `// @generated:end`,
    ``,
    `// @generated:start context`,
    contextBody,
    `// @generated:end`,
    ``,
    `// @generated:start component`,
    rootBody,
    ``,
    triggerBody,
    ``,
    contentBody,
    `// @generated:end`,
    ``,
    `// @custom:start trailing`,
    ``,
    `// @custom:end`,
    ``,
  ].join("\n");
}

// packages/ds-codegen/src/frameworks/angular/surface-emit.ts
/**
 * Angular emitter — Anchored Presence Surface path.
 *
 * Activated for any contract whose IR has a `surface` block of an
 * anchored-presence kind (Tooltip, Popover, ...). Surface kind
 * eligibility is decided by `isPartAnchoredSurface` in shared
 * semantics, and per-kind policy (`AnchoredSurfacePolicy`) drives
 * default content role and public dismissal props. This emitter
 * MUST NOT branch on component identity or on `surface.kind` for
 * any rule that could be expressed by the policy.
 *
 * Emits the compound API:
 *
 *   <fsds-popover>
 *     <fsds-popover-trigger>Open</fsds-popover-trigger>          <!-- default-host -->
 *     <fsds-popover-content>Body</fsds-popover-content>
 *   </fsds-popover>
 *
 *   <fsds-popover>
 *     <a fsdsPopoverTrigger href="#open">Open</a>                <!-- adopted host -->
 *     <fsds-popover-content>Body</fsds-popover-content>
 *   </fsds-popover>
 *
 * Host adoption is **attribute-directive based**, Angular's native
 * idiom. The `[fsds<Name>Trigger]` directive inject(s) ElementRef +
 * the <Name>ContextToken; registers its host element as the anchor;
 * applies ARIA + data marker via @HostBinding; and lets the substrate
 * install open-trigger/dismissal DOM listeners directly on it.
 *
 * The default-host `<fsds-<name>-trigger>` component reuses the
 * directive internally on its own rendered <button>, so both modes
 * funnel through the same anchor-registration path.
 */
import type { ComponentIR, SurfaceIR } from "../../ir.js";
import {
  anchoredPortalsContentToBody,
  isPartAnchoredSurface,
  resolveAnchoredSurfacePolicy,
  type AnchoredSurfacePolicy,
  type PublicDismissalProp,
} from "../../semantics.js";

export interface AngularSurfaceFiles {
  rootComponent: string;
  triggerComponent: string;
  triggerDirective: string;
  contentComponent: string;
  composable: string;
}

export function isSurfaceComponent(ir: ComponentIR): boolean {
  return ir.surface !== undefined && isPartAnchoredSurface(ir.surface);
}

export function generateAngularSurfaceFiles(ir: ComponentIR): AngularSurfaceFiles {
  const surface = ir.surface;
  if (!surface) {
    throw new Error(
      `generateAngularSurfaceFiles called on ${ir.name} without ir.surface`,
    );
  }
  const policy = resolveAnchoredSurfacePolicy(surface);
  return {
    rootComponent: emitRootComponent(ir, surface, policy),
    triggerComponent: emitTriggerComponent(ir, surface),
    triggerDirective: emitTriggerDirective(ir, surface),
    contentComponent: emitContentComponent(ir, surface, policy),
    composable: emitComposable(ir, surface),
  };
}

function kebab(name: string): string {
  return name.replace(/([A-Z])/g, "-$1").toLowerCase().replace(/^-/, "");
}

function tagFor(name: string): string {
  return `fsds-${kebab(name)}`;
}

function emitRootComponent(
  ir: ComponentIR,
  surface: SurfaceIR,
  policy: AnchoredSurfacePolicy,
): string {
  const name = ir.name;
  const cssPrefix = ir.cssPrefix;
  const placementValues = ir.variants["placement"];
  const placementTypeAlias = placementValues
    ? `export type ${name}Placement = ${placementValues.map((v) => `"${v}"`).join(" | ")};\n`
    : "";
  const rootTag = tagFor(name);
  const openTriggers = JSON.stringify(surface.openTriggers);
  const anchorRelation = surface.anchor?.relation ?? "describedby";
  const positioningEnabled = surface.positioning?.strategy === "anchored";

  // Policy-derived dismissal-array assembly. For each declared
  // dismissal mode:
  //   - public + runtime-toggleable modes (escape, blur,
  //     outside-click) gate behind `this._<closeOnProp>() !== false`
  //     so toggling the @Input at runtime drives a substrate remount.
  //   - internal-only modes (pointer-leave, ...) are always-on.
  const dismissalParts = policy.publicDismissalProps.map((spec) =>
    spec.prop && spec.runtimeToggleable
      ? `this._${spec.prop}() !== false ? "${spec.mode}" as const : null`
      : `"${spec.mode}" as const`,
  );
  const dismissalExpr = dismissalParts.join(",\n      ");

  // Policy-derived public @Input + private signal mirror for each
  // consumer-facing dismissal flag. Entries with `prop: null` (e.g.
  // tooltip's pointer-leave) don't surface to the consumer.
  const publicDismissalProps = policy.publicDismissalProps.filter(
    (spec): spec is PublicDismissalProp & { prop: string } =>
      spec.prop !== null,
  );
  const closeOnInputLines = publicDismissalProps.map(
    (spec) => `  @Input() ${spec.prop}?: boolean;`,
  );
  const closeOnSignalLines = publicDismissalProps.map(
    (spec) => `  private _${spec.prop} = signal<boolean | undefined>(undefined);`,
  );
  // Each runtime-toggleable closeOn* @Input mirrors into its signal
  // and asks the substrate to remount so the new dismissal array
  // takes effect mid-life.
  const closeOnNgOnChangesBlocks = publicDismissalProps
    .filter((spec) => spec.runtimeToggleable)
    .flatMap((spec) => [
      `    if (changes["${spec.prop}"]) {`,
      `      this._${spec.prop}.set(this.${spec.prop});`,
      `      this.behavior?.requestRemount();`,
      `    }`,
    ]);

  return [
    `// @generated:start imports`,
    `import {`,
    `  Component,`,
    `  Input,`,
    `  OnChanges,`,
    `  OnInit,`,
    `  SimpleChanges,`,
    `  computed,`,
    `  signal,`,
    `  forwardRef,`,
    `  inject,`,
    `  DestroyRef,`,
    `  ChangeDetectionStrategy,`,
    `} from "@angular/core";`,
    `import { NgClass } from "@angular/common";`,
    `import { use${name}, ${name}ContextToken, type ${name}ContextValue } from "./use${name}.js";`,
    `// @generated:end`,
    ``,
    `// @custom:start imports`,
    ``,
    `// @custom:end`,
    ``,
    `// @generated:start types`,
    placementTypeAlias.trimEnd(),
    `// @generated:end`,
    ``,
    `// @custom:start types`,
    ``,
    `// @custom:end`,
    ``,
    `// @generated:start component`,
    `@Component({`,
    `  selector: "${rootTag}",`,
    `  standalone: true,`,
    `  imports: [NgClass],`,
    `  providers: [`,
    `    {`,
    `      provide: ${name}ContextToken,`,
    `      useFactory: () => {`,
    `        const self = inject(forwardRef(() => ${name}Component));`,
    `        const ctx: ${name}ContextValue = {`,
    `          get open() { return self.behavior.open; },`,
    `          setOpen: (v) => self.behavior.setOpen(v),`,
    `          get contentId() { return self.behavior.contentId; },`,
    `          anchorRelation: "${anchorRelation}",`,
    `          registerAnchor: (n) => self.behavior.registerAnchor(n),`,
    `          registerContent: (n) => self.behavior.registerContent(n),`,
    `          getAnchorNode: () => self.behavior.getAnchorNode(),`,
    `          getContentNode: () => self.behavior.getContentNode(),`,
    positioningEnabled ? `          getPlacement: () => self.placement,` : "",
    `        };`,
    `        return ctx;`,
    `      },`,
    `      deps: [],`,
    `    },`,
    `  ],`,
    `  template: \`<span [ngClass]="classes()"><ng-content /></span>\`,`,
    `  changeDetection: ChangeDetectionStrategy.OnPush,`,
    `})`,
    `export class ${name}Component implements OnChanges, OnInit {`,
    `  @Input() open?: boolean;`,
    `  @Input() defaultOpen?: boolean;`,
    `  @Input() onOpenChange?: (open: boolean) => void;`,
    placementValues ? `  @Input() placement?: ${name}Placement;` : "",
    `  @Input() disabled?: boolean;`,
    ...closeOnInputLines,
    `  @Input() class?: string;`,
    ``,
    `  // Signal mirrors of @Input values. The root owns its own`,
    `  // uncontrolled state here so we can seed it from defaultOpen in`,
    `  // ngOnInit (Angular sets @Input values after constructor but`,
    `  // before ngOnInit) without routing through onOpenChange.`,
    `  private _controlledOpen = signal<boolean | undefined>(undefined);`,
    `  private _uncontrolledOpen = signal<boolean>(false);`,
    `  private _disabled = signal<boolean>(false);`,
    ...closeOnSignalLines,
    ``,
    `  ngOnChanges(changes: SimpleChanges): void {`,
    `    if (changes["open"]) this._controlledOpen.set(this.open);`,
    `    if (changes["disabled"]) this._disabled.set(this.disabled === true);`,
    ...closeOnNgOnChangesBlocks,
    `  }`,
    ``,
    `  ngOnInit(): void {`,
    `    // Seed uncontrolled state from defaultOpen. Silent — does NOT`,
    `    // fire onOpenChange because we mutate the signal directly`,
    `    // instead of routing through the substrate's setOpen.`,
    `    if (this.defaultOpen === true && this.open === undefined) {`,
    `      this._uncontrolledOpen.set(true);`,
    `    }`,
    `  }`,
    ``,
    `  private destroyRef = inject(DestroyRef);`,
    `  // The substrate reads open via a unified getter that picks`,
    `  // controlled or uncontrolled. We pass defaultOpen=false (the`,
    `  // root component handles seeding in ngOnInit above).`,
    `  protected behavior = use${name}({`,
    `    open: () => {`,
    `      const controlled = this._controlledOpen();`,
    `      return controlled === undefined ? this._uncontrolledOpen() : controlled;`,
    `    },`,
    `    defaultOpen: false,`,
    `    onOpenChange: (v) => {`,
    `      // Substrate's setOpen routes through here. If we are`,
    `      // uncontrolled, mirror to our local signal too so future`,
    `      // open() reads pick up the change.`,
    `      if (this._controlledOpen() === undefined) this._uncontrolledOpen.set(v);`,
    `      this.onOpenChange?.(v);`,
    `    },`,
    `    openTriggers: () => ${openTriggers},`,
    `    dismissal: () => this._buildDismissal(),`,
    `    disabled: () => this._disabled(),`,
    `    destroyRef: this.destroyRef,`,
    `  });`,
    ``,
    `  private _buildDismissal() {`,
    `    return [`,
    `      ${dismissalExpr}`,
    `    ].filter((d): d is Exclude<typeof d, null> => d !== null);`,
    `  }`,
    ``,
    `  classes = computed(() =>`,
    `    [`,
    `      "${cssPrefix}",`,
    placementValues
      ? `      this.placement ? \`${cssPrefix}--\${this.placement}\` : null,`
      : "",
    `      this.disabled ? "${cssPrefix}--disabled" : null,`,
    `      this.class,`,
    `    ].filter(Boolean).join(" "),`,
    `  );`,
    `}`,
    `// @generated:end`,
    ``,
    `// @custom:start trailing`,
    ``,
    `// @custom:end`,
    ``,
  ]
    .filter((line) => line !== "")
    .join("\n");
}

function emitTriggerDirective(ir: ComponentIR, surface: SurfaceIR): string {
  const name = ir.name;
  const cssPrefix = ir.cssPrefix;
  const anchorRelation = surface.anchor?.relation ?? "describedby";

  // ARIA host bindings keyed on the anchor relation. The directive
  // applies these via @HostBinding so the consumer's element (or our
  // default <button>) gets the right ARIA reactively.
  const ariaHostBindings = (() => {
    if (anchorRelation === "describedby") {
      return [
        `  @HostBinding("attr.aria-describedby") get _ariaDescribedBy(): string | null {`,
        `    const ctx = this.ctx;`,
        `    return ctx && ctx.open() ? ctx.contentId : null;`,
        `  }`,
      ].join("\n");
    }
    if (anchorRelation === "controls-expanded") {
      return [
        `  @HostBinding("attr.aria-controls") get _ariaControls(): string | null {`,
        `    return this.ctx ? this.ctx.contentId : null;`,
        `  }`,
        ``,
        `  @HostBinding("attr.aria-expanded") get _ariaExpanded(): string | null {`,
        `    return this.ctx ? (this.ctx.open() ? "true" : "false") : null;`,
        `  }`,
      ].join("\n");
    }
    if (anchorRelation === "labelledby") {
      return [
        `  @HostBinding("attr.aria-labelledby") get _ariaLabelledBy(): string | null {`,
        `    const ctx = this.ctx;`,
        `    return ctx && ctx.open() ? ctx.contentId : null;`,
        `  }`,
      ].join("\n");
    }
    return `  // no ARIA host binding for anchor relation "${anchorRelation}"`;
  })();

  return [
    `// @generated:start imports`,
    `import {`,
    `  Directive,`,
    `  ElementRef,`,
    `  HostBinding,`,
    `  OnInit,`,
    `  OnDestroy,`,
    `  inject,`,
    `} from "@angular/core";`,
    `import { ${name}ContextToken, type ${name}ContextValue } from "./use${name}.js";`,
    `// @generated:end`,
    ``,
    `// @custom:start imports`,
    ``,
    `// @custom:end`,
    ``,
    `// @generated:start directive`,
    `/**`,
    ` * Attribute directive that lets a consumer adopt their own`,
    ` * element as the Tooltip anchor:`,
    ` *`,
    ` *   <fsds-tooltip>`,
    ` *     <a fsdsTooltipTrigger href="#help">Save</a>`,
    ` *     <fsds-tooltip-content>Help</fsds-tooltip-content>`,
    ` *   </fsds-tooltip>`,
    ` *`,
    ` * Registers the host element as the anchor with the nearest`,
    ` * Tooltip root context. Applies ARIA + data marker via host`,
    ` * bindings. DOM event listeners (pointerenter, focus, etc.) are`,
    ` * installed by the substrate's AnchoredSurfaceController on the`,
    ` * host element directly.`,
    ` */`,
    `@Directive({`,
    `  selector: "[fsds${name}Trigger]",`,
    `  standalone: true,`,
    `})`,
    `export class ${name}TriggerDirective implements OnInit, OnDestroy {`,
    `  private elRef = inject(ElementRef<HTMLElement>);`,
    `  protected ctx = inject(${name}ContextToken, { optional: true });`,
    ``,
    `  @HostBinding("attr.data-${cssPrefix}-trigger") get _dataMarker(): string {`,
    `    return "";`,
    `  }`,
    ``,
    ariaHostBindings,
    ``,
    `  ngOnInit(): void {`,
    `    if (!this.ctx) {`,
    `      throw new Error(`,
    `        "[fsds${name}Trigger] used outside of <${tagFor(name)}>.",`,
    `      );`,
    `    }`,
    `    this.ctx.registerAnchor(this.elRef.nativeElement);`,
    `  }`,
    ``,
    `  ngOnDestroy(): void {`,
    `    this.ctx?.registerAnchor(null);`,
    `  }`,
    `}`,
    `// @generated:end`,
    ``,
    `// @custom:start trailing`,
    ``,
    `// @custom:end`,
    ``,
  ].join("\n");
}

function emitTriggerComponent(ir: ComponentIR, _surface: SurfaceIR): string {
  const name = ir.name;
  const triggerTag = `${tagFor(name)}-trigger`;
  return [
    `// @generated:start imports`,
    `import { Component, ChangeDetectionStrategy } from "@angular/core";`,
    `import { ${name}TriggerDirective } from "./${name}Trigger.directive.js";`,
    `// @generated:end`,
    ``,
    `// @custom:start imports`,
    ``,
    `// @custom:end`,
    ``,
    `// @generated:start component`,
    `/**`,
    ` * Default-host trigger component. Renders a <button> and adopts`,
    ` * it as the anchor via the same [fsds${name}Trigger] directive`,
    ` * consumers use for their own elements. Both default-host and`,
    ` * host-adoption funnel through the directive's registration.`,
    ` */`,
    `@Component({`,
    `  selector: "${triggerTag}",`,
    `  standalone: true,`,
    `  imports: [${name}TriggerDirective],`,
    `  template: \`<button type="button" fsds${name}Trigger><ng-content /></button>\`,`,
    `  changeDetection: ChangeDetectionStrategy.OnPush,`,
    `})`,
    `export class ${name}TriggerComponent {}`,
    `// @generated:end`,
    ``,
    `// @custom:start trailing`,
    ``,
    `// @custom:end`,
    ``,
  ].join("\n");
}

function emitContentComponent(
  ir: ComponentIR,
  surface: SurfaceIR,
  policy: AnchoredSurfacePolicy,
): string {
  const name = ir.name;
  const cssPrefix = ir.cssPrefix;
  // Policy-derived default content role. `null` means: do not force
  // an ARIA role on the content host. Popover-kind surfaces let the
  // anchor relation (controls-expanded) carry the semantics; tooltip-
  // kind surfaces default to role="tooltip" unless the contract
  // overrides via `anatomy.parts.<content>.aria.role`.
  const contentRole = policy.defaultContentRole;
  const contentTag = `${tagFor(name)}-content`;
  // Role-reflection host binding. Emitted only when policy yields a
  // non-null role; otherwise the content host carries no `role` attr.
  const roleHostBindingLines = contentRole
    ? [
        `  @HostBinding("attr.role") get _role(): string | null {`,
        `    return this.isOpen() ? "${contentRole}" : null;`,
        `  }`,
        ``,
      ]
    : [];

  // Positioning + portal are driven by the contract and are
  // independent flags (see docs/codegen-authority.md):
  //   - surface.positioning.strategy === "anchored" → instantiate
  //     createAnchoredPosition against the anchor/content nodes the
  //     surface substrate already registers, and apply fixed-position
  //     host bindings (style + data-placement).
  //   - anchoredPortalsContentToBody(ir) → body-append this
  //     component's host element while open, mirroring the Dialog
  //     root-portal idiom (ngOnInit/ngOnDestroy save/restore original
  //     position). Portaling escapes ancestor stacking contexts and
  //     `overflow` clipping; the anchor/trigger stays in place.
  const positioningEnabled = surface.positioning?.strategy === "anchored";
  const collision = surface.positioning?.collision ?? "flip-shift";
  const portalsToBody = anchoredPortalsContentToBody({
    behavior: { portal: ir.behavior.portal },
    surface: { positioning: surface.positioning },
  });

  const positioningImportLines = positioningEnabled
    ? [
        `import {`,
        `  createAnchoredPosition,`,
        `  type CreateAnchoredPositionResult,`,
        `} from "../../primitives/surfaces/createAnchoredPosition.js";`,
      ]
    : [];

  const positioningFieldLines = positioningEnabled
    ? [
        ``,
        `  // Positioning substrate. Fed with getters for the anchor/`,
        `  // content nodes the surface registers and the resolved`,
        `  // placement input; recomputed whenever open/anchor/content`,
        `  // change via requestUpdate() below.`,
        `  private _position: CreateAnchoredPositionResult = createAnchoredPosition({`,
        `    anchor: () => this.ctx?.getAnchorNode() ?? null,`,
        `    content: () => this.ctx?.getContentNode() ?? null,`,
        `    open: () => this.isOpen(),`,
        `    placement: () => this.ctx?.getPlacement() ?? "auto",`,
        `    collision: () => "${collision}",`,
        `    destroyRef: inject(DestroyRef),`,
        `  });`,
      ]
    : [];

  const positioningHostBindingLines = positioningEnabled
    ? [
        `  @HostBinding("attr.data-placement") get _dataPlacement(): string | null {`,
        `    return this.isOpen() ? this._position.state().placement : null;`,
        `  }`,
        ``,
        `  @HostBinding("style.position") get _stylePosition(): string | null {`,
        `    return this.isOpen() ? "fixed" : null;`,
        `  }`,
        ``,
        `  @HostBinding("style.top.px") get _styleTop(): number | null {`,
        `    return this.isOpen() ? this._position.state().top : null;`,
        `  }`,
        ``,
        `  @HostBinding("style.left.px") get _styleLeft(): number | null {`,
        `    return this.isOpen() ? this._position.state().left : null;`,
        `  }`,
        ``,
        `  @HostBinding("style.visibility") get _styleVisibility(): string | null {`,
        `    if (!this.isOpen()) return null;`,
        `    return this._position.state().ready ? "visible" : "hidden";`,
        `  }`,
        ``,
      ]
    : [];

  const portalFieldLines = portalsToBody
    ? [
        ``,
        `  // Body-portal bookkeeping: saved so ngOnDestroy can restore`,
        `  // the host to its original in-tree position (Dialog root-`,
        `  // portal precedent). Anchored content has no in-tree`,
        `  // positioning context to lose (it's already position:`,
        `  // fixed against viewport coordinates), so portaling only`,
        `  // needs to escape ancestor stacking/overflow — it does not`,
        `  // need to preserve layout flow the way a non-anchored root`,
        `  // portal would.`,
        `  private _portalOriginParent: Node | null = null;`,
        `  private _portalOriginNext: Node | null = null;`,
        `  private _portalAppended = false;`,
      ]
    : [];

  const ngAfterViewInitBody = [
    `  ngAfterViewInit(): void {`,
    `    this.ctx?.registerContent(this.elRef.nativeElement);`,
    positioningEnabled ? `    this._position.requestUpdate();` : "",
    `  }`,
  ]
    .filter((line) => line !== "")
    .join("\n");

  const portalSyncBody = portalsToBody
    ? [
        ``,
        `  // Body-append while open; restore to the original in-tree`,
        `  // position on close (or destroy). Runs after each`,
        `  // \`isOpen()\`-affecting change because *ngIf on the`,
        `  // \`<ng-container>\` only gates the projected content — the`,
        `  // host element itself is always in the DOM for host`,
        `  // bindings to apply to, so the portal move is host-driven`,
        `  // here rather than template-driven.`,
        `  private _syncPortal(): void {`,
        `    if (typeof document === "undefined") return;`,
        `    const host = this.elRef.nativeElement;`,
        `    if (this.isOpen()) {`,
        `      if (this._portalAppended) return;`,
        `      this._portalOriginParent = host.parentNode;`,
        `      this._portalOriginNext = host.nextSibling;`,
        `      document.body.appendChild(host);`,
        `      this._portalAppended = true;`,
        `    } else {`,
        `      if (!this._portalAppended) return;`,
        `      if (this._portalOriginParent && this._portalOriginParent.isConnected) {`,
        `        this._portalOriginParent.insertBefore(host, this._portalOriginNext);`,
        `      } else {`,
        `        host.parentNode?.removeChild(host);`,
        `      }`,
        `      this._portalAppended = false;`,
        `    }`,
        `  }`,
      ].join("\n")
    : "";

  const ngOnDestroyBody = [
    `  ngOnDestroy(): void {`,
    `    this.ctx?.registerContent(null);`,
    portalsToBody
      ? [
          `    if (this._portalAppended && typeof document !== "undefined") {`,
          `      const host = this.elRef.nativeElement;`,
          `      if (this._portalOriginParent && this._portalOriginParent.isConnected) {`,
          `        this._portalOriginParent.insertBefore(host, this._portalOriginNext);`,
          `      } else {`,
          `        host.parentNode?.removeChild(host);`,
          `      }`,
          `      this._portalAppended = false;`,
          `    }`,
        ].join("\n")
      : "",
    `  }`,
  ]
    .filter((line) => line !== "")
    .join("\n");

  // isOpen() drives both the positioning recompute and the portal
  // move. Angular's OnPush + signal-computed `isOpen` doesn't offer a
  // template-level "value changed" hook, so we re-derive from a
  // computed effect-free read inside the host-binding getters
  // (positioning) and re-run the portal sync from ngDoCheck, which
  // OnPush components still receive on signal-triggered CD runs.
  const ngDoCheckBody =
    positioningEnabled || portalsToBody
      ? [
          ``,
          `  private _lastOpen = false;`,
          `  ngDoCheck(): void {`,
          `    const open = this.isOpen();`,
          `    if (open === this._lastOpen) return;`,
          `    this._lastOpen = open;`,
          positioningEnabled ? `    this._position.requestUpdate();` : "",
          portalsToBody ? `    this._syncPortal();` : "",
          `  }`,
        ]
          .filter((line) => line !== "")
          .join("\n")
      : "";

  const lifecycleInterfaces = [
    "AfterViewInit",
    "OnDestroy",
    positioningEnabled || portalsToBody ? "DoCheck" : "",
  ].filter((v) => v !== "");

  const coreImportNames = [
    "Component",
    "ElementRef",
    "HostBinding",
    "AfterViewInit",
    "OnDestroy",
    positioningEnabled || portalsToBody ? "DoCheck" : "",
    "inject",
    "computed",
    positioningEnabled ? "DestroyRef" : "",
    "ChangeDetectionStrategy",
  ].filter((v) => v !== "");

  return [
    `// @generated:start imports`,
    `import {`,
    ...coreImportNames.map((n) => `  ${n},`),
    `} from "@angular/core";`,
    `import { NgIf } from "@angular/common";`,
    `import { ${name}ContextToken } from "./use${name}.js";`,
    ...positioningImportLines,
    `// @generated:end`,
    ``,
    `// @custom:start imports`,
    ``,
    `// @custom:end`,
    ``,
    `// @generated:start component`,
    `@Component({`,
    `  selector: "${contentTag}",`,
    `  standalone: true,`,
    `  imports: [NgIf],`,
    `  template: \`<ng-container *ngIf="isOpen()"><ng-content /></ng-container>\`,`,
    `  changeDetection: ChangeDetectionStrategy.OnPush,`,
    `})`,
    `export class ${name}ContentComponent implements ${lifecycleInterfaces.join(", ")} {`,
    `  private elRef = inject(ElementRef<HTMLElement>);`,
    `  protected ctx = inject(${name}ContextToken, { optional: true });`,
    ``,
    `  // The substrate uses content.contains(relatedTarget) for grace-`,
    `  // path checks. We register the host element so contains() sees`,
    `  // the consumer's projected children too (they live in light DOM`,
    `  // under us). Open-state is reflected via host bindings on the`,
    `  // same host element so ARIA + the data marker apply to the`,
    `  // exact node the substrate registered.`,
    `  protected isOpen = computed(() => this.ctx?.open() ?? false);`,
    ...positioningFieldLines,
    ...portalFieldLines,
    ``,
    `  @HostBinding("attr.id") get _id(): string | null {`,
    `    return this.isOpen() && this.ctx ? this.ctx.contentId : null;`,
    `  }`,
    ``,
    ...roleHostBindingLines,
    `  @HostBinding("attr.data-${cssPrefix}-content") get _dataMarker(): string | null {`,
    `    return this.isOpen() ? "" : null;`,
    `  }`,
    ``,
    ...positioningHostBindingLines,
    ngAfterViewInitBody,
    portalSyncBody,
    ngDoCheckBody,
    ``,
    ngOnDestroyBody,
    `}`,
    `// @generated:end`,
    ``,
    `// @custom:start trailing`,
    ``,
    `// @custom:end`,
    ``,
  ].join("\n");
}

function emitComposable(ir: ComponentIR, surface: SurfaceIR): string {
  const name = ir.name;
  const anchorRelation = surface.anchor?.relation ?? "describedby";
  const positioningEnabled = surface.positioning?.strategy === "anchored";
  const placementValues = ir.variants["placement"];
  const placementType = placementValues ? `${name}Placement` : "string";
  // Type-only import of the placement alias from the root component
  // file. Safe against a circular runtime import (the root component
  // imports use${name} for values) because this is `import type` —
  // erased entirely at compile time, no runtime module cycle.
  const placementTypeImportLine =
    positioningEnabled && placementValues
      ? `import type { ${placementType} } from "./${name}.component.js";`
      : "";
  return [
    `// @generated:start imports`,
    [
      `import { InjectionToken, type Signal } from "@angular/core";`,
      `import {`,
      `  createAnchoredSurface,`,
      `  type CreateAnchoredSurfaceOptions,`,
      `  type CreateAnchoredSurfaceResult,`,
      `} from "../../primitives/surfaces/createAnchoredSurface.js";`,
      placementTypeImportLine,
    ]
      .filter((line) => line !== "")
      .join("\n"),
    `// @generated:end`,
    ``,
    `// @custom:start imports`,
    ``,
    `// @custom:end`,
    ``,
    `// @generated:start types`,
    [
      `export interface ${name}ContextValue {`,
      `  open: Signal<boolean>;`,
      `  setOpen: (next: boolean) => void;`,
      `  contentId: string;`,
      `  anchorRelation: "${anchorRelation}";`,
      `  registerAnchor: (node: HTMLElement | null) => void;`,
      `  registerContent: (node: HTMLElement | null) => void;`,
      `  getAnchorNode: () => HTMLElement | null;`,
      `  getContentNode: () => HTMLElement | null;`,
      positioningEnabled
        ? `  getPlacement: () => ${placementType} | undefined;`
        : "",
      `}`,
    ]
      .filter((line) => line !== "")
      .join("\n"),
    `// @generated:end`,
    ``,
    `// @custom:start types`,
    ``,
    `// @custom:end`,
    ``,
    `// @generated:start context`,
    `export const ${name}ContextToken = new InjectionToken<${name}ContextValue>(`,
    `  "${name}Context",`,
    `);`,
    `// @generated:end`,
    ``,
    `// @generated:start hook`,
    `// anchorRelation is contract-derived for this surface kind and`,
    `// is set by use${name} itself — consumers don't pass it.`,
    `export type Use${name}Options = Omit<CreateAnchoredSurfaceOptions, "anchorRelation">;`,
    ``,
    `export function use${name}(options: Use${name}Options): CreateAnchoredSurfaceResult {`,
    `  return createAnchoredSurface({`,
    `    ...options,`,
    `    anchorRelation: "${anchorRelation}",`,
    `  });`,
    `}`,
    `// @generated:end`,
    ``,
    `// @custom:start trailing`,
    ``,
    `// @custom:end`,
    ``,
  ].join("\n");
}
