// packages/ds-svelte/src/components/Label/Label.svelte
<script lang="ts">
// @generated:start imports

// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  htmlFor?: string;
  form?: string;
  class?: string;
  children?: import('svelte').Snippet;
}

let { htmlFor, form, class: className, children }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "label",
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<label class={classes} for={htmlFor} form={form} data-fsds-component="label" data-fsds-box="">
  {@render children?.()}
</label>

// packages/ds-vue/src/components/Label/Label.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  htmlFor?: string;
  form?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "label",
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <label :class="classNames" :for="props.htmlFor" :form="props.form" :data-testid="props['data-testid']" data-fsds-component="label" data-fsds-box="">
    <slot />
  </label>
</template>
