// packages/ds-vue/src/components/Switch/Switch.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useSwitch } from "./useSwitch.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type SwitchSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  checked?: boolean;
  defaultChecked?: boolean;
  onChange?: (checked: boolean) => void;
  size?: SwitchSize;
  disabled?: boolean;
  name?: string;
  value?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  checked: undefined,
  defaultChecked: undefined,
  size: "md",
  disabled: undefined,
});
// @generated:end

// @generated:start hook
const behavior = useSwitch({
  checked: () => props.checked,
  defaultChecked: props.defaultChecked,
  onChange: props.onChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "switch",
  props.size ? `switch--${props.size}` : null,
  behavior.checked.value ? "switch--checked" : null,
  props.disabled ? "switch--disabled" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <label :class="classNames" :data-testid="props['data-testid']">
    <input :class="'switch__input'" type="checkbox" role="switch" @change="(e) => behavior.setChecked((e.target as HTMLInputElement).checked)" :checked="behavior.checked.value" :disabled="props.disabled" :name="props.name" :value="props.value" />
    <span :class="'switch__track'" aria-hidden="true">
      <span :class="'switch__thumb'"></span>
    </span>
  </label>
</template>

// packages/ds-react/src/components/Switch/Switch.tsx
// @generated:start imports
import { type ReactNode } from "react";
import { useSwitch } from "./useSwitch";
import "./Switch.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type SwitchSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface SwitchProps {
  checked?: boolean;
  defaultChecked?: boolean;
  onChange?: (checked: boolean) => void;
  size?: SwitchSize;
  disabled?: boolean;
  name?: string;
  value?: string;
  className?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start subcomponents

// @generated:end

// @generated:start component
export function Switch({
  checked: controlledChecked,
  defaultChecked,
  onChange,
  size = "md",
  disabled,
  className,
  "data-testid": testId,
  name,
  value,
  ...rest
}: SwitchProps) {
  const { checked, setChecked } = useSwitch({
    checked: controlledChecked,
    defaultChecked,
    onChange,
  });

  const classNames = [
    "switch",
    size && `switch--${size}`,
    checked && "switch--checked",
    disabled && "switch--disabled",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <label className={`${classNames}`} data-testid={testId} {...rest}>
    <input className="switch__input" type="checkbox" role="switch" checked={checked} onChange={(e) => setChecked(e.target.checked)} disabled={disabled} name={name} value={value} />
    <span className="switch__track" aria-hidden="true">
      <span className="switch__thumb" />
    </span>
  </label>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end
