// packages/ds-react/src/components/Input/Input.tsx
// @generated:start imports
import { type ReactNode } from "react";
import { useInput } from "./useInput";
import "./Input.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface InputProps {
  type?: string;
  value?: string;
  defaultValue?: string;
  onChange?: (value: string) => void;
  placeholder?: string;
  disabled?: boolean;
  invalid?: boolean;
  required?: boolean;
  name?: string;
  className?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start subcomponents

// @generated:end

// @generated:start component
export function Input({
  value: controlledValue,
  defaultValue,
  onChange,
  disabled,
  invalid,
  className,
  "data-testid": testId,
  type,
  placeholder,
  required,
  name,
  ...rest
}: InputProps) {
  const { value, setValue } = useInput({
    value: controlledValue,
    defaultValue,
    onChange,
  });

  const classNames = [
    "input",
    disabled && "input--disabled",
    invalid && "input--invalid",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <input className={`${classNames}`} value={value} onChange={(e) => setValue(e.target.value)} disabled={disabled} aria-invalid={invalid} type={type} role="textbox" data-testid={testId} {...rest} />
  );
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/Input/Input.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useInput } from "./useInput.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  type?: string;
  value?: string;
  defaultValue?: string;
  onChange?: (value: string) => void;
  placeholder?: string;
  disabled?: boolean;
  invalid?: boolean;
  required?: boolean;
  name?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  disabled: undefined,
  invalid: undefined,
  required: undefined,
});
// @generated:end

// @generated:start hook
const behavior = useInput({
  value: () => props.value,
  defaultValue: props.defaultValue,
  onChange: props.onChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "input",
  props.disabled ? "input--disabled" : null,
  props.invalid ? "input--invalid" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <input :class="classNames" @change="(e) => behavior.setValue((e.target as HTMLInputElement).value)" :value="behavior.value.value" :disabled="props.disabled" :aria-invalid="props.invalid" :type="props.type" role="textbox" :data-testid="props['data-testid']" />
</template>
