// packages/ds-vue/src/components/Switch/Switch.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useSwitch } from "./useSwitch.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type SwitchSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  checked?: boolean;
  defaultChecked?: boolean;
  onChange?: (checked: boolean) => void;
  size?: SwitchSize;
  disabled?: boolean;
  name?: string;
  value?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  checked: undefined,
  defaultChecked: undefined,
  size: "md",
  disabled: undefined,
});
// @generated:end

// @generated:start hook
const behavior = useSwitch({
  checked: () => props.checked,
  defaultChecked: props.defaultChecked,
  onChange: props.onChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "switch",
  props.size ? `switch--${props.size}` : null,
  behavior.checked.value ? "switch--checked" : null,
  props.disabled ? "switch--disabled" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <label :class="classNames" :data-testid="props['data-testid']" data-fsds-component="switch">
    <input :class="'switch__input'" type="checkbox" role="switch" @change="(e) => behavior.setChecked((e.target as HTMLInputElement).checked)" :checked="behavior.checked.value" :disabled="props.disabled" :name="props.name" :value="props.value" />
    <span :class="'switch__track'" aria-hidden="true">
      <span :class="'switch__thumb'"></span>
    </span>
    <slot />
  </label>
</template>

// packages/ds-angular/src/components/Switch/Switch.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass } from "@angular/common";
import { useSwitch } from "./useSwitch.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type SwitchSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-switch",
  standalone: true,
  imports: [NgClass],
  template: `<label [ngClass]="classes()">
  <input [ngClass]="'switch__input'" type="checkbox" role="switch" (change)="handleCheckedChange($event)" [checked]="behavior.checked()" [disabled]="disabled" [name]="name" [value]="value" />
  <span [ngClass]="'switch__track'" aria-hidden="true">
    <span [ngClass]="'switch__thumb'"></span>
  </span>
</label>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SwitchComponent {
  @Input() checked?: boolean;
  @Input() defaultChecked?: boolean;
  @Input() size?: SwitchSize = "md";
  @Input() disabled?: boolean;
  @Input() name?: string;
  @Input() value?: string;
  @Input() class?: string;
  @Input() onChange?: (value: boolean) => void;

  private destroyRef = inject(DestroyRef);
  protected behavior = useSwitch({
    checked: () => this.checked,
    defaultChecked: this.defaultChecked,
    onChange: (v) => this.onChange?.(v),
    destroyRef: this.destroyRef,
  });

  classes = computed(() =>
    [
      "switch",
      this.size ? `switch--${this.size}` : null,
      this.behavior.checked() ? "switch--checked" : null,
      this.disabled ? "switch--disabled" : null,
      this.class,
    ].filter(Boolean).join(" "),
  );

  protected handleCheckedChange(event: Event): void {
    this.behavior.setChecked((event.target as HTMLInputElement).checked);
  }
}
// @generated:end

// @custom:start trailing

// @custom:end
