// packages/ds-angular/src/components/VisuallyHidden/VisuallyHidden.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass } from "@angular/common";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-visually-hidden",
  standalone: true,
  imports: [NgClass],
  template: `<span [ngClass]="classes()">
  <ng-content />
</span>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class VisuallyHiddenComponent {
  @Input() focusable?: boolean;
  @Input() title?: string;
  @Input() class?: string;

  classes(): string {
    return [
      "visually-hidden",
      this.class,
    ].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/VisuallyHidden/VisuallyHidden.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  focusable?: boolean;
  title?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "visually-hidden",
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <span :class="classNames" :data-testid="props['data-testid']">
    <slot />
  </span>
</template>
