// packages/ds-vue/src/components/CodeSnippet/CodeSnippet.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type CodeSnippetElement = "code" | "kbd" | "samp";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  text: string;
  as?: CodeSnippetElement;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  as: "code",
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "code-snippet",
  props.as ? `code-snippet--${props.as}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <component :is="props.as ?? 'code'" :class="classNames" spellcheck="false" :data-testid="props['data-testid']" data-fsds-component="code-snippet" data-fsds-box="">
    {{ props.text }}
  </component>
</template>

// packages/ds-react/src/components/CodeSnippet/CodeSnippet.tsx
// @generated:start imports
import { type ReactNode } from "react";
import { Stack } from "../../primitives";
import "./CodeSnippet.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type CodeSnippetElement = "code" | "kbd" | "samp";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface CodeSnippetProps {
  text: string;
  as?: CodeSnippetElement;
  className?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start subcomponents

// @generated:end

// @generated:start component
export function CodeSnippet({
  as = "code",
  className,
  "data-testid": testId,
  text,
  ...rest
}: CodeSnippetProps) {
  const classNames = [
    "code-snippet",
    as && `code-snippet--${as}`,
    className,
  ]
    .filter(Boolean)
    .join(" ");

  const As = as ?? "code";

  return (
  <Stack layout="native" as={As} className={`${classNames}`} spellCheck="false" data-testid={testId} data-fsds-component="code-snippet" data-fsds-box="" {...rest}>
    {text}
  </Stack>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end
