// packages/ds-react/src/components/CodeBlock/CodeBlock.tsx
// @generated:start imports
import { type ReactNode } from "react";
import { Stack } from "../../primitives";
import "./CodeBlock.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type CodeBlockLanguage = "bash" | "css" | "html" | "javascript" | "json" | "jsx" | "markdown" | "plaintext" | "tsx" | "typescript";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface CodeBlockProps {
  code: string;
  language: CodeBlockLanguage;
  className?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start subcomponents

// @generated:end

// @generated:start component
export function CodeBlock({
  className,
  "data-testid": testId,
  code,
  language,
  ...rest
}: CodeBlockProps) {
  const classNames = [
    "code-block",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <Stack layout="native" as="pre" className={`${classNames}`} data-language={language} data-testid={testId} data-fsds-component="code-block" {...rest}>
    <code className="code-block__code" spellCheck="false" data-language={language}>
      {code}
    </code>
  </Stack>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/CodeBlock/CodeBlock.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type CodeBlockLanguage = "bash" | "css" | "html" | "javascript" | "json" | "jsx" | "markdown" | "plaintext" | "tsx" | "typescript";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  code: string;
  language: CodeBlockLanguage;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "code-block",
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <pre :class="classNames" :data-language="props.language" :data-testid="props['data-testid']" data-fsds-component="code-block">
    <code :class="'code-block__code'" spellcheck="false" :data-language="props.language">
      {{ props.code }}
    </code>
  </pre>
</template>
