// packages/ds-svelte/src/components/Spinner/Spinner.svelte
<script lang="ts">
// @generated:start imports

// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type SpinnerSize = "xs" | "sm" | "md" | "lg";
type SpinnerThickness = "hairline" | "regular" | "bold";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  size?: SpinnerSize;
  thickness?: SpinnerThickness;
  ariaHidden?: boolean;
  label?: string;
  inline?: boolean;
  showAfterMs?: number;
  class?: string;
}

let { size, thickness, ariaHidden, label, inline, showAfterMs, class: className }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "spinner",
    size ? `spinner--${size}` : null,
    thickness ? `spinner--${thickness}` : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} aria-label={label} aria-hidden={ariaHidden} data-fsds-component="spinner" data-fsds-box="" role="status">
  <span class={'spinner__visual'} aria-hidden="true"></span>
</div>

// packages/ds-angular/src/components/Spinner/Spinner.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass } from "@angular/common";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type SpinnerSize = "xs" | "sm" | "md" | "lg";
export type SpinnerThickness = "hairline" | "regular" | "bold";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-spinner",
  standalone: true,
  imports: [NgClass],
  host: { "data-fsds-component": "spinner" },
  template: `<div [ngClass]="classes()" [attr.aria-label]="label" [attr.aria-hidden]="ariaHidden" data-fsds-box="" role="status">
  <span [ngClass]="'spinner__visual'" aria-hidden="true"></span>
</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SpinnerComponent {
  @Input() size?: SpinnerSize;
  @Input() thickness?: SpinnerThickness;
  @Input() ariaHidden?: boolean;
  @Input() label?: string;
  @Input() inline?: boolean;
  @Input() showAfterMs?: number;
  @Input() class?: string;

  classes(): string {
    return [
      "spinner",
      this.size ? `spinner--${this.size}` : null,
      this.thickness ? `spinner--${this.thickness}` : null,
      this.class,
    ].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end
