// packages/ds-svelte/src/components/Progress/Progress.svelte
<script lang="ts">
// @generated:start imports

// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type ProgressVariant = "linear" | "circular";
type ProgressSize = "sm" | "md" | "lg";
type ProgressIntent = "info" | "success" | "warning" | "danger";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  value?: number;
  variant?: ProgressVariant;
  size?: ProgressSize;
  intent?: ProgressIntent;
  label?: string;
  showValue?: boolean;
  formatValue?: (value: number, max: number) => string;
  class?: string;
  children?: import('svelte').Snippet;
}

let { value, variant, size, intent, label, showValue, formatValue, class: className, children }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "progress",
    variant ? `progress--${variant}` : null,
    size ? `progress--${size}` : null,
    intent ? `progress--${intent}` : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} role="progressbar" aria-valuenow={value} aria-valuemin="0" aria-valuemax="100" aria-label={label} data-fsds-component="progress">
  <span class={'progress__track'} aria-hidden="true">
    <span class={'progress__fill'} style:--fsds-progress-fill-width={value}></span>
  </span>
  {#if showValue}
  <span class={'progress__value'}>
    {@render children?.()}
  </span>
  {/if}
</div>

// packages/ds-vue/src/components/Progress/Progress.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type ProgressVariant = "linear" | "circular";
export type ProgressSize = "sm" | "md" | "lg";
export type ProgressIntent = "info" | "success" | "warning" | "danger";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  value?: number;
  variant?: ProgressVariant;
  size?: ProgressSize;
  intent?: ProgressIntent;
  label?: string;
  showValue?: boolean;
  formatValue?: (value: number, max: number) => string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "progress",
  props.variant ? `progress--${props.variant}` : null,
  props.size ? `progress--${props.size}` : null,
  props.intent ? `progress--${props.intent}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" role="progressbar" :aria-valuenow="props.value" aria-valuemin="0" aria-valuemax="100" :aria-label="props.label" :data-testid="props['data-testid']">
    <span :class="'progress__track'" aria-hidden="true">
      <span :class="'progress__fill'" :style="{ '--fsds-progress-fill-width': props.value }"></span>
    </span>
    <span v-if="props.showValue" :class="'progress__value'">
      <slot />
    </span>
  </div>
</template>
