// packages/ds-react/src/components/AnimatedCard/AnimatedCard.tsx
// @generated:start imports
import { type ReactNode } from "react";
import { Stack } from "../../primitives";
import "./AnimatedCard.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type AnimatedCardAs = "article" | "div" | "li" | "a";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface AnimatedCardProps {
  as?: AnimatedCardAs;
  duration?: number;
  delay?: number;
  triggerOnScroll?: boolean;
  scrollStart?: string;
  enableHover?: boolean;
  href?: string;
  className?: string;
  "data-testid"?: string;
  children?: ReactNode;
}
// @generated:end

// @generated:start subcomponents
export interface AnimatedCardTitleProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function AnimatedCardTitle({
  children,
  className,
  "data-testid": testId,
}: AnimatedCardTitleProps) {
  const classNames = ["animated-card__title", className].filter(Boolean).join(" ");
  return (
    <Stack as="h3" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}
// @generated:end

// @generated:start component
export function AnimatedCard({
  as,
  className,
  "data-testid": testId,
  children,
  duration,
  delay,
  triggerOnScroll,
  scrollStart,
  enableHover,
  href,
  ...rest
}: AnimatedCardProps) {
  const classNames = [
    "animated-card",
    as && `animated-card--${as}`,
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <div className={`${classNames}`} data-as={as} data-testid={testId} {...rest}>
    {children}
  </div>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/AnimatedCard/AnimatedCard.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type AnimatedCardAs = "article" | "div" | "li" | "a";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  as?: AnimatedCardAs;
  duration?: number;
  delay?: number;
  triggerOnScroll?: boolean;
  scrollStart?: string;
  enableHover?: boolean;
  href?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "animated-card",
  props.as ? `animated-card--${props.as}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" :data-as="props.as" :data-testid="props['data-testid']">
    <slot />
  </div>
</template>
