// packages/ds-svelte/src/components/OTP/OTP.svelte
<script lang="ts">
// @generated:start imports
import { useOTP } from "./useOTP.svelte.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type OTPMode = "numeric" | "alphanumeric";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  length?: number;
  value?: string;
  defaultValue?: string;
  onChange?: (value: string) => void;
  onComplete?: (value: string) => void;
  mode?: OTPMode;
  disabled?: boolean;
  readOnly?: boolean;
  label?: string;
  class?: string;
}

let { length = 6, value, defaultValue, onChange, onComplete, mode = "numeric", disabled, readOnly, label = "One-time password", class: className }: Props = $props();
// @generated:end

// @generated:start hook
const behavior = useOTP({
  value: () => value,
  defaultValue: () => defaultValue,
  onChange: () => onChange,
});
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "otp",
    mode ? `otp--${mode}` : null,
    disabled ? "otp--disabled" : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} role="group" aria-label={label} aria-describedby="otp-error-id">
  <div class={'otp__group'}>
    <input class={'otp__field'} type="text" inputmode="numeric" autocomplete="one-time-code" maxlength="1" disabled={disabled} aria-readonly={readOnly} />
  </div>
</div>

// packages/ds-vue/src/components/OTP/OTP.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useOTP } from "./useOTP.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type OTPMode = "numeric" | "alphanumeric";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  length?: number;
  value?: string;
  defaultValue?: string;
  onChange?: (value: string) => void;
  onComplete?: (value: string) => void;
  mode?: OTPMode;
  disabled?: boolean;
  readOnly?: boolean;
  label?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  length: 6,
  mode: "numeric",
  label: "One-time password",
});
// @generated:end

// @generated:start hook
const behavior = useOTP({
  value: () => props.value,
  defaultValue: props.defaultValue,
  onChange: props.onChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "otp",
  props.mode ? `otp--${props.mode}` : null,
  props.disabled ? "otp--disabled" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" role="group" :aria-label="props.label" aria-describedby="otp-error-id" :data-testid="props['data-testid']">
    <div :class="'otp__group'">
      <input :class="'otp__field'" type="text" inputmode="numeric" autocomplete="one-time-code" maxlength="1" :disabled="props.disabled" :aria-readonly="props.readOnly" />
    </div>
  </div>
</template>
