// packages/ds-vue/src/components/Details/Details.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useDetails } from "./useDetails.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type DetailsVariant = "default" | "inline" | "compact";
export type DetailsIcon = "left" | "right" | "none";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  summary: string;
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  disabled?: boolean;
  variant?: DetailsVariant;
  icon?: DetailsIcon;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  open: undefined,
  defaultOpen: undefined,
  disabled: undefined,
});
// @generated:end

// @generated:start hook
const behavior = useDetails({
  open: () => props.open,
  defaultOpen: props.defaultOpen,
  onOpenChange: props.onOpenChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "details",
  props.variant ? `details--${props.variant}` : null,
  props.icon ? `details--${props.icon}` : null,
  behavior.open.value ? "details--open" : null,
  props.disabled ? "details--disabled" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <details :class="classNames" :open="behavior.open.value" role="group" :data-testid="props['data-testid']">
    <summary :class="'details__summary'">
      <span :class="'details__summaryContent'">
        <span :class="'details__icon'"></span>
        <span :class="'details__summaryText'">
          {{ props.summary }}
        </span>
      </span>
    </summary>
    <div v-if="behavior.open.value" :class="'details__content'">
      <slot />
    </div>
  </details>
</template>

// packages/ds-lit/src/components/Details/Details.ts
// @generated:start imports
import { LitElement, html, css, nothing } from 'lit';
import { property } from 'lit/decorators.js';
import { DetailsBehavior } from './DetailsBehavior.js';
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type DetailsVariant = "default" | "inline" | "compact";
export type DetailsIcon = "left" | "right" | "none";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
export class DetailsElement extends LitElement {
  static override styles = css`:host { display: contents; }`;

  @property() summary!: string;
  @property({ type: Boolean }) open?: boolean;
  @property({ type: Boolean }) defaultOpen?: boolean;
  @property({ type: Boolean }) disabled?: boolean;
  @property() variant?: DetailsVariant;
  @property() icon?: DetailsIcon;
  @property({ attribute: false }) onOpenChange?: (value: boolean) => void;

  private behavior = new DetailsBehavior(this, {
    open: () => this.open,
    defaultOpen: this.defaultOpen,
    onOpenChange: (v) => this.onOpenChange?.(v),
  });

  private computeClasses(): string {
    return [
      "details",
      this.variant ? `details--${this.variant}` : null,
      this.icon ? `details--${this.icon}` : null,
      this.behavior.open ? "details--open" : null,
      this.disabled ? "details--disabled" : null,
    ].filter(Boolean).join(" ");
  }

  override render() {
    return html`<details class="${this.computeClasses()}" role="group" ?open=${this.behavior.open}>
  <summary class=${'details__summary'}>
    <span class=${'details__summaryContent'}>
      <span class=${'details__icon'}></span>
      <span class=${'details__summaryText'} .textContent=${this.summary}></span>
    </span>
  </summary>
  ${this.behavior.open ? html`
  <div class=${'details__content'} data-fsds-channel-renders="open">
    <slot></slot>
  </div>
  ` : nothing}
</details>`;
  }
}

customElements.define('fsds-details', DetailsElement);

export class DetailsContentElement extends LitElement {
  static override styles = css`:host { display: contents; }`;

  override render() {
    return html`<fsds-stack class="details__content"><slot></slot></fsds-stack>`;
  }
}

customElements.define('fsds-details-content', DetailsContentElement);
// @generated:end

// @custom:start trailing

// @custom:end
