// packages/ds-vue/src/components/Badge/Badge.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type BadgeVariant = "default" | "status" | "counter" | "tag";
export type BadgeIntent = "info" | "success" | "warning" | "danger";
export type BadgeSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  variant?: BadgeVariant;
  intent?: BadgeIntent;
  size?: BadgeSize;
  icon?: unknown;
  showStatusIcon?: boolean;
  class?: string;
  dataTestid?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  showStatusIcon: undefined,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "badge",
  props.variant ? `badge--${props.variant}` : null,
  props.intent ? `badge--${props.intent}` : null,
  props.size ? `badge--${props.size}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <span :class="classNames" :data-testid="props.dataTestid" data-fsds-component="badge" data-fsds-box="">
    <span v-if="props.icon" :class="'badge__icon'" aria-hidden="true">
      {{ props.icon }}
    </span>
    <span :class="'badge__content'">
      <slot />
    </span>
  </span>
</template>

// packages/ds-angular/src/components/Badge/Badge.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass, NgIf } from "@angular/common";
import { StackComponent } from "../../primitives/index.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type BadgeVariant = "default" | "status" | "counter" | "tag";
export type BadgeIntent = "info" | "success" | "warning" | "danger";
export type BadgeSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-badge",
  standalone: true,
  imports: [NgClass, NgIf],
  host: { "data-fsds-component": "badge" },
  template: `<span [ngClass]="classes()" data-fsds-box="">
  <ng-container *ngIf="icon">
    <span [ngClass]="'badge__icon'" aria-hidden="true">
      {{ icon }}
    </span>
  </ng-container>
  <span [ngClass]="'badge__content'">
    <ng-content />
  </span>
</span>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BadgeComponent {
  @Input() variant?: BadgeVariant;
  @Input() intent?: BadgeIntent;
  @Input() size?: BadgeSize;
  @Input() icon?: unknown;
  @Input() showStatusIcon?: boolean;
  @Input() class?: string;

  classes(): string {
    return [
      "badge",
      this.variant ? `badge--${this.variant}` : null,
      this.intent ? `badge--${this.intent}` : null,
      this.size ? `badge--${this.size}` : null,
      this.class,
    ].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-badge-content",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BadgeContentComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["badge__content", this.class].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end
