// packages/ds-svelte/src/components/Markdown/Markdown.svelte
<script lang="ts">
// @generated:start imports
import { parseMarkdown, type MarkdownBlock, type MarkdownMark } from "../../primitives/markdown/markdown.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  content: string;
  class?: string;
}

let { content, class: className }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "markdown",
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} data-fsds-component="markdown" data-fsds-box="">{#each parseMarkdown(content ?? "") as block, blockIndex}{@render markdownBlock(block, blockIndex)}{/each}</div>

{#snippet markdownBlock(block: MarkdownBlock, blockIndex: number)}
  {#if block.kind === "heading"}
    <h2 class="markdown__heading" data-block-kind="heading" data-block-kind-level={block.level}>{#each block.children as mark, markIndex}{@render markdownMark(mark, markIndex)}{/each}</h2>
  {:else if block.kind === "paragraph"}
    <p class="markdown__paragraph" data-block-kind="paragraph">{#each block.children as mark, markIndex}{@render markdownMark(mark, markIndex)}{/each}</p>
  {:else if block.kind === "list"}
    {#if block.ordered}
      <ol class="markdown__orderedList" data-block-kind="orderedList">{#each block.items as item, itemIndex}{@render markdownBlock(item, itemIndex)}{/each}</ol>
    {:else}
      <ul class="markdown__unorderedList" data-block-kind="unorderedList">{#each block.items as item, itemIndex}{@render markdownBlock(item, itemIndex)}{/each}</ul>
    {/if}
  {:else if block.kind === "listItem"}
    <li class="markdown__listItem" data-block-kind="listItem">{#each block.children as mark, markIndex}{@render markdownMark(mark, markIndex)}{/each}</li>
  {:else if block.kind === "codeBlock"}
    <pre class="markdown__codeBlock" data-block-kind="codeBlock" data-language={block.language}>{block.text}</pre>
  {:else if block.kind === "blockquote"}
    <blockquote class="markdown__blockquote" data-block-kind="blockquote">{#each block.children as mark, markIndex}{@render markdownMark(mark, markIndex)}{/each}</blockquote>
  {/if}
{/snippet}

{#snippet markdownMark(mark: MarkdownMark, markIndex: number)}
  {#if mark.kind === "text"}
    {mark.text}
  {:else if mark.kind === "code"}
    <code class="markdown__code" data-mark-kind="code">{mark.text}</code>
  {:else if mark.kind === "emphasis"}
    <em class="markdown__emphasis" data-mark-kind="emphasis">{#each mark.children as child, childIndex}{@render markdownMark(child, childIndex)}{/each}</em>
  {:else if mark.kind === "strong"}
    <strong class="markdown__strong" data-mark-kind="strong">{#each mark.children as child, childIndex}{@render markdownMark(child, childIndex)}{/each}</strong>
  {:else if mark.kind === "link"}
    {#if mark.href === null}
      <span>{#each mark.children as child, childIndex}{@render markdownMark(child, childIndex)}{/each}</span>
    {:else}
      <a class="markdown__link" data-mark-kind="link" href={mark.href}>{#each mark.children as child, childIndex}{@render markdownMark(child, childIndex)}{/each}</a>
    {/if}
  {/if}
{/snippet}

// packages/ds-react/src/components/Markdown/Markdown.tsx
// @generated:start imports
import { type HTMLAttributes, type ReactNode } from "react";
import { Stack } from "../../primitives";
import { parseMarkdown, type MarkdownBlock, type MarkdownMark } from "../../primitives/markdown/markdown";
import { Fragment } from "react";
import "./Markdown.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface MarkdownProps extends Omit<HTMLAttributes<HTMLDivElement>, "children" | "className" | "content" | "data-testid"> {
  content: string;
  className?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start subcomponents

function renderMarkdownBlocks(source: string): React.ReactNode[] {
  return parseMarkdown(source ?? "").map((block, blockIndex) =>
    renderMarkdownBlock(block, blockIndex),
  );
}

function renderMarkdownBlock(block: MarkdownBlock, key: React.Key): React.ReactNode {
  switch (block.kind) {
    case "heading":
      return (
        <h2 key={key} className="markdown__heading" data-block-kind="heading" data-level={block.level}>
          {block.children.map((mark, markIndex) => renderMarkdownMark(mark, markIndex))}
        </h2>
      );
    case "paragraph":
      return (
        <p key={key} className="markdown__paragraph" data-block-kind="paragraph">
          {block.children.map((mark, markIndex) => renderMarkdownMark(mark, markIndex))}
        </p>
      );
    case "list":
      return block.ordered ? (
        <ol key={key} className="markdown__orderedList" data-block-kind="orderedList">
          {block.items.map((item, itemIndex) => renderMarkdownBlock(item, itemIndex))}
        </ol>
      ) : (
        <ul key={key} className="markdown__unorderedList" data-block-kind="unorderedList">
          {block.items.map((item, itemIndex) => renderMarkdownBlock(item, itemIndex))}
        </ul>
      );
    case "listItem":
      return (
        <li key={key} className="markdown__listItem" data-block-kind="listItem">
          {block.children.map((mark, markIndex) => renderMarkdownMark(mark, markIndex))}
        </li>
      );
    case "codeBlock":
      return (
        <pre key={key} className="markdown__codeBlock" data-block-kind="codeBlock" data-language={block.language}>
          {block.text}
        </pre>
      );
    case "blockquote":
      return (
        <blockquote key={key} className="markdown__blockquote" data-block-kind="blockquote">
          {block.children.map((mark, markIndex) => renderMarkdownMark(mark, markIndex))}
        </blockquote>
      );
  }
}

function renderMarkdownMark(mark: MarkdownMark, key: React.Key): React.ReactNode {
  switch (mark.kind) {
    case "text":
      return <Fragment key={key}>{mark.text}</Fragment>;
    case "code":
      return (
        <code key={key} className="markdown__code" data-mark-kind="code">{mark.text}</code>
      );
    case "emphasis":
      return (
        <em key={key} className="markdown__emphasis" data-mark-kind="emphasis">
          {mark.children.map((child, childIndex) => renderMarkdownMark(child, childIndex))}
        </em>
      );
    case "strong":
      return (
        <strong key={key} className="markdown__strong" data-mark-kind="strong">
          {mark.children.map((child, childIndex) => renderMarkdownMark(child, childIndex))}
        </strong>
      );
    case "link":
      return mark.href === null ? (
        <Fragment key={key}>
          {mark.children.map((child, childIndex) => renderMarkdownMark(child, childIndex))}
        </Fragment>
      ) : (
        <a key={key} className="markdown__link" data-mark-kind="link" href={mark.href}>
          {mark.children.map((child, childIndex) => renderMarkdownMark(child, childIndex))}
        </a>
      );
  }
}

// @generated:end

// @generated:start component
export function Markdown({
  className,
  "data-testid": testId,
  content,
  ...rest
}: MarkdownProps) {
  const classNames = [
    "markdown",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <Stack layout="native" className={`${classNames}`} data-testid={testId} data-fsds-component="markdown" data-fsds-box="" {...rest}>
    {renderMarkdownBlocks(content)}
  </Stack>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end
