// packages/ds-angular/src/components/ShowMore/ShowMore.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass, NgIf } from "@angular/common";
import { StackComponent } from "../../primitives/index.js";
import { useShowMore } from "./useShowMore.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-show-more",
  standalone: true,
  imports: [NgClass, NgIf],
  template: `<div [ngClass]="classes()">
  <div [ngClass]="'show-more__content'">
    <ng-content />
  </div>
  <button [ngClass]="'show-more__trigger'" type="button" [attr.aria-expanded]="behavior.expanded()" (click)="handleExpandedChange($event)" [textContent]="showMoreLabel"></button>
</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ShowMoreComponent {
  @Input() expanded?: boolean;
  @Input() defaultExpanded?: boolean;
  @Input() maxLines?: number = 3;
  @Input() showMoreLabel?: string = "Show more";
  @Input() showLessLabel?: string = "Show less";
  @Input() class?: string;
  @Input() onExpandedChange?: (value: boolean) => void;

  private destroyRef = inject(DestroyRef);
  protected behavior = useShowMore({
    expanded: () => this.expanded,
    defaultExpanded: this.defaultExpanded,
    onExpandedChange: (v) => this.onExpandedChange?.(v),
    destroyRef: this.destroyRef,
  });

  classes = computed(() =>
    [
      "show-more",
      this.behavior.expanded() ? "show-more--expanded" : null,
      this.class,
    ].filter(Boolean).join(" "),
  );

  protected handleExpandedChange(event: Event): void {
    this.behavior.setExpanded((event.target as HTMLInputElement).checked);
  }
}

@Component({
  selector: "fsds-show-more-content",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ShowMoreContentComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["show-more__content", this.class].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-show-more-trigger",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="button" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ShowMoreTriggerComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["show-more__trigger", this.class].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-lit/src/components/ShowMore/ShowMore.ts
// @generated:start imports
import { LitElement, html, css, nothing } from 'lit';
import { property } from 'lit/decorators.js';
import { ShowMoreBehavior } from './ShowMoreBehavior.js';
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
export class ShowMoreElement extends LitElement {
  static override styles = css`:host { display: contents; }`;

  @property({ type: Boolean }) expanded?: boolean;
  @property({ type: Boolean }) defaultExpanded?: boolean;
  @property({ type: Number }) maxLines?: number = 3;
  @property() showMoreLabel?: string = "Show more";
  @property() showLessLabel?: string = "Show less";
  @property({ attribute: false }) onExpandedChange?: (value: boolean) => void;

  private behavior = new ShowMoreBehavior(this, {
    expanded: () => this.expanded,
    defaultExpanded: this.defaultExpanded,
    onExpandedChange: (v) => this.onExpandedChange?.(v),
  });

  private handleExpandedChange(event: Event): void {
    this.behavior.setExpanded((event.target as HTMLInputElement).checked);
  }

  private computeClasses(): string {
    return [
      "show-more",
      this.behavior.expanded ? "show-more--expanded" : null,
    ].filter(Boolean).join(" ");
  }

  override render() {
    return html`<div class="${this.computeClasses()}">
  <div class=${'show-more__content'}>
    <slot></slot>
  </div>
  <button class=${'show-more__trigger'} type="button" aria-expanded=${this.behavior.expanded ? 'true' : 'false'} @click=${(e: Event) => this.handleExpandedChange(e)} .textContent=${this.showMoreLabel}></button>
</div>`;
  }
}

customElements.define('fsds-show-more', ShowMoreElement);

export class ShowMoreContentElement extends LitElement {
  static override styles = css`:host { display: contents; }`;

  override render() {
    return html`<fsds-stack class="show-more__content"><slot></slot></fsds-stack>`;
  }
}

customElements.define('fsds-show-more-content', ShowMoreContentElement);

export class ShowMoreTriggerElement extends LitElement {
  static override styles = css`:host { display: contents; }`;

  override render() {
    return html`<fsds-stack as="button" class="show-more__trigger"><slot></slot></fsds-stack>`;
  }
}

customElements.define('fsds-show-more-trigger', ShowMoreTriggerElement);
// @generated:end

// @custom:start trailing

// @custom:end
