// packages/ds-vue/src/components/Links/Links.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type LinkTarget = "_self" | "_blank" | "_parent" | "_top";
export type LinkSize = "small" | "medium" | "large";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  href?: string;
  target?: LinkTarget;
  rel?: string;
  size?: LinkSize;
  disabled?: boolean;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "links",
  props.size ? `links--${props.size}` : null,
  props.disabled ? "links--disabled" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <a :class="classNames" :href="props.href" :target="props.target" :rel="props.rel" :data-testid="props['data-testid']">
    <slot />
  </a>
</template>

// packages/ds-react/src/components/Links/Links.tsx
// @generated:start imports
import { type ReactNode } from "react";
import "./Links.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type LinkTarget = "_self" | "_blank" | "_parent" | "_top";

export type LinkSize = "small" | "medium" | "large";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface LinksProps {
  href?: string;
  target?: LinkTarget;
  rel?: string;
  size?: LinkSize;
  disabled?: boolean;
  className?: string;
  "data-testid"?: string;
  children?: ReactNode;
}
// @generated:end

// @generated:start subcomponents

// @generated:end

// @generated:start component
export function Links({
  size,
  disabled,
  className,
  "data-testid": testId,
  children,
  href,
  target,
  rel,
  ...rest
}: LinksProps) {
  const classNames = [
    "links",
    size && `links--${size}`,
    disabled && "links--disabled",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <a className={`${classNames}`} href={href} target={target} rel={rel} data-testid={testId} {...rest}>
    {children}
  </a>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end
