// packages/ds-svelte/src/components/Status/Status.svelte
<script lang="ts">
// @generated:start imports
import Icon from "../Icon/Icon.svelte";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type StatusIntent = "info" | "success" | "warning" | "danger" | "error";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  status: StatusIntent;
  class?: string;
  children?: import('svelte').Snippet;
}

let { status, class: className, children }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "status",
    status ? `status--${status}` : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<span class={classes} data-fsds-component="status" data-fsds-box="">
  <Icon class={'status__icon'} size="sm" name={(status === "info" ? "info" : (status === "success" ? "check" : (status === "warning" ? "triangle-alert" : (status === "danger" ? "triangle-alert" : "triangle-alert"))))} />
  <span class={'status__label'}>
    {@render children?.()}
  </span>
</span>

// packages/ds-angular/src/components/Status/Status.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass } from "@angular/common";
import { IconComponent } from "../Icon/Icon.component.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type StatusIntent = "info" | "success" | "warning" | "danger" | "error";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-status",
  standalone: true,
  imports: [NgClass, IconComponent],
  host: { "data-fsds-component": "status" },
  template: `<span [ngClass]="classes()" data-fsds-box="">
  <fsds-icon [ngClass]="'status__icon'" size="sm" [name]="(status === 'info' ? 'info' : (status === 'success' ? 'check' : (status === 'warning' ? 'triangle-alert' : (status === 'danger' ? 'triangle-alert' : 'triangle-alert'))))"></fsds-icon>
  <span [ngClass]="'status__label'">
    <ng-content />
  </span>
</span>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class StatusComponent {
  @Input() status!: StatusIntent;
  @Input() class?: string;

  classes(): string {
    return [
      "status",
      this.status ? `status--${this.status}` : null,
      this.class,
    ].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end
