// packages/ds-vue/src/components/SlinkyCursor/SlinkyCursor.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "slinky-cursor",
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" :data-testid="props['data-testid']">
    <div :class="'slinky-cursor__pest'"></div>
  </div>
</template>

// packages/ds-svelte/src/components/SlinkyCursor/SlinkyCursor.svelte
<script lang="ts">
// @generated:start imports

// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  class?: string;
}

let { class: className }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "slinky-cursor",
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes}>
  <div class={'slinky-cursor__pest'}></div>
</div>
