// packages/ds-vue/src/components/Button/Button.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import Spinner from "../Spinner/Spinner.vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type ButtonSize = "small" | "medium" | "large";
export type ButtonVariant = "primary" | "secondary" | "tertiary" | "ghost" | "destructive" | "outline";
export type ButtonType = "button" | "submit" | "reset";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  size?: ButtonSize;
  variant?: ButtonVariant;
  type?: ButtonType;
  loading?: boolean;
  disabled?: boolean;
  ariaLabel?: string;
  ariaExpanded?: boolean;
  ariaPressed?: boolean;
  title?: string;
  onClick?: () => void;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  size: "medium",
  variant: "primary",
  type: "button",
  loading: undefined,
  disabled: undefined,
  ariaExpanded: undefined,
  ariaPressed: undefined,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "button",
  props.size ? `button--${props.size}` : null,
  props.variant ? `button--${props.variant}` : null,
  props.disabled ? "button--disabled" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <button :class="classNames" @click="props.onClick?.()" :type="props.type" :disabled="props.disabled" :aria-label="props.ariaLabel" :aria-expanded="props.ariaExpanded" :aria-pressed="props.ariaPressed" :aria-busy="props.loading" :data-testid="props['data-testid']" data-fsds-component="button" data-fsds-box="">
    <Spinner v-if="props.loading" :class="'button__spinner'" size="sm" :inline="props.loading" :ariaHidden="props.loading" />
    <span :class="'button__loadingText'">
      <slot />
    </span>
  </button>
</template>

// packages/ds-svelte/src/components/Button/Button.svelte
<script lang="ts">
// @generated:start imports
import Spinner from "../Spinner/Spinner.svelte";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type ButtonSize = "small" | "medium" | "large";
type ButtonVariant = "primary" | "secondary" | "tertiary" | "ghost" | "destructive" | "outline";
type ButtonType = "button" | "submit" | "reset";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  size?: ButtonSize;
  variant?: ButtonVariant;
  type?: ButtonType;
  loading?: boolean;
  disabled?: boolean;
  ariaLabel?: string;
  ariaExpanded?: boolean;
  ariaPressed?: boolean;
  title?: string;
  onClick?: () => void;
  class?: string;
  children?: import('svelte').Snippet;
}

let { size = "medium", variant = "primary", type = "button", loading, disabled, ariaLabel, ariaExpanded, ariaPressed, title, onClick, class: className, children }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "button",
    size ? `button--${size}` : null,
    variant ? `button--${variant}` : null,
    disabled ? "button--disabled" : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<button class={classes} onclick={onClick} type={type} disabled={disabled} aria-label={ariaLabel} aria-expanded={ariaExpanded} aria-pressed={ariaPressed} aria-busy={loading} data-fsds-component="button" data-fsds-box="">
  {#if loading}
  <Spinner class={'button__spinner'} size="sm" inline={loading} ariaHidden={loading} />
  {/if}
  <span class={'button__loadingText'}>
    {@render children?.()}
  </span>
</button>
