// packages/ds-svelte/src/components/Markdown/Markdown.svelte
<script lang="ts">
// @generated:start imports
import { parseMarkdown, type MarkdownBlock, type MarkdownMark } from "../../primitives/markdown/markdown.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  content: string;
  class?: string;
}

let { content, class: className }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "markdown",
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} data-fsds-component="markdown" data-fsds-box="">{#each parseMarkdown(content ?? "") as block, blockIndex}{@render markdownBlock(block, blockIndex)}{/each}</div>

{#snippet markdownBlock(block: MarkdownBlock, blockIndex: number)}
  {#if block.kind === "heading"}
    <h2 class="markdown__heading" data-block-kind="heading" data-block-kind-level={block.level}>{#each block.children as mark, markIndex}{@render markdownMark(mark, markIndex)}{/each}</h2>
  {:else if block.kind === "paragraph"}
    <p class="markdown__paragraph" data-block-kind="paragraph">{#each block.children as mark, markIndex}{@render markdownMark(mark, markIndex)}{/each}</p>
  {:else if block.kind === "list"}
    {#if block.ordered}
      <ol class="markdown__orderedList" data-block-kind="orderedList">{#each block.items as item, itemIndex}{@render markdownBlock(item, itemIndex)}{/each}</ol>
    {:else}
      <ul class="markdown__unorderedList" data-block-kind="unorderedList">{#each block.items as item, itemIndex}{@render markdownBlock(item, itemIndex)}{/each}</ul>
    {/if}
  {:else if block.kind === "listItem"}
    <li class="markdown__listItem" data-block-kind="listItem">{#each block.children as mark, markIndex}{@render markdownMark(mark, markIndex)}{/each}</li>
  {:else if block.kind === "codeBlock"}
    <pre class="markdown__codeBlock" data-block-kind="codeBlock" data-language={block.language}>{block.text}</pre>
  {:else if block.kind === "blockquote"}
    <blockquote class="markdown__blockquote" data-block-kind="blockquote">{#each block.children as mark, markIndex}{@render markdownMark(mark, markIndex)}{/each}</blockquote>
  {/if}
{/snippet}

{#snippet markdownMark(mark: MarkdownMark, markIndex: number)}
  {#if mark.kind === "text"}
    {mark.text}
  {:else if mark.kind === "code"}
    <code class="markdown__code" data-mark-kind="code">{mark.text}</code>
  {:else if mark.kind === "emphasis"}
    <em class="markdown__emphasis" data-mark-kind="emphasis">{#each mark.children as child, childIndex}{@render markdownMark(child, childIndex)}{/each}</em>
  {:else if mark.kind === "strong"}
    <strong class="markdown__strong" data-mark-kind="strong">{#each mark.children as child, childIndex}{@render markdownMark(child, childIndex)}{/each}</strong>
  {:else if mark.kind === "link"}
    {#if mark.href === null}
      <span>{#each mark.children as child, childIndex}{@render markdownMark(child, childIndex)}{/each}</span>
    {:else}
      <a class="markdown__link" data-mark-kind="link" href={mark.href}>{#each mark.children as child, childIndex}{@render markdownMark(child, childIndex)}{/each}</a>
    {/if}
  {/if}
{/snippet}

// packages/ds-vue/src/components/Markdown/Markdown.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { parseMarkdown, type MarkdownBlock, type MarkdownMark } from "../../primitives/markdown/markdown.js";
import { h, Fragment, defineComponent, type VNode } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  content: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = defineProps<Props>();
// @generated:end

// @generated:start markdownHelpers
function renderMarkdownBlock(block: MarkdownBlock): VNode {
  switch (block.kind) {
    case "heading":
      return h("h2", { class: "markdown__heading", "data-block-kind": "heading", "data-block-kind-level": block.level }, block.children.map(renderMarkdownMark));
    case "paragraph":
      return h("p", { class: "markdown__paragraph", "data-block-kind": "paragraph" }, block.children.map(renderMarkdownMark));
    case "list":
      return block.ordered
        ? h("ol", { class: "markdown__orderedList", "data-block-kind": "orderedList" }, block.items.map(renderMarkdownBlock))
        : h("ul", { class: "markdown__unorderedList", "data-block-kind": "unorderedList" }, block.items.map(renderMarkdownBlock));
    case "listItem":
      return h("li", { class: "markdown__listItem", "data-block-kind": "listItem" }, block.children.map(renderMarkdownMark));
    case "codeBlock":
      return h("pre", { class: "markdown__codeBlock", "data-block-kind": "codeBlock", "data-language": block.language }, block.text);
    case "blockquote":
      return h("blockquote", { class: "markdown__blockquote", "data-block-kind": "blockquote" }, block.children.map(renderMarkdownMark));
  }
}

function renderMarkdownMark(mark: MarkdownMark): VNode {
  switch (mark.kind) {
    case "text":
      return h("span", mark.text);
    case "code":
      return h("code", { class: "markdown__code", "data-mark-kind": "code" }, mark.text);
    case "emphasis":
      return h("em", { class: "markdown__emphasis", "data-mark-kind": "emphasis" }, mark.children.map(renderMarkdownMark));
    case "strong":
      return h("strong", { class: "markdown__strong", "data-mark-kind": "strong" }, mark.children.map(renderMarkdownMark));
    case "link":
      return mark.href === null
        ? h("span", mark.children.map(renderMarkdownMark))
        : h("a", { class: "markdown__link", "data-mark-kind": "link", href: mark.href }, mark.children.map(renderMarkdownMark));
  }
}

// A defineComponent-wrapped local component is the unambiguous Vue
// shape for template-mounted recursive render trees.
const MarkdownTree = defineComponent({
  setup: () => () => h(Fragment, null, parseMarkdown(props.content ?? "").map(renderMarkdownBlock)),
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "markdown",
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" :data-testid="props['data-testid']" data-fsds-component="markdown" data-fsds-box="">
    <MarkdownTree />
  </div>
</template>
