// packages/ds-svelte/src/components/ToggleSwitch/ToggleSwitch.svelte
<script lang="ts">
// @generated:start imports
import { useToggleSwitch } from "./useToggleSwitch.svelte.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type ToggleSwitchSize = "small" | "medium" | "large";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  checked?: boolean;
  defaultChecked?: boolean;
  onChange?: (checked: boolean) => void;
  size?: ToggleSwitchSize;
  disabled?: boolean;
  ariaLabel?: string;
  ariaDescribedby?: string;
  class?: string;
}

let { checked, defaultChecked, onChange, size = "medium", disabled, ariaLabel, ariaDescribedby, class: className }: Props = $props();
// @generated:end

// @generated:start hook
const behavior = useToggleSwitch({
  checked: () => checked,
  defaultChecked: () => defaultChecked,
  onChange: () => onChange,
});
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "toggle-switch",
    size ? `toggle-switch--${size}` : null,
    behavior.checked ? "toggle-switch--checked" : null,
    disabled ? "toggle-switch--disabled" : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<button class={classes} type="button" onclick={() => behavior.setChecked(!behavior.checked)} aria-checked={behavior.checked} aria-label={ariaLabel} aria-describedby={ariaDescribedby} disabled={disabled} data-fsds-component="toggle-switch" role="switch"></button>

// packages/ds-angular/src/components/ToggleSwitch/ToggleSwitch.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass } from "@angular/common";
import { useToggleSwitch } from "./useToggleSwitch.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type ToggleSwitchSize = "small" | "medium" | "large";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-toggle-switch",
  standalone: true,
  imports: [NgClass],
  host: { "data-fsds-component": "toggle-switch" },
  template: `<button [ngClass]="classes()" type="button" (click)="behavior.setChecked(!behavior.checked())" [attr.aria-checked]="behavior.checked()" [attr.aria-label]="ariaLabel" [attr.aria-describedby]="ariaDescribedby" [disabled]="disabled"></button>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ToggleSwitchComponent {
  @Input() checked?: boolean;
  @Input() defaultChecked?: boolean;
  @Input() onChange?: (checked: boolean) => void;
  @Input() size?: ToggleSwitchSize = "medium";
  @Input() disabled?: boolean;
  @Input() ariaLabel?: string;
  @Input() ariaDescribedby?: string;
  @Input() class?: string;

  private destroyRef = inject(DestroyRef);
  protected behavior = useToggleSwitch({
    checked: () => this.checked,
    defaultChecked: this.defaultChecked,
    onChange: (v) => this.onChange?.(v),
    destroyRef: this.destroyRef,
  });

  classes = computed(() =>
    [
      "toggle-switch",
      (this.size ?? "medium") ? `toggle-switch--${(this.size ?? "medium")}` : null,
      this.behavior.checked() ? "toggle-switch--checked" : null,
      this.disabled ? "toggle-switch--disabled" : null,
      this.class,
    ].filter(Boolean).join(" "),
  );
}
// @generated:end

// @custom:start trailing

// @custom:end
