// packages/ds-angular/src/components/Dialog/Dialog.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass, NgIf } from "@angular/common";
import { StackComponent } from "../../primitives/index.js";
import { useDialog } from "./useDialog.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type DialogSize = "sm" | "md" | "lg" | "xl" | "full";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-dialog",
  standalone: true,
  imports: [NgClass, NgIf],
  template: `<div [ngClass]="classes()">
  <ng-container *ngIf="behavior.openness()">
    <div [ngClass]="'dialog__backdrop'" aria-hidden="true" role="presentation" (click)="closeOnBackdropClick !== false && behavior.setOpenness(false)"></div>
  </ng-container>
  <ng-container *ngIf="behavior.openness()">
    <div [ngClass]="'dialog__modal'" role="dialog" aria-modal="true" aria-labelledby="dialog-title-id" aria-describedby="dialog-body-id">
      <div [ngClass]="'dialog__header'">
        <h2 [ngClass]="'dialog__title'">
          <ng-content select="[slot=title]" />
        </h2>
        <button [ngClass]="'dialog__closeButton'" type="button" aria-label="Close dialog" (click)="handleOpennessChange($event)"></button>
      </div>
      <div [ngClass]="'dialog__body'">
        <ng-content />
      </div>
      <div [ngClass]="'dialog__footer'"></div>
    </div>
  </ng-container>
</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DialogComponent {
  @Input() open?: boolean;
  @Input() defaultOpen?: boolean;
  @Input() onOpenChange?: (open: boolean) => void;
  @Input() modal?: boolean = true;
  @Input() size?: DialogSize = "md";
  @Input() dismissible?: boolean = true;
  @Input() closeOnEscape?: boolean = true;
  @Input() closeOnBackdropClick?: boolean = true;
  @Input() initialFocus?: string;
  @Input() returnFocus?: string;
  @Input() class?: string;

  private destroyRef = inject(DestroyRef);
  protected behavior = useDialog({
    open: () => this.open,
    defaultOpen: this.defaultOpen,
    onOpenChange: (v) => this.onOpenChange?.(v),
    closeOnEscape: this.closeOnEscape,
    closeOnBackdropClick: this.closeOnBackdropClick,
    destroyRef: this.destroyRef,
  });

  classes = computed(() =>
    [
      "dialog",
      this.size ? `dialog--${this.size}` : null,
      this.class,
    ].filter(Boolean).join(" "),
  );

  protected handleOpennessChange(event: Event): void {
    this.behavior.setOpenness((event.target as HTMLInputElement).checked);
  }
}

@Component({
  selector: "fsds-dialog-header",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="header" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DialogHeaderComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["dialog__header", this.class].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-dialog-title",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="h3" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DialogTitleComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["dialog__title", this.class].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-dialog-body",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DialogBodyComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["dialog__body", this.class].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-dialog-footer",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="footer" variant="horizontal" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DialogFooterComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["dialog__footer", this.class].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-svelte/src/components/Dialog/Dialog.svelte
<script lang="ts">
// @generated:start imports
import { useDialog } from "./useDialog.svelte.js";
import { portal } from "../../primitives/index.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type DialogSize = "sm" | "md" | "lg" | "xl" | "full";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  modal?: boolean;
  size?: DialogSize;
  dismissible?: boolean;
  closeOnEscape?: boolean;
  closeOnBackdropClick?: boolean;
  initialFocus?: string;
  returnFocus?: string;
  class?: string;
  children?: import('svelte').Snippet;
  title?: import('svelte').Snippet;
}

let { open, defaultOpen, onOpenChange, modal = true, size = "md", dismissible = true, closeOnEscape = true, closeOnBackdropClick = true, initialFocus, returnFocus, class: className, children, title }: Props = $props();
// @generated:end

// @generated:start hook
const behavior = useDialog({
  open: () => open,
  defaultOpen: () => defaultOpen,
  onOpenChange: () => onOpenChange,
  closeOnEscape: () => closeOnEscape,
  closeOnBackdropClick: () => closeOnBackdropClick,
});
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "dialog",
    size ? `dialog--${size}` : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @generated:start fieldAssociation
const instanceId = $props.id();
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} aria-labelledby={title ? `${instanceId}-title` : undefined} aria-describedby={`${instanceId}-body`} data-fsds-component="dialog" use:portal={{ enabled: true }} role="dialog" onclick={(e) => { if (e.target === e.currentTarget) { closeOnBackdropClick !== false && behavior.setOpenness(false); } }}>
  {#if behavior.openness}
  <div class={'dialog__backdrop'} aria-hidden="true"></div>
  {/if}
  {#if behavior.openness}
  <div class={'dialog__modal'} role="dialog" aria-modal="true" aria-labelledby="dialog-title-id" aria-describedby="dialog-body-id">
    <div class={'dialog__header'}>
      <h2 class={'dialog__title'} id={`${instanceId}-title`}>
        {@render title?.()}
      </h2>
      <button class={'dialog__closeButton'} type="button" aria-label="Close dialog" onclick={() => behavior.setOpenness(!behavior.openness)}></button>
    </div>
    <div class={'dialog__body'} id={`${instanceId}-body`}>
      {@render children?.()}
    </div>
    <div class={'dialog__footer'}></div>
  </div>
  {/if}
</div>
