// packages/ds-svelte/src/components/List/List.svelte
<script lang="ts">
// @generated:start imports

// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type ListElement = "ul" | "ol" | "dl";
type ListVariant = "default" | "unstyled" | "inline" | "divided" | "spaced";
type ListMarker = "default" | "none" | "disc" | "circle" | "square" | "decimal" | "alpha" | "roman";
type ListSpacing = "none" | "sm" | "md" | "lg";
type ListSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  as?: ListElement;
  variant?: ListVariant;
  marker?: ListMarker;
  spacing?: ListSpacing;
  size?: ListSize;
  class?: string;
  children?: import('svelte').Snippet;
}

let { as, variant, marker, spacing, size, class: className, children }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "list",
    as ? `list--${as}` : null,
    variant ? `list--${variant}` : null,
    marker ? `list--${marker}` : null,
    spacing ? `list--${spacing}` : null,
    size ? `list--${size}` : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<ul class={classes}>
  {@render children?.()}
</ul>

// packages/ds-angular/src/components/List/List.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass } from "@angular/common";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type ListElement = "ul" | "ol" | "dl";
export type ListVariant = "default" | "unstyled" | "inline" | "divided" | "spaced";
export type ListMarker = "default" | "none" | "disc" | "circle" | "square" | "decimal" | "alpha" | "roman";
export type ListSpacing = "none" | "sm" | "md" | "lg";
export type ListSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-list",
  standalone: true,
  imports: [NgClass],
  template: `<ul [ngClass]="classes()">
  <ng-content />
</ul>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ListComponent {
  @Input() as?: ListElement;
  @Input() variant?: ListVariant = "default";
  @Input() marker?: ListMarker = "default";
  @Input() spacing?: ListSpacing;
  @Input() size?: ListSize;
  @Input() class?: string;

  classes(): string {
    return [
      "list",
      this.as ? `list--${this.as}` : null,
      this.variant ? `list--variant-${this.variant}` : null,
      this.marker ? `list--marker-${this.marker}` : null,
      this.spacing ? `list--spacing-${this.spacing}` : null,
      this.size ? `list--size-${this.size}` : null,
      this.class,
    ].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end
