// packages/ds-react/src/components/Image/Image.tsx
// @generated:start imports
import { type ReactNode } from "react";
import "./Image.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type ImageAspectRatio = "square" | "video" | "photo" | "wide" | "portrait";

export type ImageObjectFit = "cover" | "contain" | "fill" | "scale-down" | "none";

export type ImageLoading = "lazy" | "eager";

export type ImageRadius = "none" | "sm" | "md" | "lg" | "full";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface ImageProps {
  src?: string;
  alt: string;
  width?: number;
  height?: number;
  aspectRatio?: ImageAspectRatio;
  objectFit?: ImageObjectFit;
  objectPosition?: string;
  loading?: ImageLoading;
  sizes?: string;
  radius?: ImageRadius;
  showPlaceholder?: boolean;
  fallbackSrc?: string;
  size?: string;
  className?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start subcomponents

// @generated:end

// @generated:start component
export function Image({
  radius,
  size,
  className,
  "data-testid": testId,
  src,
  alt,
  width,
  height,
  aspectRatio,
  objectFit,
  objectPosition,
  loading,
  sizes,
  showPlaceholder,
  fallbackSrc,
  ...rest
}: ImageProps) {
  const classNames = [
    "image",
    radius && `image--${radius}`,
    size && `image--${size}`,
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <img className={`${classNames}`} src={src} alt={alt} width={width} height={height} loading={loading} sizes={sizes} role="img" data-testid={testId} {...rest} />
  );
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/Image/Image.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type ImageAspectRatio = "square" | "video" | "photo" | "wide" | "portrait";
export type ImageObjectFit = "cover" | "contain" | "fill" | "scale-down" | "none";
export type ImageLoading = "lazy" | "eager";
export type ImageRadius = "none" | "sm" | "md" | "lg" | "full";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  src?: string;
  alt: string;
  width?: number;
  height?: number;
  aspectRatio?: ImageAspectRatio;
  objectFit?: ImageObjectFit;
  objectPosition?: string;
  loading?: ImageLoading;
  sizes?: string;
  radius?: ImageRadius;
  showPlaceholder?: boolean;
  fallbackSrc?: string;
  size?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "image",
  props.radius ? `image--${props.radius}` : null,
  props.size ? `image--${props.size}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <img :class="classNames" :src="props.src" :alt="props.alt" :width="props.width" :height="props.height" :loading="props.loading" :sizes="props.sizes" role="img" :data-testid="props['data-testid']" />
</template>
