// packages/ds-vue/src/components/Command/Command.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useCommand } from "./useCommand.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  search?: string;
  defaultSearch?: string;
  onSearchChange?: (value: string) => void;
  placeholder?: string;
  emptyMessage?: string;
  label?: string;
  shouldFilter?: boolean;
  filter?: ((value: string, search: string) => number) | undefined;
  class?: string;
  "data-testid"?: string;
  "aria-label"?: string;
  "aria-labelledby"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  open: undefined,
  defaultOpen: undefined,
  placeholder: "Search...",
  emptyMessage: "No results found.",
  label: "Command palette",
  shouldFilter: true,
});
// @generated:end

// @generated:start hook
const behavior = useCommand({
  open: () => props.open,
  defaultOpen: props.defaultOpen,
  onOpenChange: props.onOpenChange,
  search: () => props.search,
  defaultSearch: props.defaultSearch,
  onSearchChange: props.onSearchChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "command",
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" role="dialog" :data-testid="props['data-testid']" @click.self="behavior.setOpen(false)">
    <div v-if="behavior.open.value" :class="'command__overlay'" aria-hidden="true"></div>
    <div v-if="behavior.open.value" :class="'command__dialog'" role="dialog" aria-modal="true" :aria-label="props.label">
      <div :class="'command__inputWrapper'">
        <span :class="'command__searchIcon'" aria-hidden="true"></span>
        <input :class="'command__input'" type="search" role="combobox" aria-autocomplete="list" aria-controls="fsds-command-listbox" @change="(e) => behavior.setSearch((e.target as HTMLInputElement).value)" :aria-expanded="behavior.open.value" :placeholder="props.placeholder" :value="behavior.search.value" />
      </div>
      <div :class="'command__list'" role="listbox" id="fsds-command-listbox">
        <div :class="'command__empty'"></div>
        <div :class="'command__group'">
          <div :class="'command__groupHeading'"></div>
          <div :class="'command__groupItems'">
            <div :class="'command__item'" role="option">
              <span :class="'command__itemIcon'"></span>
              <div :class="'command__itemContent'">
                <span :class="'command__itemLabel'"></span>
                <span :class="'command__itemDescription'"></span>
              </div>
            </div>
          </div>
        </div>
        <div :class="'command__separator'" role="separator" aria-hidden="true"></div>
      </div>
    </div>
  </div>
</template>

// packages/ds-react/src/components/Command/Command.tsx
// @generated:start imports
import { type HTMLAttributes, type ReactNode } from "react";
import { Stack } from "../../primitives";
import { useCommand } from "./useCommand";
import "./Command.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface CommandProps extends Omit<HTMLAttributes<HTMLDivElement>, "aria-label" | "aria-labelledby" | "children" | "className" | "data-testid" | "defaultOpen" | "defaultSearch" | "emptyMessage" | "filter" | "label" | "onOpenChange" | "onSearchChange" | "open" | "placeholder" | "search" | "shouldFilter"> {
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  search?: string;
  defaultSearch?: string;
  onSearchChange?: (value: string) => void;
  placeholder?: string;
  emptyMessage?: string;
  label?: string;
  shouldFilter?: boolean;
  filter?: ((value: string, search: string) => number) | undefined;
  className?: string;
  "data-testid"?: string;
  "aria-label"?: string;
  "aria-labelledby"?: string;
}
// @generated:end

// @generated:start subcomponents
export interface CommandListProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function CommandList({
  children,
  className,
  "data-testid": testId,
}: CommandListProps) {
  const classNames = ["command__list", className].filter(Boolean).join(" ");
  return (
    <Stack as="ul" variant="horizontal" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface CommandGroupProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function CommandGroup({
  children,
  className,
  "data-testid": testId,
}: CommandGroupProps) {
  const classNames = ["command__group", className].filter(Boolean).join(" ");
  return (
    <Stack className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface CommandItemProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function CommandItem({
  children,
  className,
  "data-testid": testId,
}: CommandItemProps) {
  const classNames = ["command__item", className].filter(Boolean).join(" ");
  return (
    <Stack as="li" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}
// @generated:end

// @generated:start component
export function Command({
  open: controlledOpen,
  defaultOpen,
  onOpenChange,
  search: controlledSearch,
  defaultSearch,
  onSearchChange,
  className,
  "data-testid": testId,
  "aria-label": ariaLabel,
  "aria-labelledby": ariaLabelledBy,
  placeholder = "Search...",
  emptyMessage = "No results found.",
  label = "Command palette",
  shouldFilter = true,
  filter,
  ...rest
}: CommandProps) {
  const { open, setOpen, search, setSearch } = useCommand({
    open: controlledOpen,
    defaultOpen,
    onOpenChange,
    search: controlledSearch,
    defaultSearch,
    onSearchChange,
  });

  const classNames = [
    "command",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <div className={`${classNames}`} role="dialog" data-testid={testId} onClick={(e) => { if (e.target === e.currentTarget) setOpen(false); }} {...rest}>
    {open && (
      <div className="command__overlay" aria-hidden="true" />
    )}
    {open && (
      <div className="command__dialog" role="dialog" aria-modal="true" aria-label={label} aria-labelledby={ariaLabelledBy}>
        <div className="command__inputWrapper">
          <span className="command__searchIcon" aria-hidden="true" />
          <input className="command__input" type="search" role="combobox" aria-autocomplete="list" aria-controls="fsds-command-listbox" aria-expanded={open} placeholder={placeholder} value={search} onChange={(e) => setSearch(e.target.value)} />
        </div>
        <div className="command__list" role="listbox" id="fsds-command-listbox">
          <div className="command__empty" />
          <div className="command__group">
            <div className="command__groupHeading" />
            <div className="command__groupItems">
              <div className="command__item" role="option">
                <span className="command__itemIcon" />
                <div className="command__itemContent">
                  <span className="command__itemLabel" />
                  <span className="command__itemDescription" />
                </div>
              </div>
            </div>
          </div>
          <div className="command__separator" role="separator" aria-hidden="true" />
        </div>
      </div>
    )}
  </div>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end
