// packages/ds-vue/src/components/Label/Label.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  htmlFor?: string;
  form?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "label",
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <label :class="classNames" :for="props.htmlFor" :form="props.form" :data-testid="props['data-testid']">
    <slot />
  </label>
</template>

// packages/ds-react/src/components/Label/Label.tsx
// @generated:start imports
import { type ReactNode } from "react";
import "./Label.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface LabelProps {
  htmlFor?: string;
  form?: string;
  className?: string;
  "data-testid"?: string;
  children?: ReactNode;
}
// @generated:end

// @generated:start subcomponents

// @generated:end

// @generated:start component
export function Label({
  className,
  "data-testid": testId,
  children,
  htmlFor,
  form,
  ...rest
}: LabelProps) {
  const classNames = [
    "label",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <label className={`${classNames}`} htmlFor={htmlFor} form={form} data-testid={testId} {...rest}>
    {children}
  </label>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end
