// packages/ds-svelte/src/components/CodeSnippet/CodeSnippet.svelte
<script lang="ts">
// @generated:start imports

// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type CodeSnippetElement = "code" | "kbd" | "samp";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  text: string;
  as?: CodeSnippetElement;
  class?: string;
}

let { text, as = "code", class: className }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "code-snippet",
    as ? `code-snippet--${as}` : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<svelte:element this={as ?? "code"} class={classes} spellcheck="false" data-fsds-component="code-snippet" data-fsds-box="">{text}</svelte:element>

// packages/ds-angular/src/components/CodeSnippet/CodeSnippet.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass, NgSwitch, NgSwitchCase } from "@angular/common";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type CodeSnippetElement = "code" | "kbd" | "samp";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-code-snippet",
  standalone: true,
  imports: [NgClass, NgSwitch, NgSwitchCase],
  host: { "data-fsds-component": "code-snippet" },
  template: `<ng-container [ngSwitch]="this.as || 'code'">
  <code [ngClass]="classes()" spellcheck="false" data-fsds-box="" *ngSwitchCase="'code'">
    {{ text }}
  </code>
  <kbd [ngClass]="classes()" spellcheck="false" data-fsds-box="" *ngSwitchCase="'kbd'">
    {{ text }}
  </kbd>
  <samp [ngClass]="classes()" spellcheck="false" data-fsds-box="" *ngSwitchCase="'samp'">
    {{ text }}
  </samp>
</ng-container>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CodeSnippetComponent {
  @Input() text!: string;
  @Input() as?: CodeSnippetElement = "code";
  @Input() class?: string;

  classes(): string {
    return [
      "code-snippet",
      (this.as ?? "code") ? `code-snippet--${(this.as ?? "code")}` : null,
      this.class,
    ].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end
