// packages/ds-svelte/src/components/Command/Command.svelte
<script lang="ts">
// @generated:start imports
import { useCommand } from "./useCommand.svelte.js";
import { portal } from "../../primitives/index.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  search?: string;
  defaultSearch?: string;
  onSearchChange?: (value: string) => void;
  placeholder?: string;
  emptyMessage?: string;
  label?: string;
  shouldFilter?: boolean;
  filter?: ((value: string, search: string) => number) | undefined;
  class?: string;
}

let { open, defaultOpen, onOpenChange, search, defaultSearch, onSearchChange, placeholder = "Search...", emptyMessage = "No results found.", label = "Command palette", shouldFilter = true, filter, class: className }: Props = $props();
// @generated:end

// @generated:start hook
const behavior = useCommand({
  open: () => open,
  defaultOpen: () => defaultOpen,
  onOpenChange: () => onOpenChange,
  search: () => search,
  defaultSearch: () => defaultSearch,
  onSearchChange: () => onSearchChange,
});
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "command",
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} use:portal={{ enabled: true }} role="dialog" onclick={(e) => { if (e.target === e.currentTarget) { behavior.setOpen(false); } }}>
  {#if behavior.open}
  <div class={'command__overlay'} aria-hidden="true"></div>
  {/if}
  {#if behavior.open}
  <div class={'command__dialog'} role="dialog" aria-modal="true" aria-label={label}>
    <div class={'command__inputWrapper'}>
      <span class={'command__searchIcon'} aria-hidden="true"></span>
      <input class={'command__input'} type="search" role="combobox" aria-autocomplete="list" aria-controls="fsds-command-listbox" onchange={(e) => behavior.setSearch((e.currentTarget as HTMLInputElement).value)} aria-expanded={behavior.open} placeholder={placeholder} value={behavior.search} />
    </div>
    <div class={'command__list'} role="listbox" id="fsds-command-listbox">
      <div class={'command__empty'}></div>
      <div class={'command__group'}>
        <div class={'command__groupHeading'}></div>
        <div class={'command__groupItems'}>
          <div class={'command__item'} role="option">
            <span class={'command__itemIcon'}></span>
            <div class={'command__itemContent'}>
              <span class={'command__itemLabel'}></span>
              <span class={'command__itemDescription'}></span>
            </div>
          </div>
        </div>
      </div>
      <div class={'command__separator'} role="separator" aria-hidden="true"></div>
    </div>
  </div>
  {/if}
</div>

// packages/ds-angular/src/components/Command/Command.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass, NgIf } from "@angular/common";
import { StackComponent } from "../../primitives/index.js";
import { useCommand } from "./useCommand.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-command",
  standalone: true,
  imports: [NgClass, NgIf],
  template: `<div [ngClass]="classes()">
  <ng-container *ngIf="behavior.open()">
    <div [ngClass]="'command__overlay'" aria-hidden="true" role="presentation" (click)="behavior.setOpen(false)"></div>
  </ng-container>
  <ng-container *ngIf="behavior.open()">
    <div [ngClass]="'command__dialog'" role="dialog" aria-modal="true" [attr.aria-label]="label">
      <div [ngClass]="'command__inputWrapper'">
        <span [ngClass]="'command__searchIcon'" aria-hidden="true"></span>
        <input [ngClass]="'command__input'" type="search" role="combobox" aria-autocomplete="list" aria-controls="fsds-command-listbox" (change)="handleSearchChange($event)" [attr.aria-expanded]="behavior.open()" [placeholder]="placeholder" [value]="behavior.search()" />
      </div>
      <div [ngClass]="'command__list'" role="listbox" id="fsds-command-listbox">
        <div [ngClass]="'command__empty'"></div>
        <div [ngClass]="'command__group'">
          <div [ngClass]="'command__groupHeading'"></div>
          <div [ngClass]="'command__groupItems'">
            <div [ngClass]="'command__item'" role="option">
              <span [ngClass]="'command__itemIcon'"></span>
              <div [ngClass]="'command__itemContent'">
                <span [ngClass]="'command__itemLabel'"></span>
                <span [ngClass]="'command__itemDescription'"></span>
              </div>
            </div>
          </div>
        </div>
        <div [ngClass]="'command__separator'" role="separator" aria-hidden="true"></div>
      </div>
    </div>
  </ng-container>
</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CommandComponent {
  @Input() open?: boolean;
  @Input() defaultOpen?: boolean;
  @Input() onOpenChange?: (open: boolean) => void;
  @Input() search?: string;
  @Input() defaultSearch?: string;
  @Input() onSearchChange?: (value: string) => void;
  @Input() placeholder?: string = "Search...";
  @Input() emptyMessage?: string = "No results found.";
  @Input() label?: string = "Command palette";
  @Input() shouldFilter?: boolean = true;
  @Input() filter?: ((value: string, search: string) => number) | undefined;
  @Input() class?: string;

  private destroyRef = inject(DestroyRef);
  protected behavior = useCommand({
    open: () => this.open,
    defaultOpen: this.defaultOpen,
    onOpenChange: (v) => this.onOpenChange?.(v),
    search: () => this.search,
    defaultSearch: this.defaultSearch,
    onSearchChange: (v) => this.onSearchChange?.(v),
    destroyRef: this.destroyRef,
  });

  classes = computed(() =>
    [
      "command",
      this.class,
    ].filter(Boolean).join(" "),
  );

  protected handleSearchChange(event: Event): void {
    this.behavior.setSearch((event.target as HTMLInputElement).value);
  }
}

@Component({
  selector: "fsds-command-list",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="ul" variant="horizontal" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CommandListComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["command__list", this.class].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-command-group",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CommandGroupComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["command__group", this.class].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-command-item",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="li" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CommandItemComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["command__item", this.class].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end
