// packages/ds-vue/src/components/CodeSnippet/CodeSnippet.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type CodeSnippetElement = "code" | "kbd" | "samp";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  text: string;
  as?: CodeSnippetElement;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  as: "code",
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "code-snippet",
  props.as ? `code-snippet--${props.as}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <component :is="props.as ?? 'code'" :class="classNames" spellcheck="false" :data-testid="props['data-testid']" data-fsds-component="code-snippet" data-fsds-box="">
    {{ props.text }}
  </component>
</template>

// packages/ds-svelte/src/components/CodeSnippet/CodeSnippet.svelte
<script lang="ts">
// @generated:start imports

// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type CodeSnippetElement = "code" | "kbd" | "samp";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  text: string;
  as?: CodeSnippetElement;
  class?: string;
}

let { text, as = "code", class: className }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "code-snippet",
    as ? `code-snippet--${as}` : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<svelte:element this={as ?? "code"} class={classes} spellcheck="false" data-fsds-component="code-snippet" data-fsds-box="">{text}</svelte:element>
