// packages/ds-vue/src/components/SlinkyCursor/SlinkyCursor.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "slinky-cursor",
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" :data-testid="props['data-testid']">
    <div :class="'slinky-cursor__pest'"></div>
  </div>
</template>

// packages/ds-react/src/components/SlinkyCursor/SlinkyCursor.tsx
// @generated:start imports
import { type ReactNode } from "react";
import "./SlinkyCursor.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface SlinkyCursorProps {
  className?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start subcomponents

// @generated:end

// @generated:start component
export function SlinkyCursor({
  className,
  "data-testid": testId,
  ...rest
}: SlinkyCursorProps) {
  const classNames = [
    "slinky-cursor",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <div className={`${classNames}`} data-testid={testId} {...rest}>
    <div className="slinky-cursor__pest" />
  </div>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end
