// packages/ds-svelte/src/components/SlinkyCursor/SlinkyCursor.svelte
<script lang="ts">
// @generated:start imports

// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  class?: string;
}

let { class: className }: Props = $props();
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "slinky-cursor",
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes}>
  <div class={'slinky-cursor__pest'}></div>
</div>

// packages/ds-angular/src/components/SlinkyCursor/SlinkyCursor.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass } from "@angular/common";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-slinky-cursor",
  standalone: true,
  imports: [NgClass],
  template: `<div [ngClass]="classes()">
  <div [ngClass]="'slinky-cursor__pest'"></div>
</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SlinkyCursorComponent {
  @Input() class?: string;

  classes(): string {
    return [
      "slinky-cursor",
      this.class,
    ].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end
