// packages/ds-svelte/src/components/TextField/TextField.svelte
<script lang="ts">
// @generated:start imports
import { useTextField } from "./useTextField.svelte.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  type?: string;
  value?: string;
  defaultValue?: string;
  onChange?: (value: string) => void;
  invalid?: boolean;
  disabled?: boolean;
  required?: boolean;
  name?: string;
  ariaDescribedby?: string;
  class?: string;
  description?: import('svelte').Snippet;
  error?: import('svelte').Snippet;
  label?: import('svelte').Snippet;
}

let { type, value, defaultValue, onChange, invalid, disabled, required, name, ariaDescribedby, class: className, description, error, label }: Props = $props();
// @generated:end

// @generated:start hook
const behavior = useTextField({
  value: () => value,
  defaultValue: () => defaultValue,
  onChange: () => onChange,
});
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "text-field",
    invalid ? "text-field--invalid" : null,
    disabled ? "text-field--disabled" : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @generated:start fieldAssociation
const instanceId = $props.id();
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} data-fsds-component="text-field">
  <label class={'text-field__label'} id={`${instanceId}-label`}>
    {@render label?.()}
  </label>
  <input class={'text-field__field'} onchange={(e) => behavior.setValue((e.currentTarget as HTMLInputElement).value)} type={type} value={behavior.value} disabled={disabled} name={name} required={required} aria-invalid={invalid} aria-labelledby={label ? `${instanceId}-label` : undefined} aria-describedby={[description ? `${instanceId}-description` : null, error && invalid ? `${instanceId}-error` : null, ariaDescribedby].filter(Boolean).join(' ') || undefined} />
  <span class={'text-field__description'} id={`${instanceId}-description`}>
    {@render description?.()}
  </span>
  <span class={'text-field__error'} role="alert" id={`${instanceId}-error`}>
    {@render error?.()}
  </span>
</div>

// packages/ds-vue/src/components/TextField/TextField.vue
<script setup lang="ts">
// @generated:start imports
import { computed, useId } from "vue";
import { useTextField } from "./useTextField.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  type?: string;
  value?: string;
  defaultValue?: string;
  onChange?: (value: string) => void;
  invalid?: boolean;
  disabled?: boolean;
  required?: boolean;
  name?: string;
  ariaDescribedby?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  invalid: undefined,
  disabled: undefined,
  required: undefined,
});
// @generated:end

// @generated:start hook
const behavior = useTextField({
  value: () => props.value,
  defaultValue: props.defaultValue,
  onChange: props.onChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "text-field",
  props.invalid ? "text-field--invalid" : null,
  props.disabled ? "text-field--disabled" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @generated:start fieldAssociation
const instanceId = useId();
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" :data-testid="props['data-testid']" data-fsds-component="text-field">
    <label :class="'text-field__label'" :id="`${instanceId}-label`">
      <slot name="label" />
    </label>
    <input :class="'text-field__field'" @input="(e) => behavior.setValue((e.target as HTMLInputElement).value)" :type="props.type" :value="behavior.value.value" :disabled="props.disabled" :name="props.name" :required="props.required" :aria-invalid="props.invalid" :aria-labelledby="$slots.label ? `${instanceId}-label` : undefined" :aria-describedby="[$slots.description ? `${instanceId}-description` : null, $slots.error && props.invalid ? `${instanceId}-error` : null, props.ariaDescribedby].filter(Boolean).join(' ') || undefined" />
    <span :class="'text-field__description'" :id="`${instanceId}-description`">
      <slot name="description" />
    </span>
    <span :class="'text-field__error'" role="alert" :id="`${instanceId}-error`">
      <slot name="error" />
    </span>
  </div>
</template>
