// packages/ds-vue/src/components/Alert/Alert.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { Stack } from "../../primitives/index.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type AlertIntent = "info" | "success" | "warning" | "danger";
export type AlertLevel = "inline" | "section" | "page";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  intent?: AlertIntent;
  level?: AlertLevel;
  dismissible?: boolean;
  icon?: unknown;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "alert",
  props.intent ? `alert--${props.intent}` : null,
  props.level ? `alert--${props.level}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <Stack role="alert" :data-testid="props['data-testid']" :class="classNames">
    <slot />
  </Stack>
</template>

// packages/ds-react/src/components/Alert/Alert.tsx
// @generated:start imports
import { type ReactNode } from "react";
import { Stack } from "../../primitives";
import "./Alert.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type AlertIntent = "info" | "success" | "warning" | "danger";

export type AlertLevel = "inline" | "section" | "page";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface AlertProps {
  intent?: AlertIntent;
  level?: AlertLevel;
  dismissible?: boolean;
  icon?: ReactNode;
  className?: string;
  "data-testid"?: string;
  children?: ReactNode;
}
// @generated:end

// @generated:start subcomponents
export interface AlertBodyProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function AlertBody({
  children,
  className,
  "data-testid": testId,
}: AlertBodyProps) {
  const classNames = ["alert__body", className].filter(Boolean).join(" ");
  return (
    <Stack className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface AlertTitleProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function AlertTitle({
  children,
  className,
  "data-testid": testId,
}: AlertTitleProps) {
  const classNames = ["alert__title", className].filter(Boolean).join(" ");
  return (
    <Stack as="h3" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}
// @generated:end

// @generated:start component
export function Alert({
  intent,
  level,
  className,
  "data-testid": testId,
  children,
  dismissible,
  icon,
  ...rest
}: AlertProps) {
  const classNames = [
    "alert",
    intent && `alert--${intent}`,
    level && `alert--${level}`,
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <Stack
      role="alert"
      className={classNames}
      data-testid={testId}
      {...rest}
    >
      {children}
    </Stack>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end
