// packages/ds-react/src/primitives/hooks/createCompoundContext.ts
import { type Context, createContext, useContext } from "react";

/**
 * Helper for compound components (Tabs, Accordion, Dropdown, Menu, …):
 * creates a typed React context plus a `useX` consumer that throws when
 * called outside the provider.
 *
 * Generated hook code uses this so each compound component avoids
 * re-implementing the same null-check + descriptive-error boilerplate.
 *
 * Usage:
 *   const [TabsContextProvider, useTabsContext, TabsContext] =
 *     createCompoundContext<TabsContextValue>("Tabs");
 */
export function createCompoundContext<T>(
  name: string,
): [Context<T | null>["Provider"], () => T, Context<T | null>] {
  const ctx = createContext<T | null>(null);
  ctx.displayName = `${name}Context`;
  function useCompoundContext(): T {
    const value = useContext(ctx);
    if (value === null) {
      throw new Error(
        `${name} compound component used outside of <${name}> provider.`,
      );
    }
    return value;
  }
  return [ctx.Provider, useCompoundContext, ctx];
}

// packages/ds-angular/src/primitives/hooks/createCompoundContext.ts
import { InjectionToken, inject } from '@angular/core';

/**
 * Angular equivalent of Vue's createCompoundContext / React's createContext.
 *
 * Returns a typed InjectionToken and a `useContext()` helper that throws a
 * descriptive error when used outside the providing component.
 *
 * Usage:
 *   const { token: TabsContextToken, useContext: useTabsContext } =
 *     createCompoundContext<TabsContextValue>("Tabs");
 *
 *   // In <Tabs> providers array:
 *   providers: [{ provide: TabsContextToken, useValue: state }]
 *
 *   // In any descendant <TabsTab> / <TabsPanel>:
 *   const ctx = useTabsContext();  // throws if outside <Tabs>
 */
export function createCompoundContext<T>(displayName: string): {
  token: InjectionToken<T>;
  useContext: () => T;
} {
  const token = new InjectionToken<T>(`${displayName}Context`);

  function useContext(): T {
    const ctx = inject(token, { optional: true });
    if (ctx == null) {
      throw new Error(
        `${displayName} compound component used outside of its provider. ` +
        `Ensure a parent component provides the "${displayName}Context" token.`,
      );
    }
    return ctx;
  }

  return { token, useContext };
}
