// packages/ds-svelte/src/components/ToggleSwitch/ToggleSwitch.svelte
<script lang="ts">
// @generated:start imports
import { useToggleSwitch } from "./useToggleSwitch.svelte.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type ToggleSwitchSize = "small" | "medium" | "large";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  checked?: boolean;
  defaultChecked?: boolean;
  onChange?: (checked: boolean) => void;
  size?: ToggleSwitchSize;
  disabled?: boolean;
  ariaLabel?: string;
  ariaDescribedby?: string;
  class?: string;
}

let { checked, defaultChecked, onChange, size = "medium", disabled, ariaLabel, ariaDescribedby, class: className }: Props = $props();
// @generated:end

// @generated:start hook
const behavior = useToggleSwitch({
  checked: () => checked,
  defaultChecked: () => defaultChecked,
  onChange: () => onChange,
});
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "toggle-switch",
    size ? `toggle-switch--${size}` : null,
    behavior.checked ? "toggle-switch--checked" : null,
    disabled ? "toggle-switch--disabled" : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<button class={classes} type="button" onclick={() => behavior.setChecked(!behavior.checked)} aria-checked={behavior.checked} aria-label={ariaLabel} aria-describedby={ariaDescribedby} disabled={disabled} data-fsds-component="toggle-switch" data-fsds-box="" role="switch"></button>

// packages/ds-vue/src/components/ToggleSwitch/ToggleSwitch.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useToggleSwitch } from "./useToggleSwitch.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type ToggleSwitchSize = "small" | "medium" | "large";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  checked?: boolean;
  defaultChecked?: boolean;
  onChange?: (checked: boolean) => void;
  size?: ToggleSwitchSize;
  disabled?: boolean;
  ariaLabel?: string;
  ariaDescribedby?: string;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  checked: undefined,
  defaultChecked: undefined,
  size: "medium",
  disabled: undefined,
});
// @generated:end

// @generated:start hook
const behavior = useToggleSwitch({
  checked: () => props.checked,
  defaultChecked: props.defaultChecked,
  onChange: props.onChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "toggle-switch",
  props.size ? `toggle-switch--${props.size}` : null,
  behavior.checked.value ? "toggle-switch--checked" : null,
  props.disabled ? "toggle-switch--disabled" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <button :class="classNames" type="button" @click="() => behavior.setChecked(!behavior.checked.value)" :aria-checked="behavior.checked.value" :aria-label="props.ariaLabel" :aria-describedby="props.ariaDescribedby" :disabled="props.disabled" role="switch" :data-testid="props['data-testid']" data-fsds-component="toggle-switch" data-fsds-box=""></button>
</template>
