// packages/ds-vue/src/components/Alert/Alert.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import Button from "../Button/Button.vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type AlertIntent = "info" | "success" | "warning" | "danger";
export type AlertLevel = "inline" | "section" | "page";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  intent?: AlertIntent;
  level?: AlertLevel;
  dismissible?: boolean;
  onDismiss?: () => void;
  dismissLabel?: string;
  icon?: unknown;
  class?: string;
  dataTestid?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  dismissible: undefined,
  dismissLabel: "Dismiss",
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "alert",
  props.intent ? `alert--${props.intent}` : null,
  props.level ? `alert--${props.level}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" role="alert" :data-testid="props.dataTestid" data-fsds-component="alert" data-fsds-box="">
    <span v-if="props.icon" :class="'alert__icon'" aria-hidden="true">
      {{ props.icon }}
    </span>
    <slot />
    <Button v-if="props.dismissible" :class="'alert__dismiss'" type="button" @click="props.onDismiss?.()" :ariaLabel="props.dismissLabel" />
  </div>
</template>

// packages/ds-angular/src/components/Alert/Alert.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass, NgIf } from "@angular/common";
import { StackComponent } from "../../primitives/index.js";
import { ButtonComponent } from "../Button/Button.component.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type AlertIntent = "info" | "success" | "warning" | "danger";
export type AlertLevel = "inline" | "section" | "page";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-alert",
  standalone: true,
  imports: [NgClass, NgIf, ButtonComponent],
  host: { "data-fsds-component": "alert" },
  template: `<div [ngClass]="classes()" role="alert" data-fsds-box="">
  <ng-container *ngIf="icon">
    <span [ngClass]="'alert__icon'" aria-hidden="true">
      {{ icon }}
    </span>
  </ng-container>
  <ng-content />
  <ng-container *ngIf="dismissible">
    <fsds-button [ngClass]="'alert__dismiss'" type="button" (click)="onDismiss && onDismiss()" [ariaLabel]="(dismissLabel ?? 'Dismiss')"></fsds-button>
  </ng-container>
</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AlertComponent {
  @Input() intent?: AlertIntent;
  @Input() level?: AlertLevel;
  @Input() dismissible?: boolean;
  @Input() onDismiss?: () => void;
  @Input() dismissLabel?: string = "Dismiss";
  @Input() icon?: unknown;
  @Input() class?: string;

  classes(): string {
    return [
      "alert",
      this.intent ? `alert--${this.intent}` : null,
      this.level ? `alert--${this.level}` : null,
      this.class,
    ].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-alert-body",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AlertBodyComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["alert__body", this.class].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-alert-title",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="h3" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AlertTitleComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["alert__title", this.class].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end
