// packages/ds-angular/src/components/Shuttle/Shuttle.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy } from "@angular/core";
import { NgClass, NgFor } from "@angular/common";
import { StackComponent } from "../../primitives/index.js";
import { useShuttle } from "./useShuttle.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-shuttle",
  standalone: true,
  imports: [NgClass, NgFor],
  host: { "data-fsds-component": "shuttle" },
  template: `<ul [ngClass]="classes()" role="listbox" [attr.aria-label]="ariaLabel" data-fsds-box="">
  <ng-container *ngFor="let item of (behavior.selection() ?? []); let index = index">
    <li [ngClass]="'shuttle__item'" role="option" aria-selected="true">
      <span>
        {{ item }}
      </span>
    </li>
  </ng-container>
</ul>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ShuttleComponent {
  @Input() ariaLabel?: string;
  @Input() value?: string[];
  @Input() defaultValue?: string[] = ["alpha","beta","gamma"];
  @Input() onValueChange?: (value: string[]) => void;
  @Input() class?: string;

  private destroyRef = inject(DestroyRef);
  protected behavior = useShuttle({
    value: () => this.value,
    defaultValue: this.defaultValue,
    onValueChange: (v) => this.onValueChange?.(v),
    destroyRef: this.destroyRef,
  });

  classes = computed(() =>
    [
      "shuttle",
      this.class,
    ].filter(Boolean).join(" "),
  );
}

@Component({
  selector: "fsds-shuttle-item",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="li" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ShuttleItemComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["shuttle__item", this.class].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/Shuttle/Shuttle.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useShuttle } from "./useShuttle.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  ariaLabel?: string;
  value?: string[];
  defaultValue?: string[];
  onValueChange?: (value: string[]) => void;
  class?: string;
  dataTestid?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  defaultValue: () => (["alpha","beta","gamma"]),
});
// @generated:end

// @generated:start hook
const behavior = useShuttle({
  value: () => props.value,
  defaultValue: props.defaultValue,
  onValueChange: props.onValueChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "shuttle",
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <ul :class="classNames" role="listbox" :aria-label="props.ariaLabel" :data-testid="props.dataTestid" data-fsds-component="shuttle" data-fsds-box="">
    <li v-for="(item, index) in (behavior.selection.value ?? [])" :key="index" :class="'shuttle__item'" role="option" aria-selected="true">
      <span>
        {{ item }}
      </span>
    </li>
  </ul>
</template>
