// packages/ds-react/src/components/Shuttle/Shuttle.tsx
// @generated:start imports
import { type HTMLAttributes, type ReactNode } from "react";
import { Stack } from "../../primitives";
import { useShuttle } from "./useShuttle";
import "./Shuttle.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface ShuttleProps extends Omit<HTMLAttributes<HTMLUListElement>, "ariaLabel" | "children" | "className" | "data-testid" | "defaultValue" | "onValueChange" | "value"> {
  ariaLabel?: string;
  value?: string[];
  defaultValue?: string[];
  onValueChange?: (value: string[]) => void;
  className?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start subcomponents
export interface ShuttleItemProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function ShuttleItem({
  children,
  className,
  "data-testid": testId,
}: ShuttleItemProps) {
  const classNames = ["shuttle__item", className].filter(Boolean).join(" ");
  return (
    <Stack as="li" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}
// @generated:end

// @generated:start component
export function Shuttle({
  value: controlledValue,
  defaultValue = ["alpha","beta","gamma"],
  onValueChange,
  className,
  "data-testid": testId,
  ariaLabel,
  ...rest
}: ShuttleProps) {
  const { selection, setSelection } = useShuttle({
    value: controlledValue,
    defaultValue,
    onValueChange,
  });

  const classNames = [
    "shuttle",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <ul className={`${classNames}`} role="listbox" aria-label={ariaLabel} data-testid={testId} {...rest}>
    {(selection ?? []).map((item, index) => (
      <li className="shuttle__item" role="option" aria-selected="true" key={index}>
        <span>
          {item}
        </span>
      </li>
    ))}
  </ul>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/Shuttle/Shuttle.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useShuttle } from "./useShuttle.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  ariaLabel?: string;
  value?: string[];
  defaultValue?: string[];
  onValueChange?: (value: string[]) => void;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  defaultValue: () => (["alpha","beta","gamma"]),
});
// @generated:end

// @generated:start hook
const behavior = useShuttle({
  value: () => props.value,
  defaultValue: props.defaultValue,
  onValueChange: props.onValueChange,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "shuttle",
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <ul :class="classNames" role="listbox" :aria-label="props.ariaLabel" :data-testid="props['data-testid']">
    <li v-for="(item, index) in (behavior.selection.value ?? [])" :key="index" :class="'shuttle__item'" role="option" aria-selected="true">
      <span>
        {{ item }}
      </span>
    </li>
  </ul>
</template>
