// packages/ds-vue/src/components/Tooltip/TooltipTrigger.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { useTooltipContext } from "./useTooltip.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start defineOptions
// Multi-root template (v-if asChild / v-else button) disables Vue's
// automatic attribute fallthrough; we apply $attrs explicitly to the
// rendered host below.
defineOptions({ inheritAttrs: false });
// @generated:end

// @generated:start props
interface Props {
  /** When true, the consumer takes over the host element via
   *  the default slot's `triggerProps` bindings. When false
   *  (the default), a `<button>` is rendered. */
  asChild?: boolean;
}

const props = defineProps<Props>();
// @generated:end

// @generated:start ctx
const ctx = useTooltipContext();

/** Default-host path needs the listener-installing ref. The
 *  triggerProps bag carries the listener-skipping ref (for the
 *  slot-props host-adoption path), so we omit it here and pass
 *  registerAnchor via :ref. The rest of the bag (aria, data,
 *  handlers — none of which the default-host needs since the
 *  controller wires them as DOM listeners) is also omitted to
 *  avoid double-firing. */
const defaultHostAriaAndData = computed(() => {
  const { ref: _ref, ...rest } = ctx.triggerProps.value;
  return {
    "aria-describedby": rest["aria-describedby"],
    "aria-controls": rest["aria-controls"],
    "aria-expanded": rest["aria-expanded"],
    "aria-labelledby": rest["aria-labelledby"],
    "data-tooltip-trigger": rest["data-tooltip-trigger"],
  };
});
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <template v-if="props.asChild">
    <slot :triggerProps="ctx.triggerProps.value" />
  </template>
  <button
    v-else
    type="button"
    :ref="ctx.registerAnchor"
    v-bind="{ ...$attrs, ...defaultHostAriaAndData }"
  >
    <slot />
  </button>
</template>

// packages/ds-svelte/src/components/Tooltip/TooltipTrigger.svelte
<script lang="ts">
// @generated:start imports
import type { Snippet } from "svelte";
import { useTooltipContext } from "./useTooltip.svelte.js";
import type { SurfaceTriggerBinding } from "../../primitives/surfaces/createAnchoredSurface.svelte.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start props
interface Props {
  /** When true, the consumer takes over the host element via
   *  the `trigger` snippet prop, which receives the split
   *  `{ action, attrs }` binding. When false (default), a
   *  `<button>` is rendered around the implicit `children`. */
  asChild?: boolean;
  class?: string;
  "data-testid"?: string;
  /** Default-host content (used when asChild is false). */
  children?: Snippet;
  /** Host-adoption snippet (used when asChild is true). Receives
   *  the split binding `{ action, attrs }`. The consumer applies
   *  `use:action` and spreads `{...attrs}` on the adopted
   *  element. Applying one without the other will silently break
   *  the substrate — both are required. */
  trigger?: Snippet<[SurfaceTriggerBinding]>;
}

let {
  asChild,
  class: className,
  "data-testid": dataTestid,
  children,
  trigger,
}: Props = $props();
// @generated:end

// @generated:start ctx
const ctx = useTooltipContext();

let buttonEl: HTMLButtonElement | null = $state(null);

// Default-host path: bind the rendered <button> as the anchor
// (substrate auto-wires DOM listeners on it). The adoption path
// is owned by the binding's `action` and does not need a $effect
// here.
$effect(() => {
  if (!asChild && buttonEl) ctx.registerAnchor(buttonEl);
});

// Reactive ARIA + data subset for the default-host <button>. We
// strip event handlers because the controller wires them as DOM
// listeners in default-host mode (they would double-fire if also
// spread as Svelte handlers).
const defaultHostBindings = $derived.by(() => {
  const { attrs } = ctx.getTriggerBinding();
  const { onpointerenter, onpointerleave, onfocus, onblur, onclick, ...rest } = attrs;
  return rest;
});
// @generated:end

// @custom:start trailing

// @custom:end
</script>

{#if asChild}
  {@render trigger?.(ctx.getTriggerBinding())}
{:else}
  <button
    type="button"
    bind:this={buttonEl}
    class={className}
    data-testid={dataTestid}
    {...defaultHostBindings}
  >
    {@render children?.()}
  </button>
{/if}
