// packages/ds-react/src/components/Blockquote/Blockquote.tsx
// @generated:start imports
import { type ReactNode } from "react";
import "./Blockquote.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type BlockquoteVariant = "default" | "bordered" | "highlighted";

export type BlockquoteSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface BlockquoteProps {
  cite?: string;
  variant?: BlockquoteVariant;
  size?: BlockquoteSize;
  className?: string;
  "data-testid"?: string;
  children?: ReactNode;
}
// @generated:end

// @generated:start subcomponents

// @generated:end

// @generated:start component
export function Blockquote({
  variant,
  size,
  className,
  "data-testid": testId,
  children,
  cite,
  ...rest
}: BlockquoteProps) {
  const classNames = [
    "blockquote",
    variant && `blockquote--${variant}`,
    size && `blockquote--${size}`,
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <blockquote className={`${classNames}`} data-testid={testId} {...rest}>
    {children}
  </blockquote>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/Blockquote/Blockquote.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type BlockquoteVariant = "default" | "bordered" | "highlighted";
export type BlockquoteSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  cite?: string;
  variant?: BlockquoteVariant;
  size?: BlockquoteSize;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = defineProps<Props>();
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "blockquote",
  props.variant ? `blockquote--${props.variant}` : null,
  props.size ? `blockquote--${props.size}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <blockquote :class="classNames" :data-testid="props['data-testid']">
    <slot />
  </blockquote>
</template>
