// packages/ds-react/src/components/PageTransition/PageTransition.tsx
// @generated:start imports
import { type ReactNode } from "react";
import "./PageTransition.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface PageTransitionProps {
  transitionName?: string;
  duration?: number;
  enabled?: boolean;
  className?: string;
  "data-testid"?: string;
  children?: ReactNode;
}
// @generated:end

// @generated:start subcomponents

// @generated:end

// @generated:start component
export function PageTransition({
  className,
  "data-testid": testId,
  children,
  transitionName,
  duration,
  enabled = true,
  ...rest
}: PageTransitionProps) {
  const classNames = [
    "page-transition",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <div className={`${classNames}`} data-testid={testId} {...rest}>
    {children}
  </div>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/PageTransition/PageTransition.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  transitionName?: string;
  duration?: number;
  enabled?: boolean;
  class?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  enabled: true,
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "page-transition",
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" :data-testid="props['data-testid']">
    <slot />
  </div>
</template>
